// Code generated by sngl (fyne) from t.sngl; DO NOT EDIT.

package ui

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"time"
)

func mustParseDuration(s string) time.Duration {
	d, err := time.ParseDuration(s)
	if err != nil {
		panic(err)
	}
	return d
}

// Model holds the state for this SNGL UI.
type Model struct {
	seconds      int
	running      bool
	beats__inst0 int

	__n0 *widget.Label
	__n1 *widget.Label

	timer0Ticker *time.Ticker
	timer1Ticker *time.Ticker
}

// New creates a Model with default values.
func New() *Model {
	m := &Model{}
	m.seconds = 0
	m.running = true
	m.beats__inst0 = 0
	return m
}

func (m *Model) Seconds() int {
	return m.seconds
}

func (m *Model) SetSeconds(v int) {
	m.seconds = v
}

func (m *Model) Running() bool {
	return m.running
}

func (m *Model) SetRunning(v bool) {
	m.running = v
}

func (m *Model) Beats__inst0() int {
	return m.beats__inst0
}

func (m *Model) SetBeats__inst0(v int) {
	m.beats__inst0 = v
}

// StartTimers starts all timers; ticks are gated on each timer's enabled var.
func (m *Model) StartTimers() {
	m.timer0Ticker = time.NewTicker(5 * time.Millisecond)
	go func() {
		for range m.timer0Ticker.C {
			fyne.Do(func() {
				if !m.running {
					return
				}
				m.seconds += 1
				m.__n1.SetText(fmt.Sprint(m.seconds))

			})
		}
	}()
	m.timer1Ticker = time.NewTicker(5 * time.Millisecond)
	go func() {
		for range m.timer1Ticker.C {
			fyne.Do(func() {
				m.beats__inst0 += 1
				m.__n0.SetText(("b " + fmt.Sprint(m.beats__inst0)))

			})
		}
	}()
}

// StopTimers stops all active timers.
func (m *Model) StopTimers() {
	if m.timer0Ticker != nil {
		m.timer0Ticker.Stop()
	}
	if m.timer1Ticker != nil {
		m.timer1Ticker.Stop()
	}
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	m.__n0 = widget.NewLabel("")
	m.__n0.SetText(("b " + fmt.Sprint(m.beats__inst0)))
	m.__n1 = widget.NewLabel("")
	m.__n1.SetText(fmt.Sprint(m.seconds))
	var parts []fyne.CanvasObject
	parts = append(parts, m.__n0)
	parts = append(parts, m.__n1)
	return container.NewVBox(parts...)
}
