// Code generated by sngl (gtk4) from t.sngl; DO NOT EDIT.

package main

/*
#cgo pkg-config: gtk4
#include <gtk/gtk.h>
#include <stdlib.h>

extern void snglGoDispatch(int idx);
// g_signal_connect callbacks are invoked with the signal's signature
// (self, ...args, user_data). This one is (instance, user_data), which
// is the signature of a void signal that carries no arguments of its
// own — and gir.Signal.Connectable is what holds every connection to
// that shape, since otherwise GTK would pass the signal's first real
// argument into `data` and snglGoDispatch would fire a wildly wrong
// callback. 155 of GTK's 400 signals qualify; the rest are neither
// declared nor connectable.
static void sngl_cb(gpointer instance, gpointer data) {
    (void)instance;
    snglGoDispatch(GPOINTER_TO_INT(data));
}
static void sngl_connect(void* widget, const char* signal, int idx) {
    g_signal_connect((gpointer)widget, signal, G_CALLBACK(sngl_cb), GINT_TO_POINTER(idx));
}

extern void snglIdleCallback(void* fn);
static gboolean sngl_idle_tramp(gpointer data) {
    snglIdleCallback(data);
    return G_SOURCE_REMOVE;
}
void sngl_gtk_idle_add(void* fn) {
    g_idle_add(sngl_idle_tramp, fn);
}

// Variadic wrapper — cgo cannot call `g_signal_emit_by_name` directly
// (the `...` in its prototype trips the cgo type checker). Used by
// per-id test invokers to fire signals with no extra args.
static void sngl_emit(gpointer instance, const char *signal) {
    g_signal_emit_by_name(instance, signal);
}

// Reactive-safe entry setter — GtkEditable's set_text fires "changed"
// even when the new text equals the current text, which loops back
// through any change handler that wrote the mutating var and re-applies
// reactivity, blowing the stack. Skip the call when the value already
// matches.
// g_object_unref takes a gpointer, and a declaration that names it directly
// would need a cast a SNGL override has no way to write. The shim is where the
// cast belongs -- it is C, which is what this preamble is.
static void sngl_unref_pixbuf(GdkPixbuf *p) {
    if (p != NULL) g_object_unref(p);
}

static void sngl_set_entry_text(GtkEditable *e, const char *t) {
    const char *cur = gtk_editable_get_text(e);
    if (t == NULL) t = "";
    if (cur != NULL && strcmp(cur, t) == 0) return;
    gtk_editable_set_text(e, t);
}

// Canvas2D draw-func trampoline. gtk_drawing_area_set_draw_func wants a
// C function pointer, which cannot close over Go state — so we register
// each draw closure in the snglDrawFuncs slice and pass its index as the
// user_data. sngl_draw_tramp extracts the index and dispatches into Go,
// handing through the cairo_t. Mirrors the sngl_connect/snglGoDispatch
// signal pattern: the static helpers are defined here so they are visible
// to the C.sngl_drawing_area_set_draw call sites this file emits (cgo
// preambles are per-file), while sngl_draw_dispatch is //export-ed once in
// callbacks.go and forward-declared extern here.
extern void sngl_draw_dispatch(int idx, cairo_t* cr, int width, int height);
static void sngl_draw_tramp(GtkDrawingArea* area, cairo_t* cr, int width, int height, gpointer data) {
    (void)area;
    sngl_draw_dispatch(GPOINTER_TO_INT(data), cr, width, height);
}
static void sngl_drawing_area_set_draw(void* area, int idx) {
    gtk_drawing_area_set_draw_func(GTK_DRAWING_AREA(area), sngl_draw_tramp, GINT_TO_POINTER(idx), NULL);
}
*/
import "C"

import (
	"git.duckfam.us/jonathan/sngl/pkg/go/snglcolor"
	"math"
	"unsafe"
)

type PathCmd struct {
	Op  string
	X   float64
	Y   float64
	Cx1 float64
	Cy1 float64
	Cx2 float64
	Cy2 float64
	R   float64
}

// _snglCairoScale maps a drawing's own coordinate space onto the size GTK is
// drawing at. An empty mode leaves the context alone, which is what a canvas
// shown at its own size wants.
func _snglCairoScale(cr *C.cairo_t, pw, ph, w, h int, mode string) {
	if w <= 0 || h <= 0 || mode == "" {
		return
	}
	sx, sy := float64(pw)/float64(w), float64(ph)/float64(h)
	switch mode {
	case "stretch":
	case "fill":
		if sy > sx {
			sx = sy
		}
		sy = sx
	default:
		if sy < sx {
			sx = sy
		}
		sy = sx
	}
	C.cairo_scale(cr, C.double(sx), C.double(sy))
}

type Measurement struct {
	Px  float64
	Em  float64
	Vw  float64
	Vh  float64
	Pct float64
}

type CanvasStyle struct {
	Fill        snglcolor.Color
	Stroke      snglcolor.Color
	StrokeWidth float64
	LineCap     string
	LineJoin    string
	FontSize    float64
	FontFamily  string
}

type Color struct {
	R uint8
	G uint8
	B uint8
	A uint8
}

type Point struct {
	X float64
	Y float64
}

type Arc struct {
	Degenerate bool
	Tangent1   Point
	Tangent2   Point
	Center     Point
	Start      float64
	Sweep      float64
}

// Model holds the state and widget references for this SNGL UI.
type Model struct {
	__n0   *C.GtkDrawingArea
	__root *C.GtkBox
}

// New creates a Model with default values. Binds initialize
// sequentially so later inits can reference earlier `m.<name>` fields.
func New() *Model {
	m := &Model{}
	return m
}

func Paint(ctx *C.cairo_t, style CanvasStyle) {
	if style.Fill.A > 0 {
		Source(ctx, style.Fill)
		if style.Stroke.A > 0 {
			C.cairo_fill_preserve(ctx)
		} else {
			C.cairo_fill(ctx)
		}
	}
	if style.Stroke.A > 0 {
		C.cairo_set_line_width(ctx, C.double(style.StrokeWidth))
		C.cairo_set_line_cap(ctx, LineCap(style.LineCap))
		C.cairo_set_line_join(ctx, LineJoin(style.LineJoin))
		Source(ctx, style.Stroke)
		C.cairo_stroke(ctx)
	}
}

func LineCap(name string) C.cairo_line_cap_t {
	if name == "round" {
		return C.cairo_line_cap_t(C.int(1))
	}
	if name == "square" {
		return C.cairo_line_cap_t(C.int(2))
	}
	return C.cairo_line_cap_t(C.int(0))
}

func LineJoin(name string) C.cairo_line_join_t {
	if name == "round" {
		return C.cairo_line_join_t(C.int(1))
	}
	if name == "bevel" {
		return C.cairo_line_join_t(C.int(2))
	}
	return C.cairo_line_join_t(C.int(0))
}

func Source(ctx *C.cairo_t, c snglcolor.Color) {
	C.cairo_set_source_rgba(ctx, C.double((float64(c.R) / 255)), C.double((float64(c.G) / 255)), C.double((float64(c.B) / 255)), C.double((float64(c.A) / 255)))
}

func ArcTo(ctx *C.cairo_t, from Point, corner Point, to Point, r float64) Point {
	a := TangentArc(from, corner, to, r)
	if a.Degenerate {
		C.cairo_line_to(ctx, C.double(corner.X), C.double(corner.Y))
		return corner
	}
	C.cairo_line_to(ctx, C.double(a.Tangent1.X), C.double(a.Tangent1.Y))
	if a.Sweep < 0 {
		C.cairo_arc_negative(ctx, C.double(a.Center.X), C.double(a.Center.Y), C.double(r), C.double(a.Start), C.double((a.Start + a.Sweep)))
	} else {
		C.cairo_arc(ctx, C.double(a.Center.X), C.double(a.Center.Y), C.double(r), C.double(a.Start), C.double((a.Start + a.Sweep)))
	}
	return a.Tangent2
}

func TangentArc(from Point, corner Point, to Point, r float64) Arc {
	a1 := math.Atan2((from.Y - corner.Y), (from.X - corner.X))
	a2 := math.Atan2((to.Y - corner.Y), (to.X - corner.X))
	turn := (a2 - a1)
	if turn > 3.141592653589793 {
		turn = (turn - 6.283185307179586)
	}
	if turn < -3.141592653589793 {
		turn = (turn + 6.283185307179586)
	}
	half := (math.Abs(turn) / 2)
	if ((r <= 0) || (half < 0.0001)) || (half > 1.5706) {
		return Arc{Degenerate: true, Tangent1: corner, Tangent2: corner, Center: corner, Start: 0, Sweep: 0}
	}
	reach := (r / math.Tan(half))
	t1 := Point{X: (corner.X + (reach * math.Cos(a1))), Y: (corner.Y + (reach * math.Sin(a1)))}
	t2 := Point{X: (corner.X + (reach * math.Cos(a2))), Y: (corner.Y + (reach * math.Sin(a2)))}
	__cse0 := math.Sin(half)
	c := Point{X: (corner.X + ((r / __cse0) * math.Cos((a1 + (turn / 2))))), Y: (corner.Y + ((r / __cse0) * math.Sin((a1 + (turn / 2)))))}
	sweep := (3.141592653589793 - math.Abs(turn))
	if turn > 0 {
		sweep = -sweep
	}
	return Arc{Tangent1: t1, Tangent2: t2, Center: c, Start: math.Atan2((t1.Y - c.Y), (t1.X - c.X)), Sweep: sweep, Degenerate: false}
}

func (m *Model) _canvasDraw0(ctx *C.cairo_t) {
	C.cairo_save(ctx)
	C.cairo_rectangle(ctx, C.double(0), C.double(0), C.double(10), C.double(5))
	Paint(ctx, CanvasStyle{Fill: snglcolor.Color{R: 255, G: 0, B: 0, A: 255}, Stroke: snglcolor.Color{R: 0, G: 0, B: 255, A: 255}, StrokeWidth: 2, LineCap: "butt", LineJoin: "miter", FontSize: 16, FontFamily: "sans-serif"})
	C.cairo_restore(ctx)
	C.cairo_save(ctx)
	C.cairo_new_sub_path(ctx)
	C.cairo_arc(ctx, C.double(5), C.double(5), C.double(3), C.double(0), C.double(6.283185307179586))
	Paint(ctx, CanvasStyle{Fill: snglcolor.Color{R: 0, G: 255, B: 0, A: 255}, Stroke: snglcolor.Color{A: 0, R: 0, G: 0, B: 0}, StrokeWidth: 1, LineCap: "butt", LineJoin: "miter", FontSize: 16, FontFamily: "sans-serif"})
	C.cairo_restore(ctx)
	k := 0.5522847498307936
	ox := (3 * k)
	oy := (2 * k)
	C.cairo_save(ctx)
	C.cairo_new_sub_path(ctx)
	C.cairo_move_to(ctx, C.double(8), C.double(6))
	C.cairo_curve_to(ctx, C.double((8 + ox)), C.double(6), C.double(11), C.double((8 - oy)), C.double(11), C.double(8))
	C.cairo_curve_to(ctx, C.double(11), C.double((8 + oy)), C.double((8 + ox)), C.double(10), C.double(8), C.double(10))
	C.cairo_curve_to(ctx, C.double((8 - ox)), C.double(10), C.double(5), C.double((8 + oy)), C.double(5), C.double(8))
	C.cairo_curve_to(ctx, C.double(5), C.double((8 - oy)), C.double((8 - ox)), C.double(6), C.double(8), C.double(6))
	C.cairo_close_path(ctx)
	Paint(ctx, CanvasStyle{Stroke: snglcolor.Color{R: 255, G: 0, B: 255, A: 255}, LineCap: "round", LineJoin: "bevel", Fill: snglcolor.Color{A: 0, R: 0, G: 0, B: 0}, StrokeWidth: 1, FontSize: 16, FontFamily: "sans-serif"})
	C.cairo_restore(ctx)
	C.cairo_save(ctx)
	C.cairo_move_to(ctx, C.double(0), C.double(0))
	C.cairo_line_to(ctx, C.double(9), C.double(9))
	C.cairo_set_line_width(ctx, C.double(1.5))
	C.cairo_set_line_cap(ctx, LineCap("butt"))
	C.cairo_set_line_join(ctx, LineJoin("miter"))
	Source(ctx, snglcolor.Color{R: 0, G: 0, B: 0, A: 255})
	C.cairo_stroke(ctx)
	C.cairo_restore(ctx)
	C.cairo_save(ctx)
	C.cairo_select_font_face(ctx, C.CString("sans-serif"), C.cairo_font_slant_t(C.int(0)), C.cairo_font_weight_t(C.int(0)))
	C.cairo_set_font_size(ctx, C.double(12))
	Source(ctx, snglcolor.Color{R: 17, G: 17, B: 17, A: 255})
	C.cairo_move_to(ctx, C.double(1), C.double(9))
	C.cairo_show_text(ctx, C.CString("hi"))
	C.cairo_restore(ctx)
	pb := C.gdk_pixbuf_new_from_file_at_scale(C.CString("logo.png"), C.int(8), C.int(8), C.int(0), nil)
	if pb != nil {
		C.cairo_save(ctx)
		C.gdk_cairo_set_source_pixbuf(ctx, pb, C.double(1), C.double(1))
		C.cairo_paint(ctx)
		C.cairo_restore(ctx)
		C.sngl_unref_pixbuf(pb)
	}
	at := Point{X: 0, Y: 0}
	C.cairo_save(ctx)
	for _, c := range []PathCmd{PathCmd{Op: "moveTo", X: 0, Y: 0, Cx1: 0, Cy1: 0, Cx2: 0, Cy2: 0, R: 0}, PathCmd{Op: "lineTo", X: 4, Y: 4, Cx1: 0, Cy1: 0, Cx2: 0, Cy2: 0, R: 0}, PathCmd{Op: "bezierTo", Cx1: 1, Cy1: 1, Cx2: 2, Cy2: 2, X: 3, Y: 3, R: 0}, PathCmd{Op: "arcTo", Cx1: 5, Cy1: 0, X: 5, Y: 5, R: 2, Cx2: 0, Cy2: 0}, PathCmd{Op: "close", X: 0, Y: 0, Cx1: 0, Cy1: 0, Cx2: 0, Cy2: 0, R: 0}} {
		if c.Op == "moveTo" {
			C.cairo_move_to(ctx, C.double(c.X), C.double(c.Y))
			at = Point{X: c.X, Y: c.Y}
		}
		if c.Op == "lineTo" {
			C.cairo_line_to(ctx, C.double(c.X), C.double(c.Y))
			at = Point{X: c.X, Y: c.Y}
		}
		if c.Op == "bezierTo" {
			C.cairo_curve_to(ctx, C.double(c.Cx1), C.double(c.Cy1), C.double(c.Cx2), C.double(c.Cy2), C.double(c.X), C.double(c.Y))
			at = Point{X: c.X, Y: c.Y}
		}
		if c.Op == "arcTo" {
			at = ArcTo(ctx, at, Point{X: c.Cx1, Y: c.Cy1}, Point{X: c.X, Y: c.Y}, c.R)
		}
		if c.Op == "close" {
			C.cairo_close_path(ctx)
		}
	}
	Paint(ctx, CanvasStyle{Fill: snglcolor.Color{R: 34, G: 34, B: 34, A: 255}, Stroke: snglcolor.Color{R: 51, G: 51, B: 51, A: 255}, StrokeWidth: 1, LineCap: "butt", LineJoin: "miter", FontSize: 16, FontFamily: "sans-serif"})
	C.cairo_restore(ctx)
}

func (m *Model) buildWidgetTree() {
	if m.__root != nil {
		return
	}
	m.__root = (*C.GtkBox)(unsafe.Pointer(C.gtk_box_new(C.GTK_ORIENTATION_VERTICAL, 6)))
	m.__n0 = (*C.GtkDrawingArea)(unsafe.Pointer(C.gtk_drawing_area_new()))
	C.gtk_drawing_area_set_content_width(m.__n0, C.int(100))
	C.gtk_drawing_area_set_content_height(m.__n0, C.int(100))
	snglDrawFuncs = append(snglDrawFuncs, func(cr *C.cairo_t, pw, ph int) { _snglCairoScale(cr, pw, ph, 100, 100, ""); m._canvasDraw0(cr) })
	C.sngl_drawing_area_set_draw(unsafe.Pointer(m.__n0), C.int((len(snglDrawFuncs) - 1)))
	C.gtk_box_append((*C.GtkBox)(unsafe.Pointer(m.__root)), (*C.GtkWidget)(unsafe.Pointer(m.__n0)))
}

// BuildUI constructs the widget tree and returns the top-level window.
func (m *Model) BuildUI(app *C.GtkApplication) *C.GtkWidget {
	m.buildWidgetTree()
	win := C.gtk_application_window_new(app)
	C.gtk_window_set_default_size((*C.GtkWindow)(unsafe.Pointer(win)), 480, 640)
	C.gtk_window_set_title((*C.GtkWindow)(unsafe.Pointer(win)), C.CString("art"))
	C.gtk_window_set_child((*C.GtkWindow)(unsafe.Pointer(win)), (*C.GtkWidget)(unsafe.Pointer(m.__root)))
	return win
}
