package android

import (
	"archive/zip"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"duckfam.us/sngl/internal/jdk"
)

// directBuild compiles Kotlin sources to a signed debug APK without Gradle.
// Pipeline: aapt2 (resources) → kotlinc (with R.java) → d8 → APK assembly → sign
func directBuild(dir string, tc *toolchain, pkg string) (string, error) {
	// Point JAVA_HOME + PATH at a version-compatible JDK so kotlinc, d8, and
	// the signers all run on it — never the ambient (possibly too-new) JDK.
	home, reason := jdk.CompatibleHome(tc.jdkMin, tc.jdkMax)
	if reason != "" {
		return "", fmt.Errorf("android build: %s", reason)
	}
	os.Setenv("JAVA_HOME", home)
	jdkBin := filepath.Join(home, "bin")
	if !strings.Contains(os.Getenv("PATH"), jdkBin) {
		os.Setenv("PATH", jdkBin+string(os.PathListSeparator)+os.Getenv("PATH"))
	}

	outDir := filepath.Join(dir, "out")
	os.MkdirAll(outDir, 0o755)

	// Step 1: Extract library resources from AARs and compile with aapt2.
	// This generates real R.java with correct resource IDs.
	fmt.Fprintln(os.Stderr, "sngl: processing resources...")
	extractLibraryResources(tc, dir)
	generateLibraryIds(tc, dir)

	manifest := filepath.Join(dir, "AndroidManifest.xml")
	baseApk := filepath.Join(outDir, "base.apk")
	rJavaDir := filepath.Join(outDir, "r-java")
	os.MkdirAll(rJavaDir, 0o755)

	resDir := filepath.Join(dir, "res")
	// Collect library package names for --extra-packages so aapt2 generates
	// R.java for each library (not just the app package).
	libPackages := collectLibraryPackages(tc)

	idsFile := filepath.Join(outDir, "resource-ids.txt")
	linkArgs := []string{"link",
		"-o", baseApk,
		"-I", tc.AndroidJar,
		"--manifest", manifest,
		"--auto-add-overlay",
		"--java", rJavaDir,
		"--emit-ids", idsFile,
	}
	if len(libPackages) > 0 {
		linkArgs = append(linkArgs, "--extra-packages", strings.Join(libPackages, ":"))
	}
	if dirExists(resDir) {
		compiledRes := filepath.Join(outDir, "compiled_res.zip")
		slog.Info("exec", "cmd", "aapt2 compile", "dir", resDir)
		aapt2Compile := exec.Command(tc.Aapt2, "compile", "--dir", resDir, "-o", compiledRes)
		aapt2Compile.Stdout = os.Stderr
		aapt2Compile.Stderr = os.Stderr
		if err := aapt2Compile.Run(); err != nil {
			return "", fmt.Errorf("aapt2 compile resources failed: %w", err)
		}
		linkArgs = append(linkArgs, compiledRes)
	}
	slog.Info("exec", "cmd", "aapt2 link")
	aapt2Link := exec.Command(tc.Aapt2, linkArgs...)
	aapt2Link.Stdout = os.Stderr
	aapt2Link.Stderr = os.Stderr
	if err := aapt2Link.Run(); err != nil {
		// If linking fails (broken cross-references from library styles),
		// remove versioned values dirs and retry with base values only.
		if dirExists(resDir) {
			entries, _ := os.ReadDir(resDir)
			for _, e := range entries {
				if e.IsDir() && strings.HasPrefix(e.Name(), "values-") {
					os.RemoveAll(filepath.Join(resDir, e.Name()))
				}
			}
			// Re-compile and re-link
			compiledRes := filepath.Join(outDir, "compiled_res.zip")
			os.Remove(compiledRes)
			os.Remove(baseApk)
			recompile := exec.Command(tc.Aapt2, "compile", "--dir", resDir, "-o", compiledRes)
			recompile.Stdout = os.Stderr
			recompile.Stderr = os.Stderr
			recompile.Run()
			aapt2Retry := exec.Command(tc.Aapt2, linkArgs...)
			aapt2Retry.Stdout = os.Stderr
			aapt2Retry.Stderr = os.Stderr
			if err := aapt2Retry.Run(); err != nil {
				return "", fmt.Errorf("aapt2 link failed: %w", err)
			}
		} else {
			return "", fmt.Errorf("aapt2 link failed: %w", err)
		}
	}

	// Collect R.java files generated by aapt2
	var rJavaFiles []string
	filepath.Walk(rJavaDir, func(path string, info os.FileInfo, err error) error {
		if err == nil && strings.HasSuffix(path, ".java") {
			rJavaFiles = append(rJavaFiles, path)
		}
		return nil
	})

	// Read the resource ID map from aapt2 and generate R.kt stubs with
	// the real resource IDs for all library packages.
	resourceIDs := readResourceIDs(idsFile)
	rKtDir := filepath.Join(dir, "_rkt")
	os.MkdirAll(rKtDir, 0o755)
	generateLibraryRKotlinWithIDs(tc, rKtDir, resourceIDs)

	// Step 2: Compile app Kotlin + R.kt stubs with Compose plugin
	fmt.Fprintln(os.Stderr, "sngl: compiling Kotlin...")
	classesDir := filepath.Join(outDir, "classes")
	os.MkdirAll(classesDir, 0o755)

	ktFiles, err := filepath.Glob(filepath.Join(dir, "*.kt"))
	if err != nil || len(ktFiles) == 0 {
		return "", fmt.Errorf("no .kt files found in %s", dir)
	}
	rKtFiles, _ := filepath.Glob(filepath.Join(rKtDir, "*.kt"))
	ktFiles = append(ktFiles, rKtFiles...)

	kotlincArgs := []string{
		"-Xplugin=" + tc.ComposePlugin,
		"-Xplugin=" + tc.SerializationPlugin,
		"-cp", tc.classpath(),
		"-d", classesDir,
		"-jvm-target", "17",
		"-no-reflect",
		"-no-stdlib",
	}
	kotlincArgs = append(kotlincArgs, ktFiles...)

	slog.Info("exec", "cmd", "kotlinc", "dir", dir)
	kotlinc := exec.Command(tc.Kotlinc, kotlincArgs...)
	kotlinc.Dir = dir
	kotlinc.Stdout = os.Stderr
	kotlinc.Stderr = os.Stderr
	if err := kotlinc.Run(); err != nil {
		return "", fmt.Errorf("kotlinc failed: %w", err)
	}

	// Step 3: Convert to DEX with d8.
	// Library JARs are pre-dexed and cached so only app classes are processed
	// on each build. This cuts d8 time from ~60s to ~3s.
	fmt.Fprintln(os.Stderr, "sngl: converting to DEX...")
	dexDir := filepath.Join(outDir, "dex")
	os.MkdirAll(dexDir, 0o755)

	var classFiles []string
	filepath.Walk(classesDir, func(path string, info os.FileInfo, err error) error {
		if err == nil && strings.HasSuffix(path, ".class") {
			classFiles = append(classFiles, path)
		}
		return nil
	})

	// Pre-dex library JARs (cached)
	libDexDir := filepath.Join(tc.CacheDir, "lib-dex")
	libDexes := preDexLibraries(tc, libDexDir)

	// Dex app classes only
	appDexDir := filepath.Join(outDir, "app-dex")
	os.MkdirAll(appDexDir, 0o755)

	appD8Args := []string{
		"--lib", tc.AndroidJar,
		"--output", appDexDir,
		"--min-api", "26",
	}
	// Add library dex files as classpath (not re-dexed)
	for _, ld := range libDexes {
		appD8Args = append(appD8Args, "--classpath", ld)
	}
	appD8Args = append(appD8Args, classFiles...)

	if err := runD8(tc, appD8Args); err != nil {
		return "", fmt.Errorf("d8 (app classes) failed: %w", err)
	}

	// Merge all dex files into the output directory
	appDexFiles, _ := filepath.Glob(filepath.Join(appDexDir, "*.dex"))
	dexIndex := 0
	for _, df := range appDexFiles {
		dest := filepath.Join(dexDir, fmt.Sprintf("classes%s.dex", dexSuffix(dexIndex)))
		copyFile(df, dest)
		dexIndex++
	}
	for _, ld := range libDexes {
		ldFiles, _ := filepath.Glob(filepath.Join(ld, "*.dex"))
		for _, df := range ldFiles {
			dest := filepath.Join(dexDir, fmt.Sprintf("classes%s.dex", dexSuffix(dexIndex)))
			copyFile(df, dest)
			dexIndex++
		}
	}

	// Add DEX files to the APK (it's a zip)
	dexFiles, _ := filepath.Glob(filepath.Join(dexDir, "*.dex"))
	if len(dexFiles) == 0 {
		return "", fmt.Errorf("no DEX files produced")
	}

	if err := addFilesToZip(baseApk, dexFiles); err != nil {
		return "", fmt.Errorf("adding dex files to APK: %w", err)
	}

	// Step 4: Zipalign
	alignedApk := filepath.Join(outDir, "aligned.apk")
	if fileExists(tc.Zipalign) {
		slog.Info("exec", "cmd", "zipalign")
		zipalign := exec.Command(tc.Zipalign, "-f", "4", baseApk, alignedApk)
		zipalign.Stdout = os.Stderr
		zipalign.Stderr = os.Stderr
		if err := zipalign.Run(); err != nil {
			// Non-fatal: skip alignment
			fmt.Fprintf(os.Stderr, "sngl: warning: zipalign failed: %v\n", err)
			alignedApk = baseApk
		}
	} else {
		alignedApk = baseApk
	}

	// Step 5: Sign with debug keystore
	fmt.Fprintln(os.Stderr, "sngl: signing APK...")
	signedApk := filepath.Join(outDir, "app.apk")

	debugKeystore := filepath.Join(tc.CacheDir, "debug.keystore")
	if !fileExists(debugKeystore) {
		// Generate a debug keystore
		os.MkdirAll(filepath.Dir(debugKeystore), 0o755)
		keytool := exec.Command("keytool",
			"-genkey", "-v",
			"-keystore", debugKeystore,
			"-alias", "androiddebugkey",
			"-keyalg", "RSA",
			"-keysize", "2048",
			"-validity", "10000",
			"-storepass", "android",
			"-keypass", "android",
			"-dname", "CN=Debug",
		)
		keytool.Stdout = os.Stderr
		keytool.Stderr = os.Stderr
		if err := keytool.Run(); err != nil {
			return "", fmt.Errorf("generating debug keystore: %w", err)
		}
	}

	// Try apksigner first (from build-tools), then jarsigner
	apksigner := filepath.Join(filepath.Dir(tc.Aapt2), "apksigner")
	if fileExists(apksigner) {
		// Copy aligned to signed first (apksigner signs in-place)
		slog.Info("exec", "cmd", "apksigner sign")
		copyFile(alignedApk, signedApk)
		sign := exec.Command(apksigner, "sign",
			"--ks", debugKeystore,
			"--ks-pass", "pass:android",
			signedApk,
		)
		sign.Stdout = os.Stderr
		sign.Stderr = os.Stderr
		if err := sign.Run(); err != nil {
			return "", fmt.Errorf("apksigner failed: %w", err)
		}
	} else {
		// Fall back to jarsigner
		slog.Info("exec", "cmd", "jarsigner")
		copyFile(alignedApk, signedApk)
		sign := exec.Command("jarsigner",
			"-keystore", debugKeystore,
			"-storepass", "android",
			"-keypass", "android",
			"-signedjar", signedApk,
			alignedApk,
			"androiddebugkey",
		)
		sign.Stdout = os.Stderr
		sign.Stderr = os.Stderr
		if err := sign.Run(); err != nil {
			return "", fmt.Errorf("jarsigner failed: %w", err)
		}
	}

	return signedApk, nil
}

// generateLibraryRClasses scans AARs in the compose-libs cache for R.txt files
// and generates stub R.java/R.class files so the runtime can find them.
// collectLibraryPackages reads AndroidManifest.xml from each library AAR
// to get its package name. These are passed to aapt2 --extra-packages so
// R.java is generated for each library, not just the app.
func collectLibraryPackages(tc *toolchain) []string {
	var aars []string
	cacheDir := filepath.Join(tc.CacheDir, "compose-libs")
	cached, _ := filepath.Glob(filepath.Join(cacheDir, "*.aar"))
	aars = append(aars, cached...)

	home, _ := os.UserHomeDir()
	gradleCache := filepath.Join(home, ".gradle", "caches", "modules-2", "files-2.1")
	if dirExists(gradleCache) {
		filepath.Walk(gradleCache, func(path string, info os.FileInfo, err error) error {
			if err == nil && strings.HasSuffix(path, ".aar") && strings.Contains(path, "androidx") {
				aars = append(aars, path)
			}
			return nil
		})
	}

	seen := map[string]bool{}
	var packages []string
	for _, aarPath := range aars {
		pkg := readAARPackage(aarPath)
		if pkg != "" && !seen[pkg] {
			seen[pkg] = true
			packages = append(packages, pkg)
		}
	}
	return packages
}

func readAARPackage(aarPath string) string {
	r, err := zip.OpenReader(aarPath)
	if err != nil {
		return ""
	}
	defer r.Close()
	for _, f := range r.File {
		if f.Name == "AndroidManifest.xml" {
			rc, err := f.Open()
			if err != nil {
				return ""
			}
			data, _ := io.ReadAll(rc)
			rc.Close()
			s := string(data)
			if i := strings.Index(s, `package="`); i >= 0 {
				s = s[i+len(`package="`):]
				if before, _, ok := strings.Cut(s, `"`); ok {
					return before
				}
			}
		}
	}
	return ""
}

// generateLibraryIds reads R.txt from all library AARs and creates a
// values/lib_ids.xml declaring all id resources. This ensures aapt2 assigns
// real resource IDs for library id resources (like poolingcontainer tags).
func generateLibraryIds(tc *toolchain, dir string) {
	var aars []string
	cacheDir := filepath.Join(tc.CacheDir, "compose-libs")
	cached, _ := filepath.Glob(filepath.Join(cacheDir, "*.aar"))
	aars = append(aars, cached...)

	home, _ := os.UserHomeDir()
	gradleCache := filepath.Join(home, ".gradle", "caches", "modules-2", "files-2.1")
	if dirExists(gradleCache) {
		filepath.Walk(gradleCache, func(path string, info os.FileInfo, err error) error {
			if err == nil && strings.HasSuffix(path, ".aar") && strings.Contains(path, "androidx") {
				aars = append(aars, path)
			}
			return nil
		})
	}

	ids := map[string]bool{}
	for _, aarPath := range aars {
		_, entries := readRTxt(aarPath)
		for _, e := range entries {
			if e.rname == "id" && e.rtype == "int" {
				ids[e.name] = true
			}
		}
	}

	if len(ids) == 0 {
		return
	}

	resDir := filepath.Join(dir, "res", "values")
	os.MkdirAll(resDir, 0o755)

	var sb strings.Builder
	sb.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n")
	for name := range ids {
		fmt.Fprintf(&sb, "    <item type=\"id\" name=\"%s\" />\n", name)
	}
	sb.WriteString("</resources>\n")
	os.WriteFile(filepath.Join(resDir, "lib_ids.xml"), []byte(sb.String()), 0o644)
}

// generateLibraryRKotlinWithIDs generates R.kt files for all library packages
// using real resource IDs from aapt2's --emit-ids output.
func generateLibraryRKotlinWithIDs(tc *toolchain, rKtDir string, resourceIDs map[string]int) {
	// Detect app package from resource IDs
	appPkg := ""
	for k := range resourceIDs {
		if before, _, ok := strings.Cut(k, ":"); ok {
			appPkg = before
			break
		}
	}

	// Build resource type→name→ID map from aapt2 output
	type resEntry struct {
		name string
		id   int
	}
	resTypes := map[string][]resEntry{} // e.g. "id" → [{name, id}, ...]
	for key, id := range resourceIDs {
		// key format: "test.sngl.app:type/name"
		_, after, ok := strings.Cut(key, ":")
		if !ok {
			continue
		}
		rest := after
		before, after, ok := strings.Cut(rest, "/")
		if !ok {
			continue
		}
		resType := before
		resName := after
		resTypes[resType] = append(resTypes[resType], resEntry{resName, id})
	}

	// Collect library packages that need R classes
	var aars []string
	cacheDir := filepath.Join(tc.CacheDir, "compose-libs")
	cached, _ := filepath.Glob(filepath.Join(cacheDir, "*.aar"))
	aars = append(aars, cached...)

	home, _ := os.UserHomeDir()
	gradleCache := filepath.Join(home, ".gradle", "caches", "modules-2", "files-2.1")
	if dirExists(gradleCache) {
		filepath.Walk(gradleCache, func(path string, info os.FileInfo, err error) error {
			if err == nil && strings.HasSuffix(path, ".aar") && strings.Contains(path, "androidx") {
				aars = append(aars, path)
			}
			return nil
		})
	}

	seen := map[string]bool{}
	for _, aarPath := range aars {
		pkg, entries := readRTxt(aarPath)
		if pkg == "" || len(entries) == 0 || seen[pkg] {
			continue
		}
		seen[pkg] = true

		// Group by resource type
		types := map[string][]rEntry{}
		for _, e := range entries {
			types[e.rname] = append(types[e.rname], e)
		}

		var sb strings.Builder
		fmt.Fprintf(&sb, "package %s\n\n", pkg)
		sb.WriteString("object R {\n")
		for typeName, typeEntries := range types {
			fmt.Fprintf(&sb, "    object %s {\n", typeName)
			for _, e := range typeEntries {
				// Look up real ID from aapt2 output
				key := appPkg + ":" + e.rname + "/" + e.name
				id := resourceIDs[key]
				if e.rtype == "int[]" {
					fmt.Fprintf(&sb, "        @JvmField val %s: IntArray = intArrayOf()\n", e.name)
				} else {
					fmt.Fprintf(&sb, "        @JvmField var %s: Int = 0x%08x\n", e.name, id)
				}
			}
			sb.WriteString("    }\n")
		}
		sb.WriteString("}\n")

		filename := strings.ReplaceAll(pkg, ".", "_") + "_R.kt"
		os.WriteFile(filepath.Join(rKtDir, filename), []byte(sb.String()), 0o644)
	}

	_ = appPkg
}

// readResourceIDs parses the --emit-ids output from aapt2 link.
// Format: "test.sngl.app:id/is_pooling_container_tag = 0x7f020001"
func readResourceIDs(path string) map[string]int {
	ids := map[string]int{}
	data, err := os.ReadFile(path)
	if err != nil {
		return ids
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		// Format: "pkg:type/name = 0xHHHHHHHH"
		parts := strings.SplitN(line, " = ", 2)
		if len(parts) != 2 {
			continue
		}
		var id int
		fmt.Sscanf(parts[1], "0x%x", &id)
		if id != 0 {
			ids[parts[0]] = id
		}
	}
	return ids
}

// extractLibraryResources merges res/ directories from library AARs into
// the project's res/ directory so aapt2 can compile them into the APK.
func extractLibraryResources(tc *toolchain, dir string) {
	resDir := filepath.Join(dir, "res")

	// Only extract from our explicitly downloaded AARs to avoid version
	// conflicts from the Gradle cache which may have multiple versions.
	cacheDir := filepath.Join(tc.CacheDir, "compose-libs")
	aars, _ := filepath.Glob(filepath.Join(cacheDir, "*.aar"))

	for _, aarPath := range aars {
		aarBase := filepath.Base(aarPath)
		r, err := zip.OpenReader(aarPath)
		if err != nil {
			continue
		}
		for _, f := range r.File {
			if !strings.HasPrefix(f.Name, "res/") || f.FileInfo().IsDir() {
				continue
			}
			relPath := f.Name[len("res/"):]
			// Only extract base values/ (not versioned values-vNN which
			// have cross-references to drawables/styles from other libraries).
			resType, _, _ := strings.Cut(relPath, "/")
			if resType != "values" {
				continue
			}
			// Use unique filenames per AAR to avoid overwriting
			fileName := strings.SplitN(relPath, "/", 2)[1]
			prefix := strings.TrimSuffix(aarBase, ".aar")
			prefix = strings.ReplaceAll(prefix, ".", "_")
			prefix = strings.ReplaceAll(prefix, "-", "_")
			uniqueName := prefix + "_" + fileName
			dest := filepath.Join(resDir, "values", uniqueName)
			if fileExists(dest) {
				continue
			}
			os.MkdirAll(filepath.Dir(dest), 0o755)
			rc, err := f.Open()
			if err != nil {
				continue
			}
			out, err := os.Create(dest)
			if err != nil {
				rc.Close()
				continue
			}
			io.Copy(out, rc)
			out.Close()
			rc.Close()
		}
		r.Close()
	}
}

// readRTxt extracts the package name from AndroidManifest.xml and the resource
// entries from R.txt inside an AAR.
func readRTxt(aarPath string) (string, []rEntry) {
	r, err := zip.OpenReader(aarPath)
	if err != nil {
		return "", nil
	}
	defer r.Close()

	var pkg string
	var entries []rEntry

	for _, f := range r.File {
		switch f.Name {
		case "AndroidManifest.xml":
			rc, err := f.Open()
			if err != nil {
				continue
			}
			data, _ := io.ReadAll(rc)
			rc.Close()
			// Extract package from manifest — simple string search
			s := string(data)
			if i := strings.Index(s, `package="`); i >= 0 {
				s = s[i+len(`package="`):]
				if before, _, ok := strings.Cut(s, `"`); ok {
					pkg = before
				}
			}
		case "R.txt":
			rc, err := f.Open()
			if err != nil {
				continue
			}
			data, _ := io.ReadAll(rc)
			rc.Close()
			for line := range strings.SplitSeq(string(data), "\n") {
				fields := strings.Fields(line)
				if len(fields) >= 3 {
					entries = append(entries, rEntry{
						rtype: fields[0], // int, int[]
						rname: fields[1], // id, string, etc.
						name:  fields[2],
					})
				}
			}
		}
	}
	return pkg, entries
}

type rEntry struct {
	rtype string // "int" or "int[]"
	rname string // resource type: "id", "string", "style", etc.
	name  string // resource name
}

func dexSuffix(i int) string {
	if i == 0 {
		return ""
	}
	return fmt.Sprintf("%d", i+1)
}

// preDexLibraries dexes each library JAR individually and caches the result.
// Returns a list of directories containing dex files.
// preDexLibraries dexes each library JAR individually and caches the result.
// On subsequent builds, only JARs that changed are re-dexed.
func preDexLibraries(tc *toolchain, cacheDir string) []string {
	os.MkdirAll(cacheDir, 0o755)
	allJars := append(append([]string{}, tc.ComposeJars...), tc.KotlinLibs...)

	var dexDirs []string
	var toDex []string

	for _, jar := range allJars {
		base := filepath.Base(jar)
		dexDir := filepath.Join(cacheDir, base+".dex")
		dexFile := filepath.Join(dexDir, "classes.dex")
		failMarker := filepath.Join(dexDir, ".failed")

		// Skip previously failed JARs
		if fileExists(failMarker) {
			continue
		}

		if fileExists(dexFile) {
			jarInfo, _ := os.Stat(jar)
			dexInfo, _ := os.Stat(dexFile)
			if jarInfo != nil && dexInfo != nil && !jarInfo.ModTime().After(dexInfo.ModTime()) {
				dexDirs = append(dexDirs, dexDir)
				continue
			}
		}
		toDex = append(toDex, jar)
	}

	if len(toDex) > 0 {
		fmt.Fprintf(os.Stderr, "sngl: pre-dexing %d libraries (cached for future builds)...\n", len(toDex))
		for _, jar := range toDex {
			base := filepath.Base(jar)
			dexDir := filepath.Join(cacheDir, base+".dex")
			os.MkdirAll(dexDir, 0o755)
			args := []string{
				"--lib", tc.AndroidJar,
				"--output", dexDir,
				"--min-api", "26",
				jar,
			}
			if err := runD8(tc, args); err != nil {
				os.WriteFile(filepath.Join(dexDir, ".failed"), nil, 0o644)
				continue
			}
			// d8 may succeed but produce no dex (empty/metadata-only JARs)
			if !fileExists(filepath.Join(dexDir, "classes.dex")) {
				os.WriteFile(filepath.Join(dexDir, ".failed"), nil, 0o644)
				continue
			}
			dexDirs = append(dexDirs, dexDir)
		}
	}
	return dexDirs
}

// addFilesToZip appends the given files (flattened, no path) to an existing zip archive.
func addFilesToZip(zipPath string, files []string) error {
	src, err := zip.OpenReader(zipPath)
	if err != nil {
		return err
	}
	tmp := zipPath + ".tmp"
	out, err := os.Create(tmp)
	if err != nil {
		src.Close()
		return err
	}
	w := zip.NewWriter(out)
	for _, f := range src.File {
		fw, err := w.CreateHeader(&zip.FileHeader{Name: f.Name, Method: f.Method})
		if err != nil {
			src.Close()
			out.Close()
			return err
		}
		rc, err := f.Open()
		if err != nil {
			src.Close()
			out.Close()
			return err
		}
		if _, err := io.Copy(fw, rc); err != nil {
			rc.Close()
			src.Close()
			out.Close()
			return err
		}
		rc.Close()
	}
	src.Close()
	for _, fp := range files {
		data, err := os.ReadFile(fp)
		if err != nil {
			out.Close()
			return err
		}
		fw, err := w.Create(filepath.Base(fp))
		if err != nil {
			out.Close()
			return err
		}
		if _, err := fw.Write(data); err != nil {
			out.Close()
			return err
		}
	}
	if err := w.Close(); err != nil {
		out.Close()
		return err
	}
	if err := out.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, zipPath)
}

func runD8(tc *toolchain, args []string) error {
	slog.Info("exec", "cmd", "d8")
	javaBin := javaPath(tc.jdkMin, tc.jdkMax)
	// d8 can be a jar or a wrapper script
	if strings.HasSuffix(tc.D8, ".jar") {
		javaArgs := append([]string{"-jar", tc.D8}, args...)
		cmd := exec.Command(javaBin, javaArgs...)
		cmd.Stdout = os.Stderr
		cmd.Stderr = os.Stderr
		return cmd.Run()
	}
	cmd := exec.Command(tc.D8, args...)
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	cmd.Env = append(os.Environ(), "PATH="+filepath.Dir(javaBin)+string(os.PathListSeparator)+os.Getenv("PATH"))
	return cmd.Run()
}

// javaPath returns the `java` binary of a JDK compatible with the [min, max]
// window (see jdk.CompatibleHome), or the sentinel "java" when none was found
// so callers that don't validate still produce a recognizable error.
func javaPath(minJDK, maxJDK int) string {
	home, reason := jdk.CompatibleHome(minJDK, maxJDK)
	if reason != "" {
		return "java"
	}
	return jdk.Bin(home)
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}
