// Code generated by internal/cmd/genfynehost. DO NOT EDIT.

package fynehost

import (
	canvas "fyne.io/fyne/v2/canvas"
	container "fyne.io/fyne/v2/container"
	layout "fyne.io/fyne/v2/layout"
	widget "fyne.io/fyne/v2/widget"
)

// Default is the widget set the stdlib declares, as fyne.sngl describes it.
//
// Every entry here is a Spec in that file: the constructor, the setter method
// behind each prop, the callback field behind each event. What a Spec also
// carries -- the Go type, the callback signature -- is absent, because those
// exist so the emitter can print them and a host reads both off the value.
//
// The keys are SNGL's names. An interpreted program is checked without platform
// overrides inlined, so a window is asked for `text`, never `Label`.
func Default() Registry {
	return Registry{
		"vbox": {
			New: container.NewVBox,
			Add: "Add",
		},
		"hbox": {
			New: container.NewHBox,
			Add: "Add",
		},
		"stack": {
			New: container.NewVBox,
			Add: "Add",
		},
		"scroll": {
			New:     container.NewVScroll,
			Content: "Content",
		},
		"spacer": {
			New: layout.NewSpacer,
		},
		"card": {
			New: container.NewVBox,
			Add: "Add",
		},
		"splitview": {
			New: container.NewHBox,
			Add: "Add",
		},
		"modal": {
			New: container.NewVBox,
			Add: "Add",
		},
		"drawer": {
			New: container.NewVBox,
			Add: "Add",
		},
		"popover": {
			New: container.NewVBox,
			Add: "Add",
		},
		"tooltip": {
			New: container.NewVBox,
			Add: "Add",
		},
		"tabs": {
			New: container.NewHBox,
			Add: "Add",
		},
		"toolbar": {
			New: container.NewHBox,
			Add: "Add",
		},
		"menubar": {
			New: container.NewHBox,
			Add: "Add",
		},
		"menu": {
			New: container.NewVBox,
			Add: "Add",
		},
		"table": {
			New: container.NewVBox,
			Add: "Add",
		},
		"tree": {
			New: container.NewVBox,
			Add: "Add",
		},
		"radio": {
			New: container.NewVBox,
			Add: "Add",
		},
		"text": {
			New:     widget.NewLabel,
			Setters: map[string]string{"value": "SetText"},
		},
		"badge": {
			New:     widget.NewLabel,
			Setters: map[string]string{"value": "SetText"},
		},
		"chip": {
			New:     widget.NewLabel,
			Setters: map[string]string{"label": "SetText"},
		},
		"divider": {
			New:     widget.NewLabel,
			Setters: map[string]string{"label": "SetText"},
		},
		"avatar": {
			New:     widget.NewLabel,
			Setters: map[string]string{"initials": "SetText"},
		},
		"spinner": {
			New:     widget.NewLabel,
			Setters: map[string]string{"label": "SetText"},
		},
		"progress": {
			New: widget.NewLabel,
		},
		"datepicker": {
			New:     widget.NewLabel,
			Setters: map[string]string{"placeholder": "SetText"},
		},
		"button": {
			New:      widget.NewButton,
			Setters:  map[string]string{"text": "SetText"},
			Handlers: map[string]string{"click": "OnTapped"},
		},
		"link": {
			New: widget.NewHyperlink,
		},
		"image": {
			New: canvas.NewImageFromResource,
		},
		"checkbox": {
			New:      widget.NewCheck,
			Setters:  map[string]string{"label": "SetText"},
			Handlers: map[string]string{"change": "OnChanged"},
		},
		"toggle": {
			New:      widget.NewCheck,
			Setters:  map[string]string{"label": "SetText"},
			Handlers: map[string]string{"change": "OnChanged"},
		},
		"select": {
			New:      widget.NewSelect,
			Handlers: map[string]string{"change": "OnChanged"},
		},
		"input": {
			New:      widget.NewEntry,
			Setters:  map[string]string{"placeholder": "SetPlaceHolder", "value": "SetText"},
			Handlers: map[string]string{"input": "OnChanged"},
		},
		"textarea": {
			New:      widget.NewMultiLineEntry,
			Setters:  map[string]string{"placeholder": "SetPlaceHolder", "value": "SetText"},
			Handlers: map[string]string{"input": "OnChanged"},
		},
	}
}
