// Code generated by internal/cmd/genfynehost. DO NOT EDIT.

package fynehost

import (
	canvas "fyne.io/fyne/v2/canvas"
	container "fyne.io/fyne/v2/container"
	layout "fyne.io/fyne/v2/layout"
	widget "fyne.io/fyne/v2/widget"
	fynelayout "git.duckfam.us/jonathan/sngl/pkg/go/fynelayout"
)

// Ctors is every constructor the stdlib widget set names, keyed the way a Spec
// spells it.
//
// This is the whole generated artifact. Everything else a host needs -- which
// method sets a prop, which field takes a callback, how a container attaches a
// child -- rides on the node in its Spec, and reflection reads the rest off the
// value. Go will not turn "widget.NewLabel" into a symbol, and that is the only
// reason this file exists.
//
// A worker generated for a project emits the same map from the Specs that
// program can reach, which is what makes a widget the compiler never heard of a
// rebuild rather than an impossibility.
func Ctors() map[string]any {
	return map[string]any{
		"fyne.io/fyne/v2/canvas.NewImageFromResource":                canvas.NewImageFromResource,
		"fyne.io/fyne/v2/container.NewHBox":                          container.NewHBox,
		"fyne.io/fyne/v2/container.NewVBox":                          container.NewVBox,
		"fyne.io/fyne/v2/container.NewVScroll":                       container.NewVScroll,
		"fyne.io/fyne/v2/layout.NewSpacer":                           layout.NewSpacer,
		"fyne.io/fyne/v2/widget.NewButton":                           widget.NewButton,
		"fyne.io/fyne/v2/widget.NewCheck":                            widget.NewCheck,
		"fyne.io/fyne/v2/widget.NewEntry":                            widget.NewEntry,
		"fyne.io/fyne/v2/widget.NewHyperlink":                        widget.NewHyperlink,
		"fyne.io/fyne/v2/widget.NewLabel":                            widget.NewLabel,
		"fyne.io/fyne/v2/widget.NewMultiLineEntry":                   widget.NewMultiLineEntry,
		"fyne.io/fyne/v2/widget.NewSelect":                           widget.NewSelect,
		"git.duckfam.us/jonathan/sngl/pkg/go/fynelayout.NewToplevel": fynelayout.NewToplevel,
	}
}
