//go:build !js

package optimize

import (
	"fmt"
	"strings"
	"sync"
	"testing"

	"duckfam.us/sngl/codegen/scheme/golang"
	"duckfam.us/sngl/internal/checker"
	"duckfam.us/sngl/ir"
)

// purepkgImport resolves the purepkg test package through the real go:
// importer, once. The declared types the results document is checked against
// come from there, so a fixture written against a hand-built *ir.Type would
// only be asserting itself.
var purepkgImport = sync.OnceValues(func() (*ir.NativeImport, error) {
	// The importer maps time.Duration through ir.DurationType, which the
	// #[builtin("duration")] declaration registers as sngl:time loads. The real
	// pipeline loads it in newChecker, before any import resolves; a test
	// resolving an import on its own has to say so.
	if checker.LibPackage("time") == nil {
		return nil, fmt.Errorf("sngl:time did not load")
	}
	return (&golang.GoImporter{}).Resolve("go:"+purepkgPath, projectDir())
})

// record is one line of the results file: a key, the separator, a value.
func record(key, expr string) string { return key + resultSep + expr + "\n" }

// purepkgDecls indexes purepkg's declarations the way a compilation importing
// it does, so a value naming one of its types can resolve it.
func purepkgDecls(t *testing.T) ir.NativeDecls {
	t.Helper()
	ni, err := purepkgImport()
	if err != nil {
		t.Skipf("resolving %s: %v", purepkgPath, err)
	}
	return ir.IndexNativeDecls(&ir.Package{Imports: []*ir.Import{{
		Path:   "go:" + purepkgPath,
		Alias:  "purepkg",
		Native: ni,
	}}})
}

// importedFunc returns the imported declaration of a purepkg function.
func importedFunc(t *testing.T, name string) *ir.Func {
	t.Helper()
	ni, err := purepkgImport()
	if err != nil {
		t.Skipf("resolving %s: %v", purepkgPath, err)
	}
	for _, f := range ni.Funcs {
		if f.Name == name {
			return f
		}
	}
	t.Fatalf("purepkg declares no %s", name)
	return nil
}

// checkResults runs one result record through the results reader against the
// return type of the named purepkg function.
func checkResults(t *testing.T, fn, expr string) ir.Expr {
	t.Helper()
	got, bad := readResults(t, fn, expr)
	if bad["k"] != nil {
		t.Fatalf("parseNativeResults(%s): %v", expr, bad["k"])
	}
	return got["k"]
}

// readResults is checkResults without the assertion, for the cases that are
// about the per-key error.
func readResults(t *testing.T, fn, expr string) (map[string]ir.Expr, map[string]error) {
	t.Helper()
	f := importedFunc(t, fn)
	got, bad, err := parseNativeResults("results.sngl", []byte(record("k", expr)), map[string]*ir.Type{"k": f.Return}, purepkgDecls(t))
	if err != nil {
		t.Fatalf("parseNativeResults(%s): %v", expr, err)
	}
	return got, bad
}

// The results document is the contract between pkg/go/consteval and the
// folder: what that encoder writes, this reads back — as IR checked against
// the declared type of the function that produced it.
func TestParseConstResultsScalars(t *testing.T) {
	f := importedFunc(t, "Greet")
	src := []byte("// Code generated by pkg/go/consteval. DO NOT EDIT.\n\n" +
		record("s", `"a\"b\\c\nd\{e\}"`))
	got, bad, err := parseNativeResults("results.sngl", src, map[string]*ir.Type{"s": f.Return}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if bad["s"] != nil {
		t.Fatal(bad["s"])
	}
	lit, ok := got["s"].(*ir.Literal)
	if !ok {
		t.Fatalf("s = %T", got["s"])
	}
	// Raw holds the unquoted content: the escapes the encoder added are gone.
	if lit.Value != "a\"b\\c\nd{e}" {
		t.Errorf("s = %q", lit.Value)
	}
	if lit.Type == nil || lit.Type.Kind != ir.TypeString {
		t.Errorf("s typed %v, want string", lit.Type)
	}
}

// A float whose value is a whole number stays a float. The JSON results path
// had only float64 to work with and turned every whole one into an int, so a
// function declared to return a float folded to an int literal.
func TestWholeFloatStaysFloat(t *testing.T) {
	lit, ok := checkResults(t, "Whole", "3").(*ir.Literal)
	if !ok {
		t.Fatalf("got %T", checkResults(t, "Whole", "3"))
	}
	if lit.Type == nil || lit.Type.Kind != ir.TypeFloat {
		t.Errorf("Whole() folded to %v, want float", lit.Type)
	}
}

// A duration keeps its unit, end to end: the Go importer maps time.Duration to
// the #[builtin("duration")] unit, and the encoded `250ms` checks against it.
// Both halves had to move — the importer used to type a Duration by its
// underlying int64, and the value model held only the magnitude.
func TestDurationKeepsItsUnit(t *testing.T) {
	want := importedFunc(t, "Wait").Return
	if want == nil || want.Kind != ir.TypeUnit {
		t.Fatalf("time.Duration imported as %v, want a unit type", want)
	}
	if got := unitBuiltin(want); got != ir.BuiltinDuration {
		t.Fatalf("time.Duration imported as a unit marked %q, want duration", got)
	}

	lit, ok := checkResults(t, "Wait", "250ms").(*ir.Literal)
	if !ok {
		t.Fatalf("got %T", checkResults(t, "Wait", "250ms"))
	}
	if lit.Suffix != "ms" {
		t.Errorf("Wait() folded to suffix %q, want ms", lit.Suffix)
	}
	if !lit.Type.IsAssignableTo(want) {
		t.Errorf("Wait() folded to %v, which does not fit the declared %v", lit.Type, want)
	}
}

// unitBuiltin is the #[builtin] mark on a unit type's declaration.
func unitBuiltin(t *ir.Type) ir.BuiltinKind {
	if t == nil || t.Kind != ir.TypeUnit {
		return ir.BuiltinNone
	}
	ud, _ := t.Decl.(*ir.UnitDef)
	if ud == nil {
		return ir.BuiltinNone
	}
	return ud.Builtin
}

// An encoded value that does not fit its declared type means the encoder and
// the importer disagree about the Go type, which must not reach codegen as a
// well-formed literal of the wrong type.
func TestParseConstResultsRejectsUnassignable(t *testing.T) {
	f := importedFunc(t, "Greet") // returns string
	got, bad, err := parseNativeResults("results.sngl", []byte(record("x", "250ms")), map[string]*ir.Type{"x": f.Return}, nil)
	if err != nil {
		t.Fatalf("one bad value failed the whole document: %v", err)
	}
	if got["x"] != nil {
		t.Fatal("a duration was accepted where a string was expected")
	}
	if bad["x"] == nil || !strings.Contains(bad["x"].Error(), "assignable") {
		t.Errorf("error does not report the type mismatch: %v", bad["x"])
	}
}

// A key that does not check is one key. The reader used to return on the first
// failure, so every value in the document — each from a different function with
// its own declared type — was dropped with it, silently and with no error to
// show for it.
func TestOneBadValueLeavesTheRestReadable(t *testing.T) {
	str := importedFunc(t, "Greet").Return
	src := []byte(record("bad", "250ms") + record("good", `"hi"`))
	got, bad, err := parseNativeResults("results.sngl", src, map[string]*ir.Type{"bad": str, "good": str}, nil)
	if err != nil {
		t.Fatalf("one bad value failed the whole document: %v", err)
	}
	if bad["bad"] == nil {
		t.Error("the mismatched value was accepted")
	}
	if litRaw(got["good"]) != "hi" {
		t.Errorf("good = %v (%v), want the string it encoded", got["good"], bad["good"])
	}
}

// A time.Time survives end to end for the same reason a duration does: the
// importer maps it to the datetime type and the encoder writes it as the string
// that type's domain is. Nothing pinned this before the two mappings became a
// registry, and moving them is exactly when it could have broken.
func TestTimeFoldsToDateTime(t *testing.T) {
	want := importedFunc(t, "Stamp0").Return
	if !ir.IsDateTimeStruct(want) {
		t.Fatalf("time.Time imported as %v, want the datetime type", want)
	}
	lit, ok := checkResults(t, "Stamp0", `"2026-08-24T09:30:00Z"`).(*ir.Literal)
	if !ok {
		t.Fatalf("got %T", checkResults(t, "Stamp0", `"2026-08-24T09:30:00Z"`))
	}
	if lit.Value != "2026-08-24T09:30:00Z" {
		t.Errorf("Stamp0() folded to %q", lit.Value)
	}
	if !lit.Type.IsAssignableTo(want) {
		t.Errorf("Stamp0() folded to %v, which does not fit the declared %v", lit.Type, want)
	}
}

// Field names come off the imported declaration, which is where the scheme
// importer recorded the Go name it derived each SNGL name from. Nothing here
// re-derives the mapping, so `HTTPStatus` lands on whatever the importer
// decided rather than on a second guess at the same rule.
func TestStructFieldNamesComeFromTheImport(t *testing.T) {
	lit, ok := checkResults(t, "GetMeta", `Meta{URL = "/a", ID = 7, HTTPStatus = 404}`).(*ir.StructLit)
	if !ok {
		t.Fatalf("got %T", checkResults(t, "GetMeta", `Meta{URL = "/a", ID = 7, HTTPStatus = 404}`))
	}
	if lit.Def == nil || lit.Def.Name != "Meta" {
		t.Fatalf("GetMeta() folded to a literal with Def %v, want Meta", lit.Def)
	}
	// The names the importer derived, in the order it declared them. The
	// value model held a map, so the order was alphabetical and the names
	// were a second, independent guess at the importer's rule.
	var got []string
	for _, f := range lit.Fields {
		got = append(got, f.Name)
	}
	want := []string{"url", "id", "hTTPStatus"}
	if len(got) != len(want) {
		t.Fatalf("fields %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("fields %v, want %v (the declaration's names, in its order: %v)", got, want, fieldNames(lit.Def))
		}
	}
}

func fieldNames(sd *ir.StructDef) []string {
	var out []string
	for _, f := range sd.Fields {
		out = append(out, f.Name)
	}
	return out
}

// A struct nested inside a list inside a struct keeps its own declaration at
// every level, because every level was checked against the declared type.
func TestNestedStructKeepsItsDef(t *testing.T) {
	list, ok := checkResults(t, "GetGroups", `[Group{Label = "first", Items = [Item{Name = "alpha", Value = 1}]}]`).(*ir.ListLit)
	if !ok {
		t.Fatalf("got %T", checkResults(t, "GetGroups", `[Group{Label = "first", Items = []}]`))
	}
	group, ok := list.Elems[0].(*ir.StructLit)
	if !ok || group.Def == nil || group.Def.Name != "Group" {
		t.Fatalf("element is %T with Def %v, want a Group", list.Elems[0], group)
	}
	var items *ir.ListLit
	for _, f := range group.Fields {
		if f.Name == "items" {
			items, _ = f.Value.(*ir.ListLit)
		}
	}
	if items == nil {
		t.Fatalf("group has no items list: %v", fieldNames(group.Def))
	}
	item, ok := items.Elems[0].(*ir.StructLit)
	if !ok || item.Def == nil || item.Def.Name != "Item" {
		t.Fatalf("nested element is %T with Def %v, want an Item", items.Elems[0], item)
	}
}

// An embedded struct survives end to end. The encoder used to promote its
// fields into the outer literal, which spelled a shape the importer never
// declared — `At`/`Seq` on a Record that has a `stamp` field — so the value
// either mis-named a field or failed to check. Now both sides agree.
func TestEmbeddedStructFoldsUnderItsOwnName(t *testing.T) {
	dir := projectDir()
	if dir == "" {
		t.Skip("could not find project root")
	}
	got := evalNow(t, purepkgCtx(dir), call{importedFunc(t, "GetRecord"), nil})
	if got[0].err != nil {
		t.Fatalf("GetRecord(): %v", got[0].err)
	}
	rec, ok := got[0].expr.(*ir.StructLit)
	if !ok || rec.Def == nil || rec.Def.Name != "Record" {
		t.Fatalf("GetRecord() = %T with Def %v, want a Record", got[0].expr, rec)
	}
	var stamp *ir.StructLit
	for _, f := range rec.Fields {
		if f.Name == "stamp" {
			stamp, _ = f.Value.(*ir.StructLit)
		}
	}
	if stamp == nil {
		t.Fatalf("Record has no stamp field, only %v", litFieldNames(rec))
	}
	if stamp.Def == nil || stamp.Def.Name != "Stamp" {
		t.Errorf("stamp Def = %v, want Stamp", stamp.Def)
	}
	if got := fieldRaw(stamp, "at"); got != "t0" {
		t.Errorf("stamp.at = %q, want t0", got)
	}
	if got := fieldRaw(stamp, "seq"); got != "1" {
		t.Errorf("stamp.seq = %q, want 1", got)
	}
}

// litFieldNames lists the field names a struct literal actually carries.
func litFieldNames(s *ir.StructLit) []string {
	var out []string
	for _, f := range s.Fields {
		out = append(out, f.Name)
	}
	return out
}

// Where the declared type is dyn there is nothing to map a field name
// through — so the value names its own type instead, and the declaration it
// names is the one the importer built. Before that, an element of a []any
// arrived with a nil Def and the Go field names on it.
func TestDynValueNamesItsOwnType(t *testing.T) {
	dir := projectDir()
	if dir == "" {
		t.Skip("could not find project root")
	}
	f := importedFunc(t, "Anything") // []any
	if f.Return == nil || f.Return.Elems[0].Kind != ir.TypeDyn {
		t.Fatalf("Anything() returns %v, want a list of dyn", f.Return)
	}
	got := evalNow(t, purepkgCtx(dir), call{f, nil})
	if got[0].err != nil {
		t.Fatalf("Anything(): %v", got[0].err)
	}
	list, ok := got[0].expr.(*ir.ListLit)
	if !ok {
		t.Fatalf("Anything() = %T, want a list literal", got[0].expr)
	}
	assertItem(t, list.Elems[0])
}

// The type ref rides on every struct the encoder writes, so a named struct
// nested inside a dyn one resolves too.
func TestNestedDynValueNamesItsOwnType(t *testing.T) {
	dir := projectDir()
	if dir == "" {
		t.Skip("could not find project root")
	}
	got := evalNow(t, purepkgCtx(dir), call{importedFunc(t, "AnythingNested"), nil})
	if got[0].err != nil {
		t.Fatalf("AnythingNested(): %v", got[0].err)
	}
	list, ok := got[0].expr.(*ir.ListLit)
	if !ok {
		t.Fatalf("AnythingNested() = %T, want a list literal", got[0].expr)
	}
	group, ok := list.Elems[0].(*ir.StructLit)
	if !ok || group.Def == nil || group.Def.Name != "Group" {
		t.Fatalf("element is %T with Def %v, want a Group", list.Elems[0], group)
	}
	var items *ir.ListLit
	for _, f := range group.Fields {
		if f.Name == "items" {
			items, _ = f.Value.(*ir.ListLit)
		}
	}
	if items == nil {
		t.Fatalf("group has no items list, only %v", litFieldNames(group))
	}
	assertItem(t, items.Elems[0])
}

// assertItem checks that e is a purepkg.Item with its real declaration and the
// field names that declaration gives, rather than Go's.
func assertItem(t *testing.T, e ir.Expr) {
	t.Helper()
	item, ok := e.(*ir.StructLit)
	if !ok {
		t.Fatalf("value = %T, want a struct literal", e)
	}
	if item.Def == nil || item.Def.Name != "Item" {
		t.Fatalf("value has Def %v, want the imported Item", item.Def)
	}
	if got := litFieldNames(item); len(got) != 2 || got[0] != "name" || got[1] != "value" {
		t.Errorf("fields = %v, want the declaration's names [name value]", got)
	}
}

// A value that names a type the expected type contradicts is the encoder and
// the importer having read different Go types — a compiler bug, and one that
// must cost the value rather than compile a literal of the wrong type.
//
// The disagreement is nested, where the whole value's type still fits the
// declared one and only the inner declaration is wrong: a top-level mismatch
// is already caught by comparing the value's type against the declared return
// type. Tally has Item's fields, so nothing but the named type says they
// differ.
func TestNamedTypeMustAgreeWithTheExpectedOne(t *testing.T) {
	f := importedFunc(t, "GetGroups")
	ref := func(name string) string { return `import("go:` + purepkgPath + `").` + name }
	src := record("x", `[`+ref("Group")+`{Label = "first", Items = [`+ref("Tally")+`{Name = "a", Value = 1}]}]`)
	_, bad, err := parseNativeResults("results.sngl", []byte(src), map[string]*ir.Type{"x": f.Return}, purepkgDecls(t))
	if err != nil {
		t.Fatalf("a bad value failed the whole batch: %v", err)
	}
	if bad["x"] == nil {
		t.Fatal("a Tally was accepted where an Item was declared")
	}
	if !strings.Contains(bad["x"].Error(), "Item") {
		t.Errorf("error does not name the declared type: %v", bad["x"])
	}
}

// A value the encoder could not have written fails its key, rather than
// folding to an empty value.
func TestParseConstResultsRejectsNonValue(t *testing.T) {
	f := importedFunc(t, "Greet")
	got, bad, err := parseNativeResults("results.sngl", []byte(record("x", "someFunc()")), map[string]*ir.Type{"x": f.Return}, nil)
	if err != nil {
		t.Fatalf("a bad value failed the whole document: %v", err)
	}
	if got["x"] != nil || bad["x"] == nil {
		t.Fatal("a non-literal initializer was accepted")
	}
}

// A record with no key is corruption: there is no key to report the failure
// under, so the batch as a whole fails rather than losing a value silently.
func TestParseNativeResultsRejectsCorruptRecord(t *testing.T) {
	f := importedFunc(t, "Greet")
	// Beside a well-formed record, so this is one damaged line and not the
	// whole file being in a format this reader does not know.
	src := []byte("x = = =\n" + record("good", `"hi"`))
	_, _, err := parseNativeResults("results.sngl", src, map[string]*ir.Type{"x": f.Return}, nil)
	if err == nil {
		t.Fatal("a record with no key was accepted")
	}
	if !strings.Contains(err.Error(), "has no key") {
		t.Errorf("a damaged line was reported as something else: %v", err)
	}
}

// The evaluator resolves pkg/go/consteval through the user's go.mod, so it can
// be a version of the sngl module that writes a record format this reader does
// not know. Every key then looks missing, which read as corruption of the file
// and told nobody to align the two.
func TestParseNativeResultsReportsAVersionSkew(t *testing.T) {
	f := importedFunc(t, "Greet")
	src := []byte("// Code generated by pkg/go/consteval. DO NOT EDIT.\n\n" +
		"x;\"hi\"\ny;\"there\"\n")
	_, _, err := parseNativeResults("results.sngl", src, map[string]*ir.Type{"x": f.Return}, nil)
	if err == nil {
		t.Fatal("a results file in an unknown format was accepted")
	}
	if !strings.Contains(err.Error(), "different versions") {
		t.Errorf("a version skew was reported as something else: %v", err)
	}
}

// A value that does not parse is one value: its key fails and the rest of the
// batch is still read.
func TestParseNativeResultsRejectsUnparseableValue(t *testing.T) {
	str := importedFunc(t, "Greet").Return
	src := []byte(record("bad", "= =") + record("good", `"hi"`))
	got, bad, err := parseNativeResults("results.sngl", src, map[string]*ir.Type{"bad": str, "good": str}, nil)
	if err != nil {
		t.Fatalf("one unparseable value failed the whole batch: %v", err)
	}
	if bad["bad"] == nil {
		t.Error("an unparseable value was accepted")
	}
	if litRaw(got["good"]) != "hi" {
		t.Errorf("good = %v (%v), want the string it encoded", got["good"], bad["good"])
	}
}

// The encoder writes the Go type name, so a value of the wrong type is caught
// here rather than folded into a literal shaped like the expected one. Tally
// has Item's fields, so nothing but the name distinguishes them — the check
// that the encoder and the importer read the same Go type.
func TestParseConstResultsRejectsWrongStruct(t *testing.T) {
	f := importedFunc(t, "GetTally")
	_, bad, err := parseNativeResults("results.sngl", []byte(record("x", `Item{Name = "a", Value = 1}`)), map[string]*ir.Type{"x": f.Return}, nil)
	if err != nil {
		t.Fatalf("a bad value failed the whole document: %v", err)
	}
	if bad["x"] == nil {
		t.Fatal("an Item was accepted where a Tally was expected")
	}
	if !strings.Contains(bad["x"].Error(), "Tally") {
		t.Errorf("error does not name the expected type: %v", bad["x"])
	}
}
