package optimize

import (
	"testing"
)

// The results document is the contract between pkg/go/consteval and the
// folder: what that encoder writes, this reads back.
func TestParseConstResults(t *testing.T) {
	src := []byte(`// Code generated by pkg/go/consteval. DO NOT EDIT.

const s = "a\"b\\c\nd\{e\}"
const i = 7
const neg = -7
const f = 2.5
const whole = 2.0
const yes = true
const nothing = null
const list = [1, "two", null]
const st = Item{Name = "alpha", Value = 1, URL = "/u"}
const m = {"Key" = 1, "other" = 2}
const dur = 250ms
`)
	got, err := parseConstResults("results.sngl", src)
	if err != nil {
		t.Fatalf("parseConstResults: %v", err)
	}

	want := map[string]any{
		"s":       "a\"b\\c\nd{e}",
		"i":       7,
		"neg":     -7,
		"f":       2.5,
		"whole":   2, // every number arrived as a float64 on the JSON path
		"yes":     true,
		"nothing": nil,
		"dur":     250,
	}
	for k, w := range want {
		if got[k] != w {
			t.Errorf("%s = %#v, want %#v", k, got[k], w)
		}
	}

	if l, ok := got["list"].([]any); !ok || len(l) != 3 || l[0] != 1 || l[1] != "two" || l[2] != nil {
		t.Errorf("list = %#v", got["list"])
	}

	// A struct literal names Go fields; the folder's value model uses SNGL
	// names, so the initialism collapses whole.
	st, ok := got["st"].(map[string]any)
	if !ok {
		t.Fatalf("st = %#v", got["st"])
	}
	if st["name"] != "alpha" || st["value"] != 1 || st["url"] != "/u" {
		t.Errorf("st = %#v", st)
	}

	// A map key is data, not a field name: it is not renamed.
	m, ok := got["m"].(map[string]any)
	if !ok {
		t.Fatalf("m = %#v", got["m"])
	}
	if m["Key"] != 1 || m["other"] != 2 {
		t.Errorf("m = %#v", m)
	}
}

// A value the encoder could not have written is a corrupt document, not an
// empty value.
func TestParseConstResultsRejectsNonValue(t *testing.T) {
	if _, err := parseConstResults("results.sngl", []byte("const x = someFunc()\n")); err == nil {
		t.Fatal("a non-literal initializer was accepted")
	}
}
