package sngl_test

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	sngl "git.duckfam.us/jonathan/sngl"
	"git.duckfam.us/jonathan/sngl/ir"
)

// checkedFixture parses+checks a fixture, skipping ones that don't cleanly
// check (parse error, error diagnostic, or ERROR directive).
func checkedFixture(t *testing.T, path string) *ir.Package {
	t.Helper()
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(src), "ERROR(") {
		t.Skip("error fixture")
	}
	doc, err := sngl.Parse(path, strings.NewReader(string(src)))
	if err != nil {
		t.Skipf("parse error: %v", err)
	}
	pkg, diags := sngl.Check(doc, "testdata")
	for _, d := range diags {
		if d.Severity == ir.Error {
			t.Skipf("check error: %v", d.Msg)
		}
	}
	if pkg == nil {
		t.Skip("nil package")
	}
	return pkg
}

// clearAnalysisTables nulls the pointer-keyed side tables that reflect.DeepEqual
// cannot compare across two independently-cloned graphs.
func clearAnalysisTables(pkg *ir.Package) {
	pkg.PointsTo = nil
	pkg.LiftedCaptures = nil
	pkg.AddressedVars = nil
}

func callFuncPtrs(pkg *ir.Package) map[*ir.Func]bool {
	m := map[*ir.Func]bool{}
	ir.InspectPackage(pkg, ir.Inspector{
		Expr: func(e ir.Expr) error {
			if c, ok := e.(*ir.Call); ok && c.Func != nil {
				m[c.Func] = true
			}
			return nil
		},
	})
	return m
}

// TestClonePackageStructuralEquivalence: for every clean fixture, a clone is
// (a) a distinct package, (b) structurally identical after stripping
// cross-references, and (c) shares no resolved Call.Func pointer with the
// original (proving cross-refs were re-pointed into the clone).
func TestClonePackageStructuralEquivalence(t *testing.T) {
	fixtures, _ := filepath.Glob("testdata/*.sngl")
	for _, f := range fixtures {
		t.Run(filepath.Base(f), func(t *testing.T) {
			pkg := checkedFixture(t, f)

			clone := ir.ClonePackage(pkg)
			if clone == pkg {
				t.Fatal("clone returned the same pointer")
			}

			// (c) Cross-pointer disjointness: no Call.Func shared.
			orig := callFuncPtrs(pkg)
			for f := range callFuncPtrs(clone) {
				if orig[f] {
					t.Errorf("clone shares a Call.Func pointer with the original")
					break
				}
			}

			// (b) Structural equivalence: strip both, DeepEqual. Strip a
			// fresh clone so the disjointness check above isn't affected.
			// The pointer-keyed analysis side-tables (PointsTo,
			// LiftedCaptures, AddressedVars) are nulled first: their keys are
			// node pointers that necessarily differ between two independent
			// clones, which reflect.DeepEqual cannot match even when the clone
			// is faithful. Their correct re-pointing is exercised indirectly
			// by the disjointness check above and regenerated by later passes.
			a := ir.ClonePackage(pkg)
			clearAnalysisTables(a)
			clearAnalysisTables(pkg)
			ir.StripForCompare(a)
			ir.StripForCompare(pkg)
			if !reflect.DeepEqual(pkg, a) {
				t.Errorf("clone not structurally equal to original after strip")
			}
		})
	}
}

// TestClonePackageIndependence: mutating the clone must not affect the original.
func TestClonePackageIndependence(t *testing.T) {
	pkg := checkedFixture(t, "testdata/test_stdlib.sngl")
	clone := ir.ClonePackage(pkg)

	if len(clone.Funcs) == 0 {
		t.Skip("fixture has no package funcs to mutate")
	}
	origName := pkg.Funcs[0].Name
	clone.Funcs[0].Name = "__mutated_by_clone_test__"
	if pkg.Funcs[0].Name != origName {
		t.Errorf("mutating clone changed original: %q", pkg.Funcs[0].Name)
	}
}

// TestClonePackagePreservesTypeSingletons: the immutable global Type
// singletons stay shared, so pointer-identity comparisons (e.g. against
// ir.TypString in codegen) still hold across a clone.
func TestClonePackagePreservesTypeSingletons(t *testing.T) {
	lit := &ir.Literal{Raw: "hi", Type: ir.TypString}
	fn := &ir.Func{Name: "f", Block: []ir.Stmt{&ir.Return{Value: lit}}}
	pkg := &ir.Package{Funcs: []*ir.Func{fn}}

	clone := ir.ClonePackage(pkg)
	got := clone.Funcs[0].Block[0].(*ir.Return).Value.(*ir.Literal).Type
	if got != ir.TypString {
		t.Errorf("cloned literal Type is not the shared TypString singleton")
	}
}
