package docbrowser

import (
	"fmt"
	"html"
	"net/http"

	"git.duckfam.us/jonathan/sngl/docs"
)

var _ = fmt.Sprint
var _ = html.EscapeString

// Handler returns an http.Handler that serves all routes.
func Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /", handleIndex)
	mux.HandleFunc("GET /{name}", handleDetail)
	return mux
}

func handleIndex(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	selectedIndex := 0
	_ = selectedIndex
	fmt.Fprint(w, `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SNGL Documentation</title></head><body>`)
	fmt.Fprint(w, `<div style="display:flex;flex-direction:row">`)
	fmt.Fprint(w, `<div style="gap:2px;padding:8px;width:260px;display:flex;flex-direction:column">`)
	fmt.Fprint(w, `<span style="font-size:16px;font-weight:bold;padding:8px">`)
	fmt.Fprint(w, `SNGL Docs`)
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `<a href="/button">`)
	fmt.Fprint(w, `<span>button</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/checkbox">`)
	fmt.Fprint(w, `<span>checkbox</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/hbox">`)
	fmt.Fprint(w, `<span>hbox</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/image">`)
	fmt.Fprint(w, `<span>image</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/input">`)
	fmt.Fprint(w, `<span>input</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/scroll">`)
	fmt.Fprint(w, `<span>scroll</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/slot">`)
	fmt.Fprint(w, `<span>slot</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/spacer">`)
	fmt.Fprint(w, `<span>spacer</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/stack">`)
	fmt.Fprint(w, `<span>stack</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/text">`)
	fmt.Fprint(w, `<span>text</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/vbox">`)
	fmt.Fprint(w, `<span>vbox</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/radio">`)
	fmt.Fprint(w, `<span>radio</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/select">`)
	fmt.Fprint(w, `<span>select</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/textarea">`)
	fmt.Fprint(w, `<span>textarea</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/toggle">`)
	fmt.Fprint(w, `<span>toggle</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/badge">`)
	fmt.Fprint(w, `<span>badge</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/divider">`)
	fmt.Fprint(w, `<span>divider</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/link">`)
	fmt.Fprint(w, `<span>link</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/progress">`)
	fmt.Fprint(w, `<span>progress</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/spinner">`)
	fmt.Fprint(w, `<span>spinner</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/tabs">`)
	fmt.Fprint(w, `<span>tabs</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/accordion">`)
	fmt.Fprint(w, `<span>accordion</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/drawer">`)
	fmt.Fprint(w, `<span>drawer</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/modal">`)
	fmt.Fprint(w, `<span>modal</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/popover">`)
	fmt.Fprint(w, `<span>popover</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/splitview">`)
	fmt.Fprint(w, `<span>splitview</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/tooltip">`)
	fmt.Fprint(w, `<span>tooltip</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/menu">`)
	fmt.Fprint(w, `<span>menu</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/menubar">`)
	fmt.Fprint(w, `<span>menubar</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/table">`)
	fmt.Fprint(w, `<span>table</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/toolbar">`)
	fmt.Fprint(w, `<span>toolbar</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/tree">`)
	fmt.Fprint(w, `<span>tree</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/avatar">`)
	fmt.Fprint(w, `<span>avatar</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/card">`)
	fmt.Fprint(w, `<span>card</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/chip">`)
	fmt.Fprint(w, `<span>chip</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/datepicker">`)
	fmt.Fprint(w, `<span>datepicker</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `</div>`)
	fmt.Fprint(w, `<div style="gap:16px;padding:24px;display:flex;flex-direction:column">`)
	fmt.Fprint(w, `<span style="font-size:24px;font-weight:bold">`)
	fmt.Fprint(w, `SNGL Documentation`)
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `<span>`)
	fmt.Fprint(w, `Select a component from the sidebar.`)
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `</div>`)
	fmt.Fprint(w, `</div>`)
	fmt.Fprint(w, `</body></html>`)
}

func handleDetail(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	name := r.PathValue("name")
	_ = name
	selectedIndex := 0
	_ = selectedIndex
	fmt.Fprint(w, `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Component — SNGL Docs</title></head><body>`)
	fmt.Fprint(w, `<div style="display:flex;flex-direction:row">`)
	fmt.Fprint(w, `<div style="gap:2px;padding:8px;width:260px;display:flex;flex-direction:column">`)
	fmt.Fprint(w, `<span style="font-size:16px;font-weight:bold;padding:8px">`)
	fmt.Fprint(w, `SNGL Docs`)
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `<a href="/button">`)
	fmt.Fprint(w, `<span>button</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/checkbox">`)
	fmt.Fprint(w, `<span>checkbox</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/hbox">`)
	fmt.Fprint(w, `<span>hbox</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/image">`)
	fmt.Fprint(w, `<span>image</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/input">`)
	fmt.Fprint(w, `<span>input</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/scroll">`)
	fmt.Fprint(w, `<span>scroll</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/slot">`)
	fmt.Fprint(w, `<span>slot</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/spacer">`)
	fmt.Fprint(w, `<span>spacer</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/stack">`)
	fmt.Fprint(w, `<span>stack</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/text">`)
	fmt.Fprint(w, `<span>text</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/vbox">`)
	fmt.Fprint(w, `<span>vbox</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/radio">`)
	fmt.Fprint(w, `<span>radio</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/select">`)
	fmt.Fprint(w, `<span>select</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/textarea">`)
	fmt.Fprint(w, `<span>textarea</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/toggle">`)
	fmt.Fprint(w, `<span>toggle</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/badge">`)
	fmt.Fprint(w, `<span>badge</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/divider">`)
	fmt.Fprint(w, `<span>divider</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/link">`)
	fmt.Fprint(w, `<span>link</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/progress">`)
	fmt.Fprint(w, `<span>progress</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/spinner">`)
	fmt.Fprint(w, `<span>spinner</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/tabs">`)
	fmt.Fprint(w, `<span>tabs</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/accordion">`)
	fmt.Fprint(w, `<span>accordion</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/drawer">`)
	fmt.Fprint(w, `<span>drawer</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/modal">`)
	fmt.Fprint(w, `<span>modal</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/popover">`)
	fmt.Fprint(w, `<span>popover</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/splitview">`)
	fmt.Fprint(w, `<span>splitview</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/tooltip">`)
	fmt.Fprint(w, `<span>tooltip</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/menu">`)
	fmt.Fprint(w, `<span>menu</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/menubar">`)
	fmt.Fprint(w, `<span>menubar</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/table">`)
	fmt.Fprint(w, `<span>table</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/toolbar">`)
	fmt.Fprint(w, `<span>toolbar</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/tree">`)
	fmt.Fprint(w, `<span>tree</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/avatar">`)
	fmt.Fprint(w, `<span>avatar</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/card">`)
	fmt.Fprint(w, `<span>card</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/chip">`)
	fmt.Fprint(w, `<span>chip</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `<a href="/datepicker">`)
	fmt.Fprint(w, `<span>datepicker</span>`)
	fmt.Fprint(w, `</a>`)
	fmt.Fprint(w, `</div>`)
	fmt.Fprint(w, `<div style="gap:12px;padding:24px;display:flex;flex-direction:column">`)
	fmt.Fprint(w, `<span style="font-size:24px;font-weight:bold">`)
	fmt.Fprint(w, html.EscapeString(fmt.Sprint(docs.Lookup(name).Name)))
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `<span style="color:#d29922">`)
	fmt.Fprint(w, html.EscapeString(fmt.Sprint((("[" + docs.Lookup(name).Tier) + "]"))))
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `<span>`)
	fmt.Fprint(w, html.EscapeString(fmt.Sprint(docs.Lookup(name).Doc)))
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `<span style="color:#888">`)
	fmt.Fprint(w, html.EscapeString(fmt.Sprint(("Children: " + docs.Lookup(name).Children))))
	fmt.Fprint(w, `</span>`)
	fmt.Fprint(w, `</div>`)
	fmt.Fprint(w, `</div>`)
	fmt.Fprint(w, `</body></html>`)
}
