// Code generated by sngl (gtk4) from t.sngl; DO NOT EDIT.

package main

import (
	"fmt"
	"git.duckfam.us/jonathan/sngl/pkg/go/gtk4rt"
)

type Item struct {
	Name string
}

// Model holds the state and widget references for this SNGL UI.
type Model struct {
	items        []Item
	__root       gtk4rt.Handle
	__slot0      []gtk4rt.Handle
	__inst0_live []*CardInstance
}

// New creates a Model with default values. Binds initialize
// sequentially so later inits can reference earlier `m.<name>` fields.
func New() *Model {
	m := &Model{}
	m.items = []Item{Item{Name: "a"}, Item{Name: "b"}}
	m.__root = nil
	m.__slot0 = nil
	m.__inst0_live = []*CardInstance{}
	return m
}

func (m *Model) __renderSlot0(parent gtk4rt.Handle) {
	for _, __entry := range m.__slot0 {
		gtk4rt.BoxRemove(parent, __entry)
	}
	m.__slot0 = nil
	__inst0_next := []*CardInstance{}
	__inst0_i := 0
	for _, item := range m.items {
		var __n1 *CardInstance
		if len(m.__inst0_live) > __inst0_i {
			__n1 = m.__inst0_live[__inst0_i]
			__n1.SetName(item.Name)
		} else {
			if len(m.__inst0_live) > __inst0_i {
				m.__inst0_live[__inst0_i].Destroy()
			}
			__n1__new := newCardInstance(item.Name)
			__n1 = __n1__new
		}
		__inst0_next = append(__inst0_next, __n1)
		__inst0_i = (__inst0_i + 1)
		__n1__el := __n1.Root
		gtk4rt.BoxAppend(parent, __n1__el)
		m.__slot0 = append(m.__slot0, __n1__el)
	}
	for __inst0_i_d, _ := range m.__inst0_live {
		__inst0_i_j := ((len(m.__inst0_live) - 1) - __inst0_i_d)
		if __inst0_i_j >= __inst0_i {
			m.__inst0_live[__inst0_i_j].Destroy()
		}
	}
	m.__inst0_live = __inst0_next
}

// CardInstance is one live instance of the card component.
type CardInstance struct {
	Root        gtk4rt.Handle
	__prop_name string
	clicks      int
	__root      gtk4rt.Handle
	__slot0     []gtk4rt.Handle
	__n0        gtk4rt.Handle
}

func newCardInstance(name string) *CardInstance {
	c := &CardInstance{}
	c.__prop_name = name
	c.clicks = 0
	c.__root = gtk4rt.BoxNew(gtk4rt.OrientationVertical, 6)
	c.__slot0 = nil
	c.__n0 = gtk4rt.ButtonNew()
	gtk4rt.ButtonSetLabel(c.__n0, (((c.__prop_name + " (") + fmt.Sprint(c.clicks)) + ")"))
	gtk4rt.Connect(c.__n0, "clicked", func() {
		c.clicks += 1
		gtk4rt.ButtonSetLabel(c.__n0, (((c.__prop_name + " (") + fmt.Sprint(c.clicks)) + ")"))
	})
	c.Root = c.__n0
	return c
}

func (c *CardInstance) SetName(__v string) {
	c.__prop_name = __v
	gtk4rt.ButtonSetLabel(c.__n0, (((c.__prop_name + " (") + fmt.Sprint(c.clicks)) + ")"))
}

func (c *CardInstance) Destroy() {}

func (m *Model) Items() []Item {
	return m.items
}

func (m *Model) SetItems(v []Item) {
	m.items = v
}

func (m *Model) buildWidgetTree() {
	if m.__root != nil {
		return
	}
	m.__root = gtk4rt.BoxNew(gtk4rt.OrientationVertical, 6)
	m.__renderSlot0(m.__root)
}

// BuildUI constructs the widget tree and returns the top-level window.
func (m *Model) BuildUI(app gtk4rt.Handle) gtk4rt.Handle {
	m.buildWidgetTree()
	win := gtk4rt.ApplicationWindowNew(app)
	gtk4rt.WindowSetDefaultSize(win, 480, 640)
	gtk4rt.WindowSetChild(win, m.__root)
	return win
}
