// Code generated by sngl (fyne) from t.sngl; DO NOT EDIT.

package ui

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

// Model holds the state for this SNGL UI.
type Model struct {
	items        []string
	__root       *fyne.Container
	__slot0      []fyne.CanvasObject
	__slot1      []fyne.CanvasObject
	__inst0_live []*CardInstance
}

// New creates a Model with default values.
func New() *Model {
	m := &Model{}
	m.items = []string{"a", "b"}
	m.__root = container.NewVBox()
	m.__slot0 = nil
	m.__slot1 = nil
	m.__inst0_live = []*CardInstance{}
	return m
}

func (m *Model) __renderSlot1(container *fyne.Container) {
	for _, __entry := range m.__slot1 {
		container.Remove(__entry)
	}
	m.__slot1 = nil
	__inst0_next := []*CardInstance{}
	__inst0_i := 0
	for _, it := range m.items {
		var __n2 *CardInstance
		if len(m.__inst0_live) > __inst0_i {
			__n2 = m.__inst0_live[__inst0_i]
			__n2.SetName(it)
		} else {
			if len(m.__inst0_live) > __inst0_i {
				m.__inst0_live[__inst0_i].Destroy()
			}
			__n2__new := newCardInstance(it)
			__n2 = __n2__new
		}
		__inst0_next = append(__inst0_next, __n2)
		__inst0_i = (__inst0_i + 1)
		__n2__el := __n2.Root
		container.Add(__n2__el)
		m.__slot1 = append(m.__slot1, __n2__el)
	}
	for __inst0_i_d, _ := range m.__inst0_live {
		__inst0_i_j := ((len(m.__inst0_live) - 1) - __inst0_i_d)
		if __inst0_i_j >= __inst0_i {
			m.__inst0_live[__inst0_i_j].Destroy()
		}
	}
	m.__inst0_live = __inst0_next
}

func (m *Model) Items() []string {
	return m.items
}

func (m *Model) SetItems(v []string) {
	m.items = v
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	m.__renderSlot1(m.__root)
	content := fyne.CanvasObject(widget.NewLabel(""))
	return content
}

// CardInstance is one live instance of the card component.
type CardInstance struct {
	Root        fyne.CanvasObject
	__prop_name string
	open        bool
	__root      *fyne.Container
	__slot0     []fyne.CanvasObject
	__slot1     []fyne.CanvasObject
	__n0        *widget.Button
}

func newCardInstance(name string) *CardInstance {
	c := &CardInstance{}
	c.__prop_name = name
	c.open = true
	c.__root = container.NewVBox()
	c.__slot0 = nil
	c.__slot1 = nil
	c.__n0 = widget.NewButton("", nil)
	c.__n0.SetText(c.__prop_name)
	c.__n0.OnTapped = func() {
		c.open = !c.open
		c.__renderSlot0(c.__root)
	}
	c.__renderSlot0(c.__root)
	c.Root = container.NewVBox(c.__n0, c.__root)
	return c
}

func (c *CardInstance) SetName(__v string) {
	c.__prop_name = __v
	c.__n0.SetText(c.__prop_name)
	c.__renderSlot0(c.__root)
}

func (c *CardInstance) __renderSlot0(container *fyne.Container) {
	for _, __entry := range c.__slot0 {
		container.Remove(__entry)
	}
	c.__slot0 = nil
	if c.open {
		__n1 := widget.NewLabel("")
		__n1.SetText(("body of " + c.__prop_name))
		container.Add(__n1)
		c.__slot0 = append(c.__slot0, __n1)
	}
}

func (c *CardInstance) Destroy() {}
