package codegen_test

import (
	"strings"
	"testing"

	"duckfam.us/sngl/ast"
	"duckfam.us/sngl/codegen"
	"duckfam.us/sngl/codegen/platform/html"
	"duckfam.us/sngl/internal/checker"
	"duckfam.us/sngl/ir"
)

// A target whose package is a lib/ directory and that registers no Go is a
// target all the same: the registry finds it by its layout, describes it from
// its build node's doc comment, and refuses to generate for it. `none` is the
// first, and nothing in Go names it.
func TestDeclaredTargetsComeFromLib(t *testing.T) {
	for _, tc := range []struct {
		uri    string
		target any
	}{
		{"platform/none", codegen.LookupPlatform("none")},
		{"language/none", codegen.LookupLang("none")},
	} {
		switch tg := tc.target.(type) {
		case *codegen.DeclaredPlatform:
			if tg.Description() == "" {
				t.Errorf("%s: no description", tc.uri)
			}
			if err := tg.Generate(&codegen.Request{}, nil); err == nil {
				t.Errorf("%s: Generate succeeded", tc.uri)
			}
		case *codegen.DeclaredLang:
			if tg.Description() == "" {
				t.Errorf("%s: no description", tc.uri)
			}
		default:
			t.Fatalf("%s: registered as %T, want a declared target", tc.uri, tc.target)
		}
		docs := checker.PackageSource(tc.uri)
		if len(docs) == 0 {
			t.Fatalf("%s: no source", tc.uri)
		}
		for _, d := range docs {
			if f := fileOf(d); !strings.HasPrefix(f, tc.uri+"/") {
				t.Errorf("%s: file %s is not served from lib/%s", tc.uri, f, tc.uri)
			}
		}
	}
}

func fileOf(d *ast.Document) string {
	if len(d.Stmts) == 0 || d.Stmts[0].StmtPos() == nil {
		return ""
	}
	return d.Stmts[0].StmtPos().File
}

// html's package is a lib/ directory like none's, and its node names the Go
// generator it is generated by: the registry finds the generator through the
// mark, and the package through the layout. Nothing in Go serves the package.
func TestNativeTargetFoundThroughItsMark(t *testing.T) {
	pkg := checker.LibPackage("platform/html")
	node := ir.TargetNodeOf(pkg, ir.BuiltinPlatform)
	if node == nil || node.Gen == nil || node.Gen.Native != "html" {
		t.Fatalf("sngl:platform/html's node does not say #[gen.native(\"html\")]")
	}
	if _, ok := codegen.LookupPlatform("html").(*html.Generator); !ok {
		t.Fatalf("html resolved to %T, want the Go generator its mark names", codegen.LookupPlatform("html"))
	}
	for _, d := range checker.PackageSource("platform/html") {
		if f := fileOf(d); !strings.HasPrefix(f, "platform/html/") {
			t.Errorf("file %s is not served from lib/platform/html", f)
		}
	}
}

// A node naming a generator this binary does not have is a target that
// cannot generate, and says why rather than generating nothing.
func TestNativeTargetWithNoGenerator(t *testing.T) {
	p := codegen.ResolveNative("platform/missing", "nosuchgenerator")
	err := p.(codegen.PlatformGenerator).Generate(&codegen.Request{}, nil)
	if err == nil || !strings.Contains(err.Error(), `"nosuchgenerator"`) {
		t.Fatalf("Generate = %v, want an error naming the generator", err)
	}
}
