// Code generated by "stringer -type=NameKind -trimprefix Name"; DO NOT EDIT.

package codegen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NameUnknown-0]
	_ = x[NameLocal-1]
	_ = x[NameStateVar-2]
	_ = x[NameComputed-3]
	_ = x[NameConst-4]
	_ = x[NameFunc-5]
	_ = x[NameExternFunc-6]
	_ = x[NameExternVar-7]
	_ = x[NameComponent-8]
	_ = x[NameNamespace-9]
}

const _NameKind_name = "UnknownLocalStateVarComputedConstFuncExternFuncExternVarComponentNamespace"

var _NameKind_index = [...]uint8{0, 7, 12, 20, 28, 33, 37, 47, 56, 65, 74}

func (i NameKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NameKind_index)-1 {
		return "NameKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NameKind_name[_NameKind_index[idx]:_NameKind_index[idx+1]]
}
