// Package consteval is the Go runtime for SNGL's compile-time evaluation of
// pure go:// functions. The compiler generates a program that calls each
// pending function and hands the result to Emit; this package encodes the
// value as SNGL source and writes the batch to the file named by
// SNGL_CONSTEVAL_OUT, which the compiler then parses.
package consteval

import (
	"bytes"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strconv"
	"sync"
)

// OutEnv names the environment variable holding the path Flush writes to.
const OutEnv = "SNGL_CONSTEVAL_OUT"

// Marshaler lets a type choose its own SNGL form. MarshalSNGL returns a SNGL
// expression, not a value: the compiler parses the bytes as source.
type Marshaler interface {
	MarshalSNGL() ([]byte, error)
}

var (
	mu       sync.Mutex
	values   = map[string][]byte{}
	failures = map[string]error{}
	custom   = map[reflect.Type]func(v any) ([]byte, error){}
)

// Register installs an encoder for a type the caller does not own (see
// stdtypes.go for time.Duration and time.Time). A Marshaler implementation
// wins over a registration; a registration wins over reflection.
func Register[T any](fn func(T) ([]byte, error)) {
	mu.Lock()
	defer mu.Unlock()
	custom[reflect.TypeFor[T]()] = func(v any) ([]byte, error) { return fn(v.(T)) }
}

// Encode returns v as SNGL source, honoring a Marshaler implementation and any
// registered encoder. It is the whole of what the compiler asks of this
// package for one value; Emit is that plus the batching Flush writes out.
func Encode(v any) ([]byte, error) {
	return appendValue(nil, reflect.ValueOf(v), 0)
}

// Emit encodes v and records it under key. An encoding error is recorded as a
// failure, so one unrepresentable value costs only its own key.
func Emit(key string, v any) {
	b, err := Encode(v)
	if err != nil {
		Fail(key, err)
		return
	}
	mu.Lock()
	defer mu.Unlock()
	delete(failures, key)
	values[key] = b
}

// Fail records that key could not be produced. Flush omits the key entirely;
// the compiler reports it by absence.
func Fail(key string, err error) {
	mu.Lock()
	defer mu.Unlock()
	delete(values, key)
	if err == nil {
		err = fmt.Errorf("no value")
	}
	failures[key] = err
}

// Flush writes every emitted value to the file named by SNGL_CONSTEVAL_OUT as
// a SNGL document of consts. Failures go to stderr: they are diagnostics for a
// human, while the compiler reads the absence of the const.
func Flush() error {
	mu.Lock()
	defer mu.Unlock()

	path := os.Getenv(OutEnv)
	if path == "" {
		return fmt.Errorf("consteval: %s is not set", OutEnv)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by pkg/go/consteval. DO NOT EDIT.\n\n")
	for _, k := range sortedKeys(values) {
		buf.WriteString("const ")
		buf.WriteString(k)
		buf.WriteString(" = ")
		buf.Write(values[k])
		buf.WriteByte('\n')
	}

	for _, k := range sortedKeys(failures) {
		fmt.Fprintf(os.Stderr, "consteval: %s: %v\n", k, failures[k])
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// reset clears recorded state. Tests only.
func reset() {
	mu.Lock()
	defer mu.Unlock()
	values = map[string][]byte{}
	failures = map[string]error{}
}

// maxDepth bounds nesting. A value that points at itself has no SNGL form,
// and recursing into one overflows the stack, which the generated program's
// per-call recover cannot catch — so the whole round would lose its results
// file rather than this one key.
const maxDepth = 64

// appendValue appends v as a SNGL expression.
func appendValue(dst []byte, v reflect.Value, depth int) ([]byte, error) {
	if !v.IsValid() {
		return append(dst, "null"...), nil
	}
	if depth > maxDepth {
		return nil, fmt.Errorf("consteval: %s nests deeper than %d levels", v.Type(), maxDepth)
	}
	if v.CanInterface() {
		// A Marshaler may hand back a slice it still owns, so the bytes are
		// appended here and never retained.
		if b, ok, err := customEncode(v); err != nil {
			return nil, err
		} else if ok {
			return append(dst, b...), nil
		}
	}

	switch v.Kind() {
	case reflect.Bool:
		return strconv.AppendBool(dst, v.Bool()), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return strconv.AppendInt(dst, v.Int(), 10), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return strconv.AppendUint(dst, v.Uint(), 10), nil
	case reflect.Float32, reflect.Float64:
		f := v.Float()
		if f != f || f > 1.7976931348623157e308 || f < -1.7976931348623157e308 {
			return nil, fmt.Errorf("consteval: %v has no SNGL form", f)
		}
		// At bitSize 64 a float32 rounds out to its float64 widening
		// (0.1 becomes 0.10000000149011612), so the fold would be a
		// different number than the function returned.
		bits := 64
		if v.Kind() == reflect.Float32 {
			bits = 32
		}
		return appendFloat(dst, f, bits), nil
	case reflect.String:
		return AppendQuote(dst, v.String()), nil
	case reflect.Pointer, reflect.Interface:
		if v.IsNil() {
			return append(dst, "null"...), nil
		}
		return appendValue(dst, v.Elem(), depth+1)
	case reflect.Slice:
		if v.IsNil() {
			return append(dst, "null"...), nil // a nil slice is absent, not empty
		}
		return appendList(dst, v, depth)
	case reflect.Array:
		return appendList(dst, v, depth)
	case reflect.Map:
		if v.IsNil() {
			return append(dst, "null"...), nil
		}
		return appendMap(dst, v, depth)
	case reflect.Struct:
		return appendStruct(dst, v, depth)
	}
	return nil, fmt.Errorf("consteval: cannot encode %s", v.Type())
}

// appendFloat writes f as a SNGL float literal. SNGL has no exponent syntax —
// `1e30` lexes as the number 1 with a unit suffix — so the format is 'f',
// never 'g'. A value with no fractional part still gets one, or the literal
// reads as an int and a large one overflows that type.
func appendFloat(dst []byte, f float64, bits int) []byte {
	out := strconv.AppendFloat(dst, f, 'f', -1, bits)
	if !bytes.ContainsRune(out[len(dst):], '.') {
		out = append(out, ".0"...)
	}
	return out
}

// customEncode applies a Marshaler implementation or a Register-ed encoder.
// The second result reports whether either applied.
func customEncode(v reflect.Value) ([]byte, bool, error) {
	if (v.Kind() == reflect.Pointer || v.Kind() == reflect.Interface) && v.IsNil() {
		return nil, false, nil
	}
	if m, ok := v.Interface().(Marshaler); ok {
		b, err := m.MarshalSNGL()
		return b, true, err
	}
	// A pointer method set reached through an addressable value: the same
	// allowance encoding/json makes.
	if v.CanAddr() {
		if m, ok := v.Addr().Interface().(Marshaler); ok {
			b, err := m.MarshalSNGL()
			return b, true, err
		}
	}
	mu.Lock()
	fn := custom[v.Type()]
	mu.Unlock()
	if fn == nil {
		return nil, false, nil
	}
	b, err := fn(v.Interface())
	return b, true, err
}

func appendList(dst []byte, v reflect.Value, depth int) ([]byte, error) {
	dst = append(dst, '[')
	for i := range v.Len() {
		if i > 0 {
			dst = append(dst, ", "...)
		}
		var err error
		if dst, err = appendValue(dst, v.Index(i), depth+1); err != nil {
			return nil, err
		}
	}
	return append(dst, ']'), nil
}

func appendMap(dst []byte, v reflect.Value, depth int) ([]byte, error) {
	entries := make([]string, 0, v.Len())
	for _, k := range v.MapKeys() {
		// A bare identifier key would make `{a = 1}` a struct literal, so a
		// string key is always quoted.
		var e []byte
		var err error
		if k.Kind() == reflect.String {
			e = AppendQuote(nil, k.String())
		} else if e, err = appendValue(nil, k, depth+1); err != nil {
			return nil, err
		}
		e = append(e, " = "...)
		if e, err = appendValue(e, v.MapIndex(k), depth+1); err != nil {
			return nil, err
		}
		entries = append(entries, string(e))
	}
	sort.Strings(entries) // map order is unspecified; the output must not be
	dst = append(dst, '{')
	for i, e := range entries {
		if i > 0 {
			dst = append(dst, ", "...)
		}
		dst = append(dst, e...)
	}
	return append(dst, '}'), nil
}

func appendStruct(dst []byte, v reflect.Value, depth int) ([]byte, error) {
	t := v.Type()
	dst = append(dst, t.Name()...)
	dst = append(dst, '{')
	wrote := false
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		if wrote {
			dst = append(dst, ", "...)
		}
		wrote = true
		// The Go field name, embedded fields included. Promoting an embedded
		// struct's fields into the outer literal would spell a shape the
		// compiler has no declaration for: the go:// importer declares an
		// embedded field under its own name like any other, so the reader
		// would see fields the struct does not have.
		dst = append(dst, f.Name...)
		dst = append(dst, " = "...)
		var err error
		if dst, err = appendValue(dst, v.Field(i), depth+1); err != nil {
			return nil, err
		}
	}
	return append(dst, '}'), nil
}

// AppendQuote appends s as a SNGL string literal. Braces are escaped because
// an unescaped `{` opens an interpolation, and the lexer has no \u escape, so
// non-ASCII runes are written through as UTF-8.
func AppendQuote(dst []byte, s string) []byte {
	dst = append(dst, '"')
	for _, r := range s {
		switch r {
		case '"':
			dst = append(dst, `\"`...)
		case '\\':
			dst = append(dst, `\\`...)
		case '{':
			dst = append(dst, `\{`...)
		case '}':
			dst = append(dst, `\}`...)
		case '\n':
			dst = append(dst, `\n`...)
		case '\t':
			dst = append(dst, `\t`...)
		case '\r':
			dst = append(dst, `\r`...)
		default:
			if r < 0x20 || r == 0x7f {
				dst = append(dst, fmt.Sprintf(`\x%02x`, r)...)
			} else {
				dst = append(dst, string(r)...)
			}
		}
	}
	return append(dst, '"')
}
