// Code generated by sngl (fyne) from t.sngl; DO NOT EDIT.

package ui

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"os"
	"time"
)

// Model holds the state for this SNGL UI.
type Model struct {
	greeting string
	busy     bool

	out  *widget.Label
	load *widget.Button
}

// New creates a Model with default values.
func New() *Model {
	m := &Model{}
	m.greeting = "idle"
	m.busy = false
	return m
}

func (m *Model) load_click_handler() {
	m.busy = true
	go func() {
		time.Sleep(300000000)
		__async_off0 := func() string { v, _ := os.Hostname(); return v }()
		fyne.Do(func() {
			m.greeting = __async_off0
			m.out.SetText(m.greeting)
			m.busy = false
		})
	}()
}

// loadClick invokes the OnTapped callback on the #load widget; for tests.
func (m *Model) loadClick() {
	if m.load.OnTapped != nil {
		m.load.OnTapped()
	}
}

func (m *Model) Greeting() string {
	return m.greeting
}

func (m *Model) SetGreeting(v string) {
	m.greeting = v
}

func (m *Model) Busy() bool {
	return m.busy
}

func (m *Model) SetBusy(v bool) {
	m.busy = v
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	m.out = widget.NewLabel("")
	m.out.SetText(m.greeting)
	m.load = widget.NewButton("", nil)
	m.load.SetText("load")
	m.load.OnTapped = m.load_click_handler
	var parts []fyne.CanvasObject
	parts = append(parts, m.out)
	parts = append(parts, m.load)
	return container.NewVBox(parts...)
}
