// Command genfynehost writes the Fyne worker's widget registry from the Specs
// in fyne.sngl.
//
// The registry is the one thing a host cannot recover by reflection: Go will
// not turn "fyne.io/fyne/v2/widget.NewLabel" into a symbol, so the constructors
// have to be named in Go source somewhere. Naming them by hand is naming them
// twice -- fyne.sngl already says which widget each component is -- and the two
// would drift silently, into a widget the tests cover and no window can build.
//
// This is the stock registry, for the widget set the stdlib declares. A worker
// generated for a project emits the same shape from the Specs *that program*
// can reach, which is what makes a third-party widget a rebuild rather than an
// impossibility.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path"
	"sort"
	"strings"

	"git.duckfam.us/jonathan/sngl/codegen"
	_ "git.duckfam.us/jonathan/sngl/codegen/platform"
	fyneplat "git.duckfam.us/jonathan/sngl/codegen/platform/fyne"
	"git.duckfam.us/jonathan/sngl/internal/checker"
	"git.duckfam.us/jonathan/sngl/internal/parser"
	"git.duckfam.us/jonathan/sngl/ir"
)

func main() {
	out := flag.String("o", "", "file to write (default: stdout)")
	flag.Parse()

	src, err := Generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genfynehost:", err)
		os.Exit(1)
	}
	if *out == "" {
		os.Stdout.Write(src)
		return
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genfynehost:", err)
		os.Exit(1)
	}
}

// Generate returns the registry source. Exported so a test can check the
// committed file against it rather than trusting that someone re-ran this.
func Generate() ([]byte, error) {
	specs, err := specs()
	if err != nil {
		return nil, err
	}
	return render(specs)
}

// probe checks the smallest program that pulls the platform in, which is all
// it takes to reach what the platform declares.
func probe() (*ir.Package, error) {
	doc, err := parser.Parse("registry.sngl", []byte(fyneplat.WidgetProbeSource))
	if err != nil {
		return nil, fmt.Errorf("parsing the widget fixture: %w", err)
	}
	plat := codegen.LookupPlatform("fyne")
	if plat == nil {
		return nil, fmt.Errorf("the fyne platform is not registered")
	}
	cfg := &checker.Config{
		IsMain:    true,
		Platforms: []ir.Platform{plat},
		Targets:   []ir.StaticTarget{{Platform: "fyne", Language: "go"}},
	}
	if l := codegen.LookupLang("go"); l != nil {
		cfg.Languages = []ir.Language{l}
	}
	pkg, diags := checker.Check(doc, cfg)
	for _, d := range diags {
		if d.Severity == ir.Error {
			return nil, fmt.Errorf("%s: %s", d.Pos, d.Msg)
		}
	}
	return pkg, nil
}

func specs() ([]fyneplat.WidgetSpec, error) {
	pkg, err := probe()
	if err != nil {
		return nil, err
	}
	return fyneplat.WidgetSpecsFrom(pkg)
}

func render(specs []fyneplat.WidgetSpec) ([]byte, error) {
	// One entry per distinct constructor. Which widget a component becomes is
	// the Spec's business and travels with the node; the constructor is the one
	// thing that has to be a Go symbol.
	ctors := map[string]string{}
	aliases := map[string]string{}
	for _, s := range specs {
		if s.CtorPath == "" {
			continue
		}
		aliases[s.CtorPath] = pkgAlias(s.CtorPath)
		ctors[s.CtorPath+"."+s.CtorName] = aliases[s.CtorPath] + "." + s.CtorName
	}
	paths := make([]string, 0, len(aliases))
	for p := range aliases {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	keys := make([]string, 0, len(ctors))
	for k := range ctors {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/cmd/genfynehost. DO NOT EDIT.

package fynehost

import (
`)
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%s %q\n", aliases[p], p)
	}
	b.WriteString(`)

// Ctors is every constructor the stdlib widget set names, keyed the way a Spec
// spells it.
//
// This is the whole generated artifact. Everything else a host needs -- which
// method sets a prop, which field takes a callback, how a container attaches a
// child -- rides on the node in its Spec, and reflection reads the rest off the
// value. Go will not turn "widget.NewLabel" into a symbol, and that is the only
// reason this file exists.
//
// A worker generated for a project emits the same map from the Specs that
// program can reach, which is what makes a widget the compiler never heard of a
// rebuild rather than an impossibility.
func Ctors() map[string]any {
	return map[string]any{
`)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t\t%q: %s,\n", k, ctors[k])
	}
	b.WriteString("\t}\n}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("the generated source does not parse: %w\n%s", err, b.String())
	}
	return src, nil
}

// pkgAlias is the identifier an import path is referred to by. The last segment
// is right except for a versioned module root, where it is a version.
func pkgAlias(p string) string {
	seg := path.Base(p)
	if len(seg) > 1 && seg[0] == 'v' && strings.IndexFunc(seg[1:], func(r rune) bool { return r < '0' || r > '9' }) < 0 {
		seg = path.Base(path.Dir(p))
	}
	return strings.ReplaceAll(seg, "-", "")
}
