// Code generated by "stringer -type=Purity -trimprefix Purity"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PurityUnknown-0]
	_ = x[PurityPure-1]
	_ = x[PurityReadonly-2]
	_ = x[PurityMutates-3]
}

const _Purity_name = "UnknownPureReadonlyMutates"

var _Purity_index = [...]uint8{0, 7, 11, 19, 26}

func (i Purity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Purity_index)-1 {
		return "Purity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Purity_name[_Purity_index[idx]:_Purity_index[idx+1]]
}
