// Code generated by "stringer -type=TypeKind -trimprefix Type"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-0]
	_ = x[TypeDyn-1]
	_ = x[TypeBool-2]
	_ = x[TypeInt-3]
	_ = x[TypeFloat-4]
	_ = x[TypeString-5]
	_ = x[TypeList-6]
	_ = x[TypeMap-7]
	_ = x[TypeOption-8]
	_ = x[TypeStruct-9]
	_ = x[TypeEnum-10]
	_ = x[TypeUnit-11]
	_ = x[TypeFunc-12]
	_ = x[TypeComponent-13]
	_ = x[TypeNull-14]
	_ = x[TypeTypeParam-15]
	_ = x[TypeVoid-16]
	_ = x[TypeRef-17]
	_ = x[TypeIter-18]
	_ = x[TypeNative-19]
	_ = x[TypeRemote-20]
}

const _TypeKind_name = "InvalidDynBoolIntFloatStringListMapOptionStructEnumUnitFuncComponentNullTypeParamVoidRefIterNativeRemote"

var _TypeKind_index = [...]uint8{0, 7, 10, 14, 17, 22, 28, 32, 35, 41, 47, 51, 55, 59, 68, 72, 81, 85, 88, 92, 98, 104}

func (i TypeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TypeKind_index)-1 {
		return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeKind_name[_TypeKind_index[idx]:_TypeKind_index[idx+1]]
}
