// Code generated by "stringer -type=TypeKind -trimprefix Type"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-0]
	_ = x[TypeDyn-1]
	_ = x[TypeBool-2]
	_ = x[TypeInt-3]
	_ = x[TypeFloat-4]
	_ = x[TypeString-5]
	_ = x[TypeList-6]
	_ = x[TypeOption-7]
	_ = x[TypeStruct-8]
	_ = x[TypeEnum-9]
	_ = x[TypeUnit-10]
	_ = x[TypeFunc-11]
	_ = x[TypeComponent-12]
	_ = x[TypeColor-13]
	_ = x[TypeDate-14]
	_ = x[TypeTime-15]
	_ = x[TypeDateTime-16]
	_ = x[TypeDuration-17]
	_ = x[TypeURL-18]
	_ = x[TypeEmail-19]
	_ = x[TypeUUID-20]
	_ = x[TypeRegex-21]
	_ = x[TypeBase64-22]
	_ = x[TypeIPV4-23]
	_ = x[TypeIPV6-24]
	_ = x[TypeHostname-25]
	_ = x[TypeDecimal-26]
	_ = x[TypeNull-27]
	_ = x[TypeTypeParam-28]
	_ = x[TypeVoid-29]
	_ = x[TypeRef-30]
}

const _TypeKind_name = "InvalidDynBoolIntFloatStringListOptionStructEnumUnitFuncComponentColorDateTimeDateTimeDurationURLEmailUUIDRegexBase64IPV4IPV6HostnameDecimalNullTypeParamVoidRef"

var _TypeKind_index = [...]uint8{0, 7, 10, 14, 17, 22, 28, 32, 38, 44, 48, 52, 56, 65, 70, 74, 78, 86, 94, 97, 102, 106, 111, 117, 121, 125, 133, 140, 144, 153, 157, 160}

func (i TypeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TypeKind_index)-1 {
		return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeKind_name[_TypeKind_index[idx]:_TypeKind_index[idx+1]]
}
