// Code generated by "stringer -type=TypeKind -trimprefix Type"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-0]
	_ = x[TypeDyn-1]
	_ = x[TypeBool-2]
	_ = x[TypeInt-3]
	_ = x[TypeFloat-4]
	_ = x[TypeString-5]
	_ = x[TypeList-6]
	_ = x[TypeMap-7]
	_ = x[TypeOption-8]
	_ = x[TypeStruct-9]
	_ = x[TypeEnum-10]
	_ = x[TypeUnit-11]
	_ = x[TypeFunc-12]
	_ = x[TypeComponent-13]
	_ = x[TypeShape-14]
	_ = x[TypeColor-15]
	_ = x[TypeDate-16]
	_ = x[TypeTime-17]
	_ = x[TypeDateTime-18]
	_ = x[TypeDuration-19]
	_ = x[TypeURL-20]
	_ = x[TypeEmail-21]
	_ = x[TypeUUID-22]
	_ = x[TypeRegex-23]
	_ = x[TypeBase64-24]
	_ = x[TypeIPV4-25]
	_ = x[TypeIPV6-26]
	_ = x[TypeHostname-27]
	_ = x[TypeDecimal-28]
	_ = x[TypeNull-29]
	_ = x[TypeTypeParam-30]
	_ = x[TypeVoid-31]
	_ = x[TypeRef-32]
	_ = x[TypeIter-33]
	_ = x[TypeNative-34]
}

const _TypeKind_name = "InvalidDynBoolIntFloatStringListMapOptionStructEnumUnitFuncComponentShapeColorDateTimeDateTimeDurationURLEmailUUIDRegexBase64IPV4IPV6HostnameDecimalNullTypeParamVoidRefIterNative"

var _TypeKind_index = [...]uint8{0, 7, 10, 14, 17, 22, 28, 32, 35, 41, 47, 51, 55, 59, 68, 73, 78, 82, 86, 94, 102, 105, 110, 114, 119, 125, 129, 133, 141, 148, 152, 161, 165, 168, 172, 178}

func (i TypeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TypeKind_index)-1 {
		return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeKind_name[_TypeKind_index[idx]:_TypeKind_index[idx+1]]
}
