// Code generated by sngl (gtk4) from t.sngl; DO NOT EDIT.

package main

/*
#cgo pkg-config: gtk4
#include <gtk/gtk.h>
#include <stdlib.h>

extern void snglGoDispatch(int idx);
// g_signal_connect callbacks are invoked with the signal's signature
// (self, ...args, user_data). This one is (instance, user_data), which
// is the signature of a void signal that carries no arguments of its
// own — and gir.Signal.Connectable is what holds every connection to
// that shape, since otherwise GTK would pass the signal's first real
// argument into `data` and snglGoDispatch would fire a wildly wrong
// callback. 155 of GTK's 400 signals qualify; the rest are neither
// declared nor connectable.
static void sngl_cb(gpointer instance, gpointer data) {
    (void)instance;
    snglGoDispatch(GPOINTER_TO_INT(data));
}
static void sngl_connect(void* widget, const char* signal, int idx) {
    g_signal_connect((gpointer)widget, signal, G_CALLBACK(sngl_cb), GINT_TO_POINTER(idx));
}

extern void snglIdleCallback(void* fn);
static gboolean sngl_idle_tramp(gpointer data) {
    snglIdleCallback(data);
    return G_SOURCE_REMOVE;
}
void sngl_gtk_idle_add(void* fn) {
    g_idle_add(sngl_idle_tramp, fn);
}

// Variadic wrapper — cgo cannot call `g_signal_emit_by_name` directly
// (the `...` in its prototype trips the cgo type checker). Used by
// per-id test invokers to fire signals with no extra args.
static void sngl_emit(gpointer instance, const char *signal) {
    g_signal_emit_by_name(instance, signal);
}

// Reactive-safe entry setter — GtkEditable's set_text fires "changed"
// even when the new text equals the current text, which loops back
// through any change handler that wrote the mutating var and re-applies
// reactivity, blowing the stack. Skip the call when the value already
// matches.
static void sngl_set_entry_text(GtkEditable *e, const char *t) {
    const char *cur = gtk_editable_get_text(e);
    if (t == NULL) t = "";
    if (cur != NULL && strcmp(cur, t) == 0) return;
    gtk_editable_set_text(e, t);
}

// Canvas2D draw-func trampoline. gtk_drawing_area_set_draw_func wants a
// C function pointer, which cannot close over Go state — so we register
// each draw closure in the snglDrawFuncs slice and pass its index as the
// user_data. sngl_draw_tramp extracts the index and dispatches into Go,
// handing through the cairo_t. Mirrors the sngl_connect/snglGoDispatch
// signal pattern: the static helpers are defined here so they are visible
// to the C.sngl_drawing_area_set_draw call sites this file emits (cgo
// preambles are per-file), while sngl_draw_dispatch is //export-ed once in
// callbacks.go and forward-declared extern here.
extern void sngl_draw_dispatch(int idx, cairo_t* cr, int width, int height);
static void sngl_draw_tramp(GtkDrawingArea* area, cairo_t* cr, int width, int height, gpointer data) {
    (void)area;
    sngl_draw_dispatch(GPOINTER_TO_INT(data), cr, width, height);
}
static void sngl_drawing_area_set_draw(void* area, int idx) {
    gtk_drawing_area_set_draw_func(GTK_DRAWING_AREA(area), sngl_draw_tramp, GINT_TO_POINTER(idx), NULL);
}
*/
import "C"

import (
	"git.duckfam.us/jonathan/sngl/pkg/go/snglcolor"
	"unsafe"
)

type CanvasStyle struct {
	Fill        snglcolor.Color
	Stroke      snglcolor.Color
	StrokeWidth float64
	LineCap     string
	LineJoin    string
	FontSize    float64
	FontFamily  string
}

type PathCmd struct {
	Op  string
	X   float64
	Y   float64
	Cx1 float64
	Cy1 float64
	Cx2 float64
	Cy2 float64
	R   float64
}

// _snglCairoScale maps a drawing's own coordinate space onto the size GTK is
// drawing at. An empty mode leaves the context alone, which is what a canvas
// shown at its own size wants.
func _snglCairoScale(cr *C.cairo_t, pw, ph, w, h int, mode string) {
	if w <= 0 || h <= 0 || mode == "" {
		return
	}
	sx, sy := float64(pw)/float64(w), float64(ph)/float64(h)
	switch mode {
	case "stretch":
	case "fill":
		if sy > sx {
			sx = sy
		}
		sy = sx
	default:
		if sy < sx {
			sx = sy
		}
		sy = sx
	}
	C.cairo_scale(cr, C.double(sx), C.double(sy))
}

func _snglCairoSource(cr *C.cairo_t, c snglcolor.Color) {
	C.cairo_set_source_rgba(cr, C.double(float64(c.R)/255.0), C.double(float64(c.G)/255.0), C.double(float64(c.B)/255.0), C.double(float64(c.A)/255.0))
}

// _snglCairoPaint fills (when fill.a>0) and strokes (when stroke.a>0) the
// current path. cairo_fill_preserve keeps the path so a following stroke
// applies to the same geometry.
func _snglCairoPaint(cr *C.cairo_t, s CanvasStyle) {
	if s.Fill.A > 0 {
		_snglCairoSource(cr, s.Fill)
		if s.Stroke.A > 0 {
			C.cairo_fill_preserve(cr)
		} else {
			C.cairo_fill(cr)
		}
	}
	if s.Stroke.A > 0 {
		C.cairo_set_line_width(cr, C.double(s.StrokeWidth))
		_snglCairoSource(cr, s.Stroke)
		C.cairo_stroke(cr)
	}
}

// _snglCairoStroke strokes the current path (line primitives have no fill).
func _snglCairoStroke(cr *C.cairo_t, s CanvasStyle) {
	if s.Stroke.A > 0 {
		C.cairo_set_line_width(cr, C.double(s.StrokeWidth))
		_snglCairoSource(cr, s.Stroke)
	}
	C.cairo_stroke(cr)
}

type Measurement struct {
	Px  float64
	Em  float64
	Vw  float64
	Vh  float64
	Pct float64
}

// Model holds the state and widget references for this SNGL UI.
type Model struct {
	__n0   *C.GtkDrawingArea
	__root *C.GtkBox
}

// New creates a Model with default values. Binds initialize
// sequentially so later inits can reference earlier `m.<name>` fields.
func New() *Model {
	m := &Model{}
	return m
}

func (m *Model) _canvasDraw0(ctx *C.cairo_t) {
	C.cairo_save(ctx)
	_style1 := CanvasStyle{Fill: snglcolor.Color{R: 99, G: 102, B: 241, A: 255}, Stroke: snglcolor.Color{A: 0, R: 0, G: 0, B: 0}, StrokeWidth: 1, LineCap: "butt", LineJoin: "miter", FontSize: 16, FontFamily: "sans-serif"}
	C.cairo_new_sub_path(ctx)
	C.cairo_arc(ctx, C.double(200), C.double(140), C.double(radius), 0, 6.283185307179586)
	_snglCairoPaint(ctx, _style1)
	C.cairo_restore(ctx)
}

func (m *Model) buildWidgetTree() {
	if m.__root != nil {
		return
	}
	m.__root = (*C.GtkBox)(unsafe.Pointer(C.gtk_box_new(C.GTK_ORIENTATION_VERTICAL, 6)))
	m.__n0 = (*C.GtkDrawingArea)(unsafe.Pointer(C.gtk_drawing_area_new()))
	C.gtk_drawing_area_set_content_width(m.__n0, C.int(400))
	C.gtk_drawing_area_set_content_height(m.__n0, C.int(280))
	snglDrawFuncs = append(snglDrawFuncs, func(cr *C.cairo_t, pw, ph int) { _snglCairoScale(cr, pw, ph, 400, 280, ""); m._canvasDraw0(cr) })
	C.sngl_drawing_area_set_draw(unsafe.Pointer(m.__n0), C.int((len(snglDrawFuncs) - 1)))
	C.gtk_box_append((*C.GtkBox)(unsafe.Pointer(m.__root)), (*C.GtkWidget)(unsafe.Pointer(m.__n0)))
}

// BuildUI constructs the widget tree and returns the top-level window.
func (m *Model) BuildUI(app *C.GtkApplication) *C.GtkWidget {
	m.buildWidgetTree()
	win := C.gtk_application_window_new(app)
	C.gtk_window_set_default_size((*C.GtkWindow)(unsafe.Pointer(win)), 480, 640)
	C.gtk_window_set_title((*C.GtkWindow)(unsafe.Pointer(win)), C.CString("c"))
	C.gtk_window_set_child((*C.GtkWindow)(unsafe.Pointer(win)), (*C.GtkWidget)(unsafe.Pointer(m.__root)))
	return win
}
