// Code generated by sngl (fyne) from t.sngl; DO NOT EDIT.

package ui

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	snglcanvas "git.duckfam.us/jonathan/sngl/pkg/go/canvas"
	"git.duckfam.us/jonathan/sngl/pkg/go/snglcolor"
)

type CanvasStyle struct {
	Fill        snglcolor.Color
	Stroke      snglcolor.Color
	StrokeWidth float64
	LineCap     string
	LineJoin    string
	FontSize    float64
	FontFamily  string
}

type PathCmd struct {
	Op  string
	X   float64
	Y   float64
	Cx1 float64
	Cy1 float64
	Cx2 float64
	Cy2 float64
	R   float64
}

// Model holds the state for this SNGL UI.
type Model struct {
	radius float64

	__n0    *canvas.Image
	__n0Ctx *snglcanvas.Context
	__n1    *widget.Button
}

// New creates a Model with default values.
func New() *Model {
	m := &Model{}
	m.radius = 50.0
	return m
}

func (m *Model) _canvasDraw0(ctx *snglcanvas.Context) {
	ctx.Save()
	_cstyle1 := CanvasStyle{Fill: snglcolor.Color{R: 10, G: 20, B: 30, A: 255}}
	ctx.SetFill(_cstyle1.Fill.R, _cstyle1.Fill.G, _cstyle1.Fill.B, _cstyle1.Fill.A)
	ctx.SetStroke(_cstyle1.Stroke.R, _cstyle1.Stroke.G, _cstyle1.Stroke.B, _cstyle1.Stroke.A)
	ctx.SetStrokeWidth(_cstyle1.StrokeWidth)
	ctx.SetFont(_cstyle1.FontSize, _cstyle1.FontFamily)
	ctx.SetLineStyle(_cstyle1.LineCap, _cstyle1.LineJoin)
	ctx.Rect(0.0, 0.0, 400.0, 280.0)
	ctx.Restore()
	ctx.Save()
	_cstyle2 := CanvasStyle{Fill: snglcolor.Color{R: 99, G: 102, B: 241, A: 255}, Stroke: snglcolor.Color{R: 67, G: 56, B: 202, A: 255}, StrokeWidth: 3.0}
	ctx.SetFill(_cstyle2.Fill.R, _cstyle2.Fill.G, _cstyle2.Fill.B, _cstyle2.Fill.A)
	ctx.SetStroke(_cstyle2.Stroke.R, _cstyle2.Stroke.G, _cstyle2.Stroke.B, _cstyle2.Stroke.A)
	ctx.SetStrokeWidth(_cstyle2.StrokeWidth)
	ctx.SetFont(_cstyle2.FontSize, _cstyle2.FontFamily)
	ctx.SetLineStyle(_cstyle2.LineCap, _cstyle2.LineJoin)
	ctx.Circle(200.0, 140.0, m.radius)
	ctx.Restore()
}

func (m *Model) __n1_click_handler() {
	m.radius = (m.radius + 10.0)
	m.__n0Ctx = snglcanvas.New(400, 280)
	m._canvasDraw0(m.__n0Ctx)
	m.__n0.Image = m.__n0Ctx.Result()
	m.__n0.Refresh()
}

func (m *Model) Radius() float64 {
	return m.radius
}

func (m *Model) SetRadius(v float64) {
	m.radius = v
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	m.__n0Ctx = snglcanvas.New(400, 280)
	m._canvasDraw0(m.__n0Ctx)
	m.__n0 = canvas.NewImageFromImage(m.__n0Ctx.Result())
	m.__n0.FillMode = canvas.ImageFillOriginal
	m.__n1 = widget.NewButton("", nil)
	m.__n1.SetText(fmt.Sprint("Grow"))
	m.__n1.OnTapped = m.__n1_click_handler
	var parts []fyne.CanvasObject
	parts = append(parts, m.__n0)
	parts = append(parts, m.__n1)
	return container.NewVBox(parts...)
}
