// Code generated by "stringer -type=AssignOp -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssignSet-0]
	_ = x[AssignAdd-1]
	_ = x[AssignSub-2]
	_ = x[AssignMul-3]
	_ = x[AssignDiv-4]
	_ = x[AssignMod-5]
}

const _AssignOp_name = "=+=-=*=/=%="

var _AssignOp_index = [...]uint8{0, 1, 3, 5, 7, 9, 11}

func (i AssignOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AssignOp_index)-1 {
		return "AssignOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssignOp_name[_AssignOp_index[idx]:_AssignOp_index[idx+1]]
}
