// Code generated by "stringer -type=BinaryOp -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinAdd-0]
	_ = x[BinSub-1]
	_ = x[BinMul-2]
	_ = x[BinDiv-3]
	_ = x[BinMod-4]
	_ = x[BinEq-5]
	_ = x[BinNeq-6]
	_ = x[BinLt-7]
	_ = x[BinLte-8]
	_ = x[BinGt-9]
	_ = x[BinGte-10]
	_ = x[BinAnd-11]
	_ = x[BinOr-12]
}

const _BinaryOp_name = "+-*/%==!=<<=>>=&&||"

var _BinaryOp_index = [...]uint8{0, 1, 2, 3, 4, 5, 7, 9, 10, 12, 13, 15, 17, 19}

func (i BinaryOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BinaryOp_index)-1 {
		return "BinaryOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOp_name[_BinaryOp_index[idx]:_BinaryOp_index[idx+1]]
}
