// Code generated by "stringer -type=LiteralKind -trimprefix Literal"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LiteralInt-0]
	_ = x[LiteralFloat-1]
	_ = x[LiteralStringQuoted-2]
	_ = x[LiteralStringBackticked-3]
	_ = x[LiteralStringTrippleQuoted-4]
	_ = x[LiteralBool-5]
	_ = x[LiteralNull-6]
	_ = x[LiteralColor-7]
	_ = x[LiteralUnit-8]
}

const _LiteralKind_name = "IntFloatStringQuotedStringBacktickedStringTrippleQuotedBoolNullColorUnit"

var _LiteralKind_index = [...]uint8{0, 3, 8, 20, 36, 55, 59, 63, 68, 72}

func (i LiteralKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LiteralKind_index)-1 {
		return "LiteralKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LiteralKind_name[_LiteralKind_index[idx]:_LiteralKind_index[idx+1]]
}
