// Code generated by "stringer -type=SelectKind -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SelectField-0]
	_ = x[SelectEvent-1]
	_ = x[SelectElemRef-2]
}

const _SelectKind_name = "field@event#ref"

var _SelectKind_index = [...]uint8{0, 5, 11, 15}

func (i SelectKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SelectKind_index)-1 {
		return "SelectKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SelectKind_name[_SelectKind_index[idx]:_SelectKind_index[idx+1]]
}
