// Code generated by "stringer -type=StringStyle -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleDouble-0]
	_ = x[StyleTriple-1]
	_ = x[StyleRaw-2]
}

const _StringStyle_name = "\"...\"\"\"\"...\"\"\"`...`"

var _StringStyle_index = [...]uint8{0, 5, 14, 19}

func (i StringStyle) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StringStyle_index)-1 {
		return "StringStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StringStyle_name[_StringStyle_index[idx]:_StringStyle_index[idx+1]]
}
