// Code generated by "stringer -type=UnaryOp -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnaryNot-0]
	_ = x[UnaryNeg-1]
	_ = x[UnaryAddr-2]
	_ = x[UnaryDeref-3]
}

const _UnaryOp_name = "!-&*"

var _UnaryOp_index = [...]uint8{0, 1, 2, 3, 4}

func (i UnaryOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UnaryOp_index)-1 {
		return "UnaryOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnaryOp_name[_UnaryOp_index[idx]:_UnaryOp_index[idx+1]]
}
