package playground

import (
	"strings"
	"testing"
)

const minifySource = `output {
    none {
        html(minify=true)
    }
}

component main {
    var name = "World"

    vbox(style={gap=12, padding=16}) {
        text(value="Hello, {name}!", style={fontSize=24, fontWeight=bold})
    }
}
`

func TestGenerateRespectsMinify(t *testing.T) {
	out := Generate(minifySource, "html", "none")
	if !strings.Contains(out, `"files":`) {
		t.Fatalf("expected files in output, got: %s", out)
	}
	// Minified HTML has no `\n  <meta` indented line.
	if strings.Contains(out, `\n  <meta`) || strings.Contains(out, "\n  <meta") {
		t.Errorf("expected minified output, but found indented <meta>: %s", out)
	}
	// Minified HTML drops the SNGL header comment.
	if strings.Contains(out, "Code generated by sngl") {
		t.Errorf("expected SNGL header comment to be stripped under minify=true: %s", out)
	}
}

func TestCompileRespectsMinify(t *testing.T) {
	out := Compile(minifySource)
	if strings.Contains(out, "Code generated by sngl") {
		t.Errorf("expected SNGL header comment to be stripped under minify=true (Compile): %s", out)
	}
}
