package kotlin

import (
	"bytes"
	"fmt"
	"io"

	"duckfam.us/sngl/codegen"
	"duckfam.us/sngl/ir"
)

// fileEmitter implements codegen.FileEmitter for Kotlin output.
//
// Kotlin has no gofmt-equivalent in the build path, so the emitter is a
// thin wrapper: prepend the generated-by header, then write the body
// bytes verbatim. Import tracking is not yet wired (Kotlin's translator
// doesn't currently call RequireImport at emit sites). Source-map
// support remains deferred per Plan A non-goal.
type fileEmitter struct {
	sink   codegen.Sink
	opts   codegen.FileOptions
	buf    bytes.Buffer
	closed bool
}

func newFileEmitter(sink codegen.Sink, opts codegen.FileOptions) *fileEmitter {
	return &fileEmitter{sink: sink, opts: opts}
}

func (fe *fileEmitter) Write(p []byte) (int, error) {
	if fe.closed {
		return 0, io.ErrClosedPipe
	}
	return fe.buf.Write(p)
}

// EvalExpr / EvalStmt are placeholders until the Kotlin path is rewritten
// to emit through this surface. Today's android-kotlin path writes the
// entire Kotlin body through Write as a pre-rendered byte slice.
func (fe *fileEmitter) EvalExpr(e ir.Expr) string   { return "" }
func (fe *fileEmitter) EvalStmt(s ir.Stmt) []string { return nil }

func (fe *fileEmitter) RequireImport(path string) string { return path }

func (fe *fileEmitter) Close() error {
	if fe.closed {
		return nil
	}
	fe.closed = true

	var assembled bytes.Buffer
	if fe.opts.Source != "" && fe.opts.Platform != "" {
		fmt.Fprintf(&assembled, "// Code generated by sngl (%s) from %s; DO NOT EDIT.\n\n",
			fe.opts.Platform, fe.opts.Source)
	}
	if fe.opts.PackageName != "" {
		fmt.Fprintf(&assembled, "package %s\n\n", fe.opts.PackageName)
	}
	assembled.Write(fe.buf.Bytes())

	w, err := fe.sink.Create(fe.opts.Name)
	if err != nil {
		return err
	}
	if _, err := w.Write(assembled.Bytes()); err != nil {
		w.Close()
		return err
	}
	return w.Close()
}
