package javascript

import (
	"bytes"
	"fmt"
	"io"

	"git.duckfam.us/jonathan/sngl/codegen"
	"git.duckfam.us/jonathan/sngl/ir"
)

// fileEmitter implements codegen.FileEmitter for JS output.
//
// The html platform doesn't currently use this emitter — it embeds JS
// inline inside `<script>` tags in the HTML body. This emitter exists
// for future split-JS-file scenarios (route mode emitting a separate
// .js bundle, future static-site multi-file modes, etc.) and to make
// the LangTranslator interface uniform across languages.
//
// Behavior:
//   - Write appends raw bytes to the body buffer.
//   - EvalExpr / EvalStmt delegate to a private JsIRContext when one is
//     bound via Context().
//   - Close prepends the generated-by comment and emits a sourcemap
//     data URL via the existing inline-marker pipeline when Maps is on.
type fileEmitter struct {
	sink   codegen.Sink
	opts   codegen.FileOptions
	buf    bytes.Buffer
	jc     *JsIRContext
	closed bool
}

func newFileEmitter(sink codegen.Sink, opts codegen.FileOptions) *fileEmitter {
	jc := &JsIRContext{EmitPositionMarkers: opts.Maps}
	return &fileEmitter{sink: sink, opts: opts, jc: jc}
}

// Context returns the embedded JsIRContext so platforms can bind it to
// their ExprCtx before calling EvalExpr/EvalStmt.
func (fe *fileEmitter) Context() *JsIRContext { return fe.jc }

func (fe *fileEmitter) Write(p []byte) (int, error) {
	if fe.closed {
		return 0, io.ErrClosedPipe
	}
	return fe.buf.Write(p)
}

func (fe *fileEmitter) EvalExpr(e ir.Expr) string {
	if fe.jc == nil || fe.jc.Ctx == nil {
		return ""
	}
	return fe.jc.EvalExpr(e)
}

func (fe *fileEmitter) EvalStmt(s ir.Stmt) []string {
	if fe.jc == nil || fe.jc.Ctx == nil {
		return nil
	}
	return fe.jc.EvalStmt(s)
}

// RequireImport: JS imports are ES module specifiers rather than Go-
// style package paths; resolving an alias requires knowing the call
// site (default vs named import). Today's html platform threads native
// imports through ExprScope.NativeImports rather than this method.
// Returns the path unchanged as a placeholder; callers expecting a
// real alias should populate NativeImports directly.
func (fe *fileEmitter) RequireImport(path string) string { return path }

func (fe *fileEmitter) Close() error {
	if fe.closed {
		return nil
	}
	fe.closed = true

	var assembled bytes.Buffer
	if fe.opts.Source != "" && fe.opts.Platform != "" {
		fmt.Fprintf(&assembled, "// Code generated by sngl (%s) from %s; DO NOT EDIT.\n\n",
			fe.opts.Platform, fe.opts.Source)
	}
	body := fe.buf.Bytes()
	if fe.opts.Maps {
		// Extract inline /*@SNGL:file:line@*/ markers into a v3 source
		// map sidecar, strip from body, and append a sourceMappingURL
		// footer that references the sidecar by name.
		res := renderJSSourceMap(fe.opts.Name, nil, body)
		if res.InlineBody != nil {
			body = res.InlineBody
		}
		if res.Sidecar != nil && res.SidecarName != "" {
			sw, err := fe.sink.Create(res.SidecarName)
			if err != nil {
				return err
			}
			if _, err := sw.Write(res.Sidecar); err != nil {
				sw.Close()
				return err
			}
			if err := sw.Close(); err != nil {
				return err
			}
		}
	}
	assembled.Write(body)

	w, err := fe.sink.Create(fe.opts.Name)
	if err != nil {
		return err
	}
	if _, err := w.Write(assembled.Bytes()); err != nil {
		w.Close()
		return err
	}
	return w.Close()
}
