package javascript

import (
	"fmt"
	"strings"

	"git.duckfam.us/jonathan/sngl/ast"

	"git.duckfam.us/jonathan/sngl/codegen"
	"git.duckfam.us/jonathan/sngl/ir"
)

// TestEmitMode selects how LowerTestFile wraps per-test bodies.
type TestEmitMode int

const (
	// TestEmitAgent produces async function declarations taking a T
	// parameter plus a Registry.register call per test. Used by
	// `sngl test --platform=html`.
	TestEmitAgent TestEmitMode = iota
	// TestEmitNative is reserved for symmetry with go/kotlin lowerers.
	// For html, native-mode emission is currently a no-op
	// (`sngl test --platform=html` is the supported path). Returns a
	// doc comment.
	TestEmitNative
)

// testInstanceVar names the component a test drives. Deliberately not a name
// SNGL source can produce, so a local in the test body never collides.
const testInstanceVar = "__snglTestComponent"

// LowerTestFile produces the entire source of a generated JS test file.
//
// Agent mode emits:
//
//	import { Registry } from './testagent/testagent.js';
//
//	export async function testFoo(t) {
//	    const c = newTestComponent();
//	    setCurrentTestModel(c);
//	    ... lowered body lines ...
//	}
//
//	Registry.register('Foo', testFoo);
//
// The caller is responsible for emitting `newTestComponent` and
// `setCurrentTestModel` in the same module (mirrors the helper
// expectation in the Go and Kotlin testlowers).
//
// `pkg` is accepted for symmetry with the Go/Kotlin LowerTestFile
// signatures but is unused in JS — ES modules have no package
// declaration.
func LowerTestFile(pkg string, irPkg *ir.Package, fns []*ir.Func, suffixes []string,
	methodFields map[string]bool, mode TestEmitMode) string {

	if mode == TestEmitNative {
		return "// native-mode html test emission is not supported.\n" +
			"// Use `sngl test --platform=html` instead.\n"
	}

	_ = pkg

	var b strings.Builder
	b.WriteString("// Generated by SNGL — do not edit.\n")
	b.WriteString("import { Registry } from './testagent/testagent.js';\n")
	b.WriteString("import { newTestComponent, setCurrentTestModel } from './current_model.js';\n\n")

	for i, fn := range fns {
		suffix := suffixes[i]
		fmt.Fprintf(&b, "export async function test%s(t) {\n", suffix)
		// Always built -- a snapshot needs an instance whether the test named
		// one or not -- but bound to the declared name only when there is
		// one. A fixed `const c` in every test redeclared any local called
		// `c`, and a module that does not parse is a page that never loads.
		b.WriteString("\tconst " + testInstanceVar + " = newTestComponent();\n")
		b.WriteString("\tsetCurrentTestModel(" + testInstanceVar + ");\n")
		if recv := codegen.TestComponentParam(fn); recv != "" {
			fmt.Fprintf(&b, "\tconst %s = %s;\n", recv, testInstanceVar)
		}
		for _, line := range lowerTestBody(irPkg, fn, methodFields) {
			fmt.Fprintf(&b, "\t%s\n", line)
		}
		b.WriteString("}\n\n")
	}

	for i := range fns {
		suffix := suffixes[i]
		fmt.Fprintf(&b, "Registry.register('%s', test%s);\n", suffix, suffix)
	}

	return b.String()
}

// lowerTestBody returns the lowered JS source lines for a test body,
// reusing the existing JS IR translator (same path non-test code
// takes). methodFields is currently unused on the JS side — agent-mode
// tests address widgets via DOM tags, not via the model field gate
// the Kotlin/Go lowerers consult — but accepted in the signature for
// symmetry and future use.
func lowerTestBody(irPkg *ir.Package, fn *ir.Func, methodFields map[string]bool) []string {
	// The test module is bundled with the emitted program, so it has to name
	// things the way the emitter named them: a method on a user type as the
	// free `Calc_digit(…)`. Over an empty package it knew none of them and
	// emitted `Calc{…}.digit(…)`, a method no plain object has.
	if irPkg == nil {
		irPkg = &ir.Package{}
	}
	ctx := codegen.NewExprCtx(irPkg)
	// Computeds are emitted as zero-arg methods; the test body must call
	// `c.<computed>()` rather than read the function object.
	ctx.MethodFields = methodFields
	ctx.StateReceiver = testInstanceVar
	for _, p := range fn.Params {
		ctx = ctx.WithLocal(p.Name)
	}
	jc := NewIRContext(ctx)

	var out []string
	for _, s := range fn.Block {
		if line, ok := lowerTestAssert(s, jc); ok {
			out = append(out, line)
			continue
		}
		if line, ok := lowerTestSnapshot(s, jc); ok {
			out = append(out, line)
			continue
		}
		if line, ok := lowerEventTrigger(s, jc); ok {
			out = append(out, line)
			continue
		}
		if name, ok := testSetContext(s); ok {
			// passContext already passed the value to every call after it.
			out = append(out, fmt.Sprintf("// t.setContext(%s, ...)", name))
			continue
		}
		out = append(out, jc.EvalStmt(s)...)
	}
	return out
}

func testSetContext(s ir.Stmt) (string, bool) {
	cs, ok := s.(*ir.CallStmt)
	if !ok {
		return "", false
	}
	name, _, ok := codegen.TestSetContext(cs.Call)
	return name, ok
}

// lowerTestAssert intercepts `t.assert(expr)` call statements and routes
// them through the agent T's assertTrue(b, msg) so failures land in the
// JSON-RPC test report. Mirrors lowerTestAssert in the Go/Kotlin
// testlowers.
func lowerTestAssert(s ir.Stmt, jc *JsIRContext) (string, bool) {
	cs, ok := s.(*ir.CallStmt)
	if !ok || cs.Call == nil || cs.Call.Func == nil {
		return "", false
	}
	if cs.Call.Func.Receiver != "Test" || cs.Call.Func.Name != "assert" {
		return "", false
	}
	if len(cs.Call.Args) != 2 {
		return "", false
	}
	expr := jc.EvalExpr(cs.Call.Args[1].Value)
	return fmt.Sprintf("t.assertTrue(%s, %q)", expr, expr), true
}

// lowerTestSnapshot intercepts `t.snapshot(name)` call statements and
// emits them with `await` so the async snapshotAssert round-trip
// completes before the test body returns. Without the await, the
// agent dispatcher fires testEnd before the driver sees the
// snapshotAssert request — test passes trivially, golden is never
// written.
func lowerTestSnapshot(s ir.Stmt, jc *JsIRContext) (string, bool) {
	cs, ok := s.(*ir.CallStmt)
	if !ok || cs.Call == nil || cs.Call.Func == nil {
		return "", false
	}
	if cs.Call.Func.Receiver != "Test" || cs.Call.Func.Name != "snapshot" {
		return "", false
	}
	if len(cs.Call.Args) != 2 {
		return "", false
	}
	name := jc.EvalExpr(cs.Call.Args[1].Value)
	return fmt.Sprintf("await t.snapshot(%s)", name), true
}

// lowerEventTrigger matches the IR shape a test line like `c.inc.click()`
// produces -- a CallStmt the checker tagged with an Event, whose callee is a
// chain of SelectExprs ending in the event field -- and emits
// `<recv>.<id><Event>(...)`.
//
// Without it the event was dropped and the call rendered as `c.inc()`, which
// resolves to nothing: the assertion then failed on an unchanged value rather
// than erroring, which is the worst way for this to be missing.
//
// The invoker it names is attached to the state object by the html platform,
// where the element behind `#inc` is known. Both halves capitalise the event
// the same way, which is the only thing making them meet.
func lowerEventTrigger(s ir.Stmt, jc *JsIRContext) (string, bool) {
	call, ok := s.(*ir.CallStmt)
	if !ok || call.Call == nil {
		return "", false
	}
	c := call.Call
	if c.AST == nil || c.Event == "" {
		return "", false
	}
	outerSel, ok := c.AST.Func.(*ast.SelectExpr)
	if !ok {
		return "", false
	}
	// outerSel.Operand is `c.inc` -- another SelectExpr Operand:Ident{c}, Field:"inc".
	innerSel, ok := outerSel.Operand.(*ast.SelectExpr)
	if !ok {
		return "", false
	}
	recv, ok := innerSel.Operand.(*ast.IdentExpr)
	if !ok {
		return "", false
	}
	args := make([]string, len(c.Args))
	for i, a := range c.Args {
		args[i] = jc.EvalExpr(a.Value)
	}
	return fmt.Sprintf("%s.%s%s(%s);", recv.Name, innerSel.Field, exportEventName(c.Event), strings.Join(args, ", ")), true
}

// exportEventName upper-cases the first letter, matching the name the platform
// gives the invoker it attaches.
func exportEventName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
