package javascript

import (
	"fmt"
	"strings"

	"git.duckfam.us/jonathan/sngl/codegen"
	"git.duckfam.us/jonathan/sngl/ir"
)

// TestEmitMode selects how LowerTestFile wraps per-test bodies.
type TestEmitMode int

const (
	// TestEmitAgent produces async function declarations taking a T
	// parameter plus a Registry.register call per test. Used by
	// `sngl test --platform=html`.
	TestEmitAgent TestEmitMode = iota
	// TestEmitNative is reserved for symmetry with go/kotlin lowerers.
	// For html, native-mode emission is currently a no-op
	// (`sngl test --platform=html` is the supported path). Returns a
	// doc comment.
	TestEmitNative
)

// LowerTestFile produces the entire source of a generated JS test file.
//
// Agent mode emits:
//
//	import { Registry } from './testagent/testagent.js';
//
//	export async function testFoo(t) {
//	    const c = newTestComponent();
//	    setCurrentTestModel(c);
//	    ... lowered body lines ...
//	}
//
//	Registry.register('Foo', testFoo);
//
// The caller is responsible for emitting `newTestComponent` and
// `setCurrentTestModel` in the same module (mirrors the helper
// expectation in the Go and Kotlin testlowers).
//
// `pkg` is accepted for symmetry with the Go/Kotlin LowerTestFile
// signatures but is unused in JS — ES modules have no package
// declaration.
func LowerTestFile(pkg string, fns []*ir.Func, suffixes []string,
	methodFields map[string]bool, mode TestEmitMode) string {

	if mode == TestEmitNative {
		return "// native-mode html test emission is not supported.\n" +
			"// Use `sngl test --platform=html` instead.\n"
	}

	_ = pkg

	var b strings.Builder
	b.WriteString("// Generated by SNGL — do not edit.\n")
	b.WriteString("import { Registry } from './testagent/testagent.js';\n")
	b.WriteString("import { newTestComponent, setCurrentTestModel } from './current_model.js';\n\n")

	for i, fn := range fns {
		suffix := suffixes[i]
		fmt.Fprintf(&b, "export async function test%s(t) {\n", suffix)
		b.WriteString("\tconst c = newTestComponent();\n")
		b.WriteString("\tsetCurrentTestModel(c);\n")
		for _, line := range lowerTestBody(fn, methodFields) {
			fmt.Fprintf(&b, "\t%s\n", line)
		}
		b.WriteString("}\n\n")
	}

	for i := range fns {
		suffix := suffixes[i]
		fmt.Fprintf(&b, "Registry.register('%s', test%s);\n", suffix, suffix)
	}

	return b.String()
}

// lowerTestBody returns the lowered JS source lines for a test body,
// reusing the existing JS IR translator (same path non-test code
// takes). methodFields is currently unused on the JS side — agent-mode
// tests address widgets via DOM tags, not via the model field gate
// the Kotlin/Go lowerers consult — but accepted in the signature for
// symmetry and future use.
func lowerTestBody(fn *ir.Func, methodFields map[string]bool) []string {
	_ = methodFields

	// Build an ExprCtx scoped to a minimal package; tests live in their
	// own emitted module and reference per-component helpers
	// (newTestComponent, setCurrentTestModel) declared in the same
	// file rather than reading package state directly.
	ctx := codegen.NewExprCtx(&ir.Package{})
	for _, p := range fn.Params {
		ctx = ctx.WithLocal(p.Name)
	}
	jc := NewIRContext(ctx)

	var out []string
	for _, s := range fn.Block {
		if line, ok := lowerTestAssert(s, jc); ok {
			out = append(out, line)
			continue
		}
		if line, ok := lowerTestSnapshot(s, jc); ok {
			out = append(out, line)
			continue
		}
		out = append(out, jc.EvalStmt(s)...)
	}
	return out
}

// lowerTestAssert intercepts `t.assert(expr)` call statements and routes
// them through the agent T's assertTrue(b, msg) so failures land in the
// JSON-RPC test report. Mirrors lowerTestAssert in the Go/Kotlin
// testlowers.
func lowerTestAssert(s ir.Stmt, jc *JsIRContext) (string, bool) {
	cs, ok := s.(*ir.CallStmt)
	if !ok || cs.Call == nil || cs.Call.Func == nil {
		return "", false
	}
	if cs.Call.Func.Receiver != "Test" || cs.Call.Func.Name != "assert" {
		return "", false
	}
	if len(cs.Call.Args) != 2 {
		return "", false
	}
	expr := jc.EvalExpr(cs.Call.Args[1].Value)
	return fmt.Sprintf("t.assertTrue(%s, %q)", expr, expr), true
}

// lowerTestSnapshot intercepts `t.snapshot(name)` call statements and
// emits them with `await` so the async snapshotAssert round-trip
// completes before the test body returns. Without the await, the
// agent dispatcher fires testEnd before the driver sees the
// snapshotAssert request — test passes trivially, golden is never
// written.
func lowerTestSnapshot(s ir.Stmt, jc *JsIRContext) (string, bool) {
	cs, ok := s.(*ir.CallStmt)
	if !ok || cs.Call == nil || cs.Call.Func == nil {
		return "", false
	}
	if cs.Call.Func.Receiver != "Test" || cs.Call.Func.Name != "snapshot" {
		return "", false
	}
	if len(cs.Call.Args) != 2 {
		return "", false
	}
	name := jc.EvalExpr(cs.Call.Args[1].Value)
	return fmt.Sprintf("await t.snapshot(%s)", name), true
}
