// consteval is the JavaScript runtime for SNGL's compile-time evaluation of
// pure js:// functions. The compiler generates a program that calls each
// pending function and hands the result to emit; this module encodes the value
// as SNGL source and writes the batch to the file named by SNGL_CONSTEVAL_OUT,
// which the compiler then parses.
//
// It is pkg/go/consteval said in JavaScript. Where the two differ, the
// difference is JavaScript's: see marshalSymbol for the hook that replaces
// implementing an interface, and encode for how each JS value kind that has no
// Go counterpart is spelled.

import { writeFile } from "node:fs/promises";

// outEnv names the environment variable flush writes to.
export const outEnv = "SNGL_CONSTEVAL_OUT";

// marshalSymbol lets a value choose its own SNGL form. A method under this key
// returns a SNGL *expression*, not a value: the compiler parses the string as
// source.
export const marshalSymbol = Symbol.for("sngl.marshal");

const values = new Map();
const failures = new Map();
const custom = new Map();

// register installs an encoder for a type the caller does not own, keyed by
// constructor. It is Go's generic Register: `reflect.Type` identifies a Go
// type, and a constructor is what identifies a JS one.
export function register(ctor, fn) {
  custom.set(ctor, fn);
}

globalThis.__SNGL_CONSTEVAL__ = { register, encode, emit, fail, flush };

// maxDepth bounds nesting. A value that points at itself has no SNGL form, and
// recursing into one overflows the stack — which, unlike a throw, the
// generated program's per-call catch cannot contain, so the whole round would
// lose its results file rather than this one key.
const maxDepth = 64;

// encode returns v as SNGL source, honoring marshalSymbol and any registered
// encoder. It throws for a value with no SNGL form; the caller turns that into
// this key's failure.
export function encode(v) {
  return encodeValue(v, 0);
}

// emit encodes v and records it under key. An encoding error is recorded as a
// failure, so one unrepresentable value costs only its own key.
export function emit(key, v) {
  let src;
  try {
    src = encode(v);
  } catch (err) {
    fail(key, err);
    return;
  }
  failures.delete(key);
  values.set(key, src);
}

// fail records that key could not be produced. flush omits the key entirely;
// the compiler reports it by absence.
export function fail(key, err) {
  values.delete(key);
  failures.set(key, reason(err));
}

// sep separates a key from its value in the results file. A key is a hash and
// an encoded string escapes a tab rather than writing one, so neither half can
// hold the separator.
const sep = "\t";

// flush writes every emitted value to the file named by SNGL_CONSTEVAL_OUT,
// one key-value record per line. Failures go to stderr: they are diagnostics
// for a human, while the compiler reads the absence of the record.
export async function flush() {
  const path = process.env[outEnv];
  if (!path) throw new Error(`consteval: ${outEnv} is not set`);

  let out = "// Code generated by pkg/js/consteval. DO NOT EDIT.\n\n";
  // Insertion order is specified for a Map, but the compiler hands keys over
  // in whatever order its rounds discovered them, so the file is sorted to
  // keep a rebuild byte-identical.
  for (const key of [...values.keys()].sort()) {
    out += `${key}${sep}${values.get(key)}\n`;
  }
  for (const key of [...failures.keys()].sort()) {
    process.stderr.write(`consteval: ${key}: ${failures.get(key)}\n`);
  }
  await writeFile(path, out, "utf8");
}

function reason(err) {
  if (err instanceof Error) return err.message || String(err);
  return String(err);
}

function encodeValue(v, depth) {
  if (depth > maxDepth) {
    throw new Error(`consteval: value nests deeper than ${maxDepth} levels`);
  }

  // undefined and null are one thing in SNGL. A JS function that returns
  // nothing returns undefined, and an absent property reads as undefined, so
  // both are the language's single absence rather than two.
  if (v === undefined || v === null) return "null";

  const marshalled = customEncode(v);
  if (marshalled !== undefined) return marshalled;

  switch (typeof v) {
    case "boolean":
      return v ? "true" : "false";
    case "number":
      return encodeNumber(v);
    case "bigint":
      return encodeBigInt(v);
    case "string":
      return quote(v);
    case "function":
      throw new Error("consteval: a function has no SNGL form");
    case "symbol":
      throw new Error("consteval: a symbol has no SNGL form");
  }

  if (Array.isArray(v)) return encodeList(v, depth);
  if (v instanceof Date) return encodeDate(v);
  if (v instanceof Map) return encodeMap(v, depth);
  // A Set is an ordered collection with no SNGL type of its own, so it crosses
  // as the list of its values. Uniqueness is not carried: SNGL has nothing to
  // carry it in, and dropping it silently beats failing a value the declared
  // type would have accepted as a list.
  if (v instanceof Set) return encodeList([...v], depth);
  if (ArrayBuffer.isView(v) || v instanceof ArrayBuffer) {
    throw new Error("consteval: a binary buffer has no SNGL form");
  }
  if (v instanceof RegExp) {
    throw new Error("consteval: a RegExp has no SNGL form");
  }
  if (typeof v.then === "function") {
    throw new Error("consteval: a promise has no SNGL form; the evaluator awaits the call, so return the value");
  }
  return encodeObject(v, depth);
}

// customEncode applies a marshalSymbol method or a registered encoder,
// returning undefined when neither applies. A marshalSymbol implementation
// wins over a registration; a registration wins over structural encoding —
// the same order Go uses.
function customEncode(v) {
  if (typeof v === "object" || typeof v === "function") {
    const m = v[marshalSymbol];
    if (typeof m === "function") return String(m.call(v));
  }
  const ctor = v.constructor;
  if (ctor !== undefined) {
    const fn = custom.get(ctor);
    if (fn !== undefined) return String(fn(v));
  }
  return undefined;
}

// encodeNumber writes a JS number as a SNGL float literal. Every JS number is
// a double and the js:// importer types `number` as float, so an integral
// value still gets a decimal point rather than crossing as an int.
function encodeNumber(v) {
  if (Number.isNaN(v)) throw new Error("consteval: NaN has no SNGL form");
  if (!Number.isFinite(v)) throw new Error(`consteval: ${v} has no SNGL form`);
  const src = plainDecimal(v);
  // A formatting bug must cost this key, not compile a wrong number.
  if (!Object.is(Number(src), v)) {
    throw new Error(`consteval: ${v} does not survive being written as ${src}`);
  }
  return src;
}

// plainDecimal renders v without an exponent. SNGL has no exponent syntax —
// `1e30` lexes as a unit literal — so the shortest round-tripping decimal JS
// gives us has to have its point moved by hand. Moving a point relocates
// digits without changing them, so the result is still exact.
function plainDecimal(v) {
  let s = String(v);
  if (Object.is(v, -0)) s = "-0";
  const m = /^(-?)(\d+)(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/.exec(s);
  if (m === null) throw new Error(`consteval: cannot write ${s} as a SNGL number`);
  const [, sign, intPart, fracPart = "", expPart] = m;
  let digits = intPart + fracPart;
  let point = intPart.length + (expPart ? Number(expPart) : 0);
  if (point <= 0) {
    digits = "0".repeat(1 - point) + digits;
    point += 1 - point;
  }
  if (point >= digits.length) {
    digits += "0".repeat(point - digits.length + 1);
  }
  return `${sign}${digits.slice(0, point)}.${digits.slice(point)}`;
}

// int64Min and uint64Max bound what SNGL's widest integer types can hold. A
// BigInt outside them has no SNGL form; guessing at a truncation would compile
// a different number than the function returned.
const int64Min = -(2n ** 63n);
const uint64Max = 2n ** 64n - 1n;

function encodeBigInt(v) {
  if (v < int64Min || v > uint64Max) {
    throw new Error(`consteval: ${v}n is outside the range of a SNGL integer`);
  }
  return v.toString();
}

// encodeDate mirrors the Go runtime's time.Time encoder: SNGL models a
// datetime as a string-domain type, so it crosses as a quoted timestamp.
function encodeDate(v) {
  const ms = v.getTime();
  if (Number.isNaN(ms)) throw new Error("consteval: an invalid Date has no SNGL form");
  return quote(v.toISOString());
}

function encodeList(v, depth) {
  const parts = [];
  for (const el of v) parts.push(encodeValue(el, depth + 1));
  return `[${parts.join(", ")}]`;
}

// encodeMap writes a Map as a SNGL map literal. The keys are quoted so that
// `{a = 1}` stays available to mean a struct — the same split the Go runtime
// makes between a Go map and a Go struct, and the reason a Map and a plain
// object are not encoded the same way here.
//
// Insertion order is preserved rather than sorted: a JS Map is ordered, so
// unlike a Go map there is nothing indeterminate to normalize away.
function encodeMap(v, depth) {
  const parts = [];
  for (const [k, val] of v) {
    const key = typeof k === "string" ? quote(k) : encodeValue(k, depth + 1);
    parts.push(`${key} = ${encodeValue(val, depth + 1)}`);
  }
  return `{${parts.join(", ")}}`;
}

// encodeObject writes a plain object or class instance as a SNGL struct
// literal. A class instance names its constructor; a plain object is
// anonymous, because `Object` is not a type the importer ever declared and the
// expected type is what says what shape the value must have.
//
// Unlike the Go runtime it writes a bare name, never the
// `import("scheme://path").Name` a checker could resolve. The js:// importer
// keys a declaration by module and name, and JavaScript reifies no module
// identity: a value carries no link to the module declaring its type, and a
// TypeScript interface has no runtime constructor at all.
function encodeObject(v, depth) {
  // A boxed primitive is an object whose own enumerable properties are none,
  // so it would otherwise encode as `Number{}`.
  if (v instanceof Boolean || v instanceof Number || v instanceof String) {
    return encodeValue(v.valueOf(), depth);
  }
  const ctor = v.constructor;
  let name = "";
  if (ctor !== undefined && ctor !== Object && typeof ctor.name === "string") {
    name = ctor.name;
  }
  const parts = [];
  for (const [k, val] of Object.entries(v)) {
    if (!isIdent(k)) {
      throw new Error(`consteval: property ${JSON.stringify(k)} is not a SNGL identifier; return a Map for keys that are not`);
    }
    parts.push(`${k} = ${encodeValue(val, depth + 1)}`);
  }
  return `${name}{${parts.join(", ")}}`;
}

function isIdent(s) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s);
}

// quote writes s as a SNGL string literal. Braces are escaped because an
// unescaped `{` opens an interpolation, and the lexer has no \u escape, so
// non-ASCII runes are written through as UTF-8.
function quote(s) {
  let out = '"';
  for (const ch of s) {
    switch (ch) {
      case '"':
        out += '\\"';
        continue;
      case "\\":
        out += "\\\\";
        continue;
      case "{":
        out += "\\{";
        continue;
      case "}":
        out += "\\}";
        continue;
      case "\n":
        out += "\\n";
        continue;
      case "\t":
        out += "\\t";
        continue;
      case "\r":
        out += "\\r";
        continue;
    }
    const code = ch.codePointAt(0);
    if (code < 0x20 || code === 0x7f) {
      out += "\\x" + code.toString(16).padStart(2, "0");
      continue;
    }
    // A lone surrogate is not a character. Writing the file as UTF-8 would
    // substitute U+FFFD for it, which is a different string than the function
    // returned, so the key fails instead.
    if (code >= 0xd800 && code <= 0xdfff) {
      throw new Error("consteval: string contains an unpaired surrogate and has no UTF-8 form");
    }
    out += ch;
  }
  return out + '"';
}
