// Code generated by sngl (fyne) from app.sngl; DO NOT EDIT.

package ui

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"go/ast"
)

var _ = fmt.Sprint
var _ fyne.CanvasObject
var _ = container.NewVBox
var _ = widget.NewLabel

func ternary[T any](cond bool, a, b T) T {
	if cond {
		return a
	}
	return b
}

// Model holds the state for this SNGL UI.
type Model struct {
	source     string
	file       ast.File
	parseError string
	parse      func(string)
	__root     *fyne.Container
	__slot0    []fyne.CanvasObject
	__slot1    []fyne.CanvasObject

	__n3 *fyne.Container
	__n5 *widget.Label
	__n6 *widget.Label
	__n0 *widget.Entry
	__n7 *widget.Button
	__n4 *fyne.Container
	__n1 *widget.Label
	__n2 *widget.Label
}

// New creates a Model with default values. Binds are initialized
// sequentially (not via a struct literal) so later init expressions can
// reference earlier fields via `m.<name>` — e.g. an interpolated
// `$"Hello, {nm}!"` reading `m.nm`.
func New() *Model {
	m := &Model{}
	m.source = "package main"
	m.file = File{}
	m.parseError = ""
	m.parse = func(_ string) any {
	}
	m.__root = container.NewVBox()
	m.__slot0 = nil
	m.__slot1 = nil
	return m
}

func (m *Model) __renderSlot0(container *fyne.Container) {
	for _, __entry := range m.__slot0 {
		container.Remove(__entry)
	}
	m.__slot0 = nil
	if m.parseError != "" {
		m.__n1 = widget.NewLabel("")
		m.__n1.SetText(fmt.Sprint(m.parseError))
		container.Add(m.__n1)
		m.__slot0 = append(m.__slot0, m.__n1)
	}
}

func (m *Model) __renderSlot1(container *fyne.Container) {
	for _, __entry := range m.__slot1 {
		container.Remove(__entry)
	}
	m.__slot1 = nil
	for _, decl := range m.file.Decls {
		m.__n2 = widget.NewLabel("")
		m.__n2.SetText(fmt.Sprint(decl))
		container.Add(m.__n2)
		m.__slot1 = append(m.__slot1, m.__n2)
	}
}

func (m *Model) __n0_input_handler(s string) {
	m.source = s
	m.__n0.SetText(fmt.Sprint(m.source))
}

func (m *Model) __n7_click_handler() {
	m.parse(m.source)
}

func (m *Model) Source() string {
	return m.source
}

func (m *Model) SetSource(v string) {
	m.source = v
}

func (m *Model) File() ast.File {
	return m.file
}

func (m *Model) SetFile(v ast.File) {
	m.file = v
}

func (m *Model) ParseError() string {
	return m.parseError
}

func (m *Model) SetParseError(v string) {
	m.parseError = v
}

func (m *Model) Parse() func(string) {
	return m.parse
}

func (m *Model) SetParse(v func(string)) {
	m.parse = v
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	m.__n3 = container.NewVBox()
	m.__n5 = widget.NewLabel("")
	m.__n5.SetText(fmt.Sprint("Go AST Explorer"))
	m.__n3.Add(m.__n5)
	m.__n6 = widget.NewLabel("")
	m.__n6.SetText(fmt.Sprint("Enter Go source code and click Parse to see the AST."))
	m.__n3.Add(m.__n6)
	m.__n0 = widget.NewMultiLineEntry()
	m.__n0.SetPlaceHolder("Enter Go code...")
	m.__n0.SetMinRowsVisible(10)
	m.__n0.SetText(fmt.Sprint(m.source))
	m.__n0.OnChanged = m.__n0_input_handler
	m.__n3.Add(m.__n0)
	m.__n7 = widget.NewButton("", nil)
	m.__n7.SetText(fmt.Sprint("Parse AST"))
	m.__n7.OnTapped = m.__n7_click_handler
	m.__n3.Add(m.__n7)
	m.__renderSlot0(m.__n3)
	m.__n4 = container.NewVBox()
	m.__renderSlot1(m.__n4)
	m.__n3.Add(m.__n4)
	content := fyne.CanvasObject(m.__n3)
	return content
}
