// Code generated by sngl (fyne) from app.sngl; DO NOT EDIT.

package ui

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"go/ast"
)

var _ = fmt.Sprint
var _ fyne.CanvasObject
var _ = container.NewVBox
var _ = widget.NewLabel

func ternary[T any](cond bool, a, b T) T {
	if cond {
		return a
	}
	return b
}

// Model holds the state for this SNGL UI.
type Model struct {
	source     string
	file       ast.File
	parseError string
	parse      func(string)
	__root     *fyne.Container
	__slot0    []fyne.CanvasObject
	__slot1    []fyne.CanvasObject

	__n1 *widget.Label
	__n0 *widget.Label
}

// New creates a Model with default values. Binds are initialized
// sequentially (not via a struct literal) so later init expressions can
// reference earlier fields via `m.<name>` — e.g. an interpolated
// `$"Hello, {nm}!"` reading `m.nm`.
func New() *Model {
	m := &Model{}
	m.source = "package main"
	m.file = ast.File{}
	m.parseError = ""
	m.parse = func(_ string) {}
	m.__root = container.NewVBox()
	m.__slot0 = nil
	m.__slot1 = nil
	return m
}

func (m *Model) doRefresh() {
}
func (m *Model) __renderSlot0(container *fyne.Container) {
	for _, __entry := range m.__slot0 {
		container.Remove(__entry)
	}
	m.__slot0 = nil
	if m.parseError != "" {
		m.__n1 = widget.NewLabel("")
		m.__n1.SetText(fmt.Sprint(m.parseError))
		container.Add(m.__n1)
		m.__slot0 = append(m.__slot0, m.__n1)
	}
}

func (m *Model) __renderSlot1(container *fyne.Container) {
	for _, __entry := range m.__slot1 {
		container.Remove(__entry)
	}
	m.__slot1 = nil
	for _, decl := range m.file.Decls {
		m.__n0 = widget.NewLabel("")
		m.__n0.SetText(fmt.Sprint(decl))
		container.Add(m.__n0)
		m.__slot1 = append(m.__slot1, m.__n0)
	}
}

func (m *Model) __n0_input_handler(s string) {
	m.source = s
	m.__n0.SetText(fmt.Sprint(m.source))
}

func (m *Model) __n6_click_handler() {
	m.parse(m.source)
}

func (m *Model) Source() string {
	return m.source
}

func (m *Model) SetSource(v string) {
	m.source = v
}

func (m *Model) File() ast.File {
	return m.file
}

func (m *Model) SetFile(v ast.File) {
	m.file = v
}

func (m *Model) ParseError() string {
	return m.parseError
}

func (m *Model) SetParseError(v string) {
	m.parseError = v
}

func (m *Model) Parse() func(string) {
	return m.parse
}

func (m *Model) SetParse(v func(string)) {
	m.parse = v
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	var parts []fyne.CanvasObject
	var part0 fyne.CanvasObject
	if part0 != nil {
		parts = append(parts, part0)
	}
	var part1 fyne.CanvasObject
	if part1 != nil {
		parts = append(parts, part1)
	}
	var part2 fyne.CanvasObject
	if part2 != nil {
		parts = append(parts, part2)
	}
	var part3 fyne.CanvasObject
	if part3 != nil {
		parts = append(parts, part3)
	}
	var part4 fyne.CanvasObject
	if part4 != nil {
		parts = append(parts, part4)
	}
	var part5 fyne.CanvasObject
	if part5 != nil {
		parts = append(parts, part5)
	}
	var part6 fyne.CanvasObject
	if part6 != nil {
		parts = append(parts, part6)
	}
	var part7 fyne.CanvasObject
	if part7 != nil {
		parts = append(parts, part7)
	}
	var part8 fyne.CanvasObject
	if part8 != nil {
		parts = append(parts, part8)
	}
	var part9 fyne.CanvasObject
	if part9 != nil {
		parts = append(parts, part9)
	}
	var part10 fyne.CanvasObject
	if part10 != nil {
		parts = append(parts, part10)
	}
	var part11 fyne.CanvasObject
	if part11 != nil {
		parts = append(parts, part11)
	}
	var part12 fyne.CanvasObject
	if part12 != nil {
		parts = append(parts, part12)
	}
	var part13 fyne.CanvasObject
	if part13 != nil {
		parts = append(parts, part13)
	}
	var part14 fyne.CanvasObject
	if part14 != nil {
		parts = append(parts, part14)
	}
	var part15 fyne.CanvasObject
	if part15 != nil {
		parts = append(parts, part15)
	}
	var part16 fyne.CanvasObject
	if part16 != nil {
		parts = append(parts, part16)
	}
	var part17 fyne.CanvasObject
	if part17 != nil {
		parts = append(parts, part17)
	}
	var part18 fyne.CanvasObject
	if part18 != nil {
		parts = append(parts, part18)
	}
	var part19 fyne.CanvasObject
	if part19 != nil {
		parts = append(parts, part19)
	}
	var part20 fyne.CanvasObject
	if part20 != nil {
		parts = append(parts, part20)
	}
	var part21 fyne.CanvasObject
	if part21 != nil {
		parts = append(parts, part21)
	}
	var part22 fyne.CanvasObject
	if part22 != nil {
		parts = append(parts, part22)
	}
	var part23 fyne.CanvasObject
	if part23 != nil {
		parts = append(parts, part23)
	}
	m.__root.Objects = parts
	return m.__root
}
