// Code generated by sngl (fyne) from app.sngl; DO NOT EDIT.

package ui

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"go/ast"
)

var _ = fmt.Sprint
var _ fyne.CanvasObject
var _ = container.NewVBox
var _ = widget.NewLabel

func ternary[T any](cond bool, a, b T) T {
	if cond {
		return a
	}
	return b
}

// Model holds the state for this SNGL UI.
type Model struct {
	source     string
	file       ast.File
	parseError string
	parse      func(string)

	label0  *widget.Label
	label1  *widget.Label
	entry2  *widget.Entry
	btn3    *widget.Button
	ifBox0  *fyne.Container
	label4  *widget.Label
	forBox1 *fyne.Container
}

// New creates a Model with default values. Binds are initialized
// sequentially (not via a struct literal) so later init expressions can
// reference earlier fields via `m.<name>` — e.g. an interpolated
// `$"Hello, {nm}!"` reading `m.nm`.
func New() *Model {
	m := &Model{}
	m.source = "package main"
	m.file = ast.File{}
	m.parseError = ""
	m.parse = func(_ string) {}
	return m
}

func (m *Model) doRefresh() {
	m.updateEntry2()
	m.updateLabel4()
	m.updateIf0()
	m.updateFor1()
}

func (m *Model) Source() string {
	return m.source
}

func (m *Model) SetSource(v string) {
	m.source = v
	m.entry2.SetText(v)
	m.updateEntry2()
}

func (m *Model) File() ast.File {
	return m.file
}

func (m *Model) SetFile(v ast.File) {
	m.file = v
	m.updateFor1()
}

func (m *Model) ParseError() string {
	return m.parseError
}

func (m *Model) SetParseError(v string) {
	m.parseError = v
	m.updateLabel4()
	m.updateIf0()
}

func (m *Model) Parse() func(string) {
	return m.parse
}

func (m *Model) SetParse(v func(string)) {
	m.parse = v
}

// BuildUI creates the widget tree. Call once; widgets are updated selectively.
func (m *Model) BuildUI() fyne.CanvasObject {
	var content fyne.CanvasObject
	var contentChildren []fyne.CanvasObject
	var contentC0 fyne.CanvasObject
	m.label0 = widget.NewLabel(fmt.Sprint("Go AST Explorer"))
	contentC0 = m.label0
	if contentC0 != nil {
		contentChildren = append(contentChildren, contentC0)
	}
	var contentC1 fyne.CanvasObject
	m.label1 = widget.NewLabel(fmt.Sprint("Enter Go source code and click Parse to see the AST."))
	contentC1 = m.label1
	if contentC1 != nil {
		contentChildren = append(contentChildren, contentC1)
	}
	var contentC2 fyne.CanvasObject
	m.entry2 = widget.NewMultiLineEntry()
	m.entry2.SetPlaceHolder("Enter Go code...")
	m.entry2.SetMinRowsVisible(10)
	m.entry2.SetText(fmt.Sprint(m.source))
	m.entry2.OnChanged = func(s string) {
		m.source = s
		m.updateEntry2()
	}
	contentC2 = m.entry2
	if contentC2 != nil {
		contentChildren = append(contentChildren, contentC2)
	}
	var contentC3 fyne.CanvasObject
	m.btn3 = widget.NewButton(
		fmt.Sprint("Parse AST"),
		func() {
			m.parse(m.source)
			m.doRefresh()
		},
	)
	contentC3 = m.btn3
	if contentC3 != nil {
		contentChildren = append(contentChildren, contentC3)
	}
	var contentC4 fyne.CanvasObject
	var contentC4Inner fyne.CanvasObject
	m.label4 = widget.NewLabel(fmt.Sprint(m.parseError))
	contentC4Inner = m.label4
	if contentC4Inner == nil {
		contentC4Inner = widget.NewLabel("")
	}
	m.ifBox0 = container.NewStack(contentC4Inner)
	if !(m.parseError != "") {
		m.ifBox0.Hide()
	}
	contentC4 = m.ifBox0
	if contentC4 != nil {
		contentChildren = append(contentChildren, contentC4)
	}
	var contentC5 fyne.CanvasObject
	var contentC5Children []fyne.CanvasObject
	var contentC5C0 fyne.CanvasObject
	var contentC5C0Items []fyne.CanvasObject
	for _, decl := range m.file.Decls {
		_ = decl
		var item fyne.CanvasObject
		var label5 *widget.Label
		label5 = widget.NewLabel(fmt.Sprint(decl))
		item = label5
		if item != nil {
			contentC5C0Items = append(contentC5C0Items, item)
		}
	}
	m.forBox1 = container.NewVBox(contentC5C0Items...)
	contentC5C0 = m.forBox1
	if contentC5C0 != nil {
		contentC5Children = append(contentC5Children, contentC5C0)
	}
	contentC5 = container.NewVBox(contentC5Children...)
	if contentC5 != nil {
		contentChildren = append(contentChildren, contentC5)
	}
	content = container.NewVBox(contentChildren...)
	if content == nil {
		content = widget.NewLabel("")
	}
	return content
}

func (m *Model) updateEntry2() {
	m.entry2.SetText(fmt.Sprint(m.source))
}

func (m *Model) updateLabel4() {
	m.label4.SetText(fmt.Sprint(m.parseError))
}

func (m *Model) updateIf0() {
	if m.parseError != "" {
		m.ifBox0.Show()
	} else {
		m.ifBox0.Hide()
	}
}

func (m *Model) updateFor1() {
	var items []fyne.CanvasObject
	for _, decl := range m.file.Decls {
		_ = decl
		var item fyne.CanvasObject
		var label5 *widget.Label
		label5 = widget.NewLabel(fmt.Sprint(decl))
		item = label5
		if item != nil {
			items = append(items, item)
		}
	}
	m.forBox1.Objects = items
	m.forBox1.Refresh()
}
