// Code generated by sngl (gtk4) from t.sngl; DO NOT EDIT.

package main

import (
	"git.duckfam.us/jonathan/sngl/pkg/go/gtk4rt"
)

type Counter struct {
	N   int
	Tag string
}

// Model holds the state and widget references for this SNGL UI.
type Model struct {
	c      Counter
	__n0   gtk4rt.Handle
	__root gtk4rt.Handle
}

// New creates a Model with default values. Binds initialize
// sequentially so later inits can reference earlier `m.<name>` fields.
func New() *Model {
	m := &Model{}
	m.c = Counter{}
	return m
}

func CounterBump(this Counter) Counter {
	next := this
	next.N = (this.N + 1)
	return next
}

func (m *Model) press() {
	m.c = CounterBump(m.c)
	gtk4rt.ButtonSetLabel(m.__n0, m.c.Tag)
}

func (m *Model) __n0_clicked_handler() {
	m.press()
}

func (m *Model) C() Counter {
	return m.c
}

func (m *Model) SetC(v Counter) {
	m.c = v
}

func (m *Model) buildWidgetTree() {
	if m.__root != nil {
		return
	}
	m.__root = gtk4rt.BoxNew(gtk4rt.OrientationVertical, 6)
	m.__n0 = gtk4rt.ButtonNew()
	gtk4rt.ButtonSetLabel(m.__n0, m.c.Tag)
	gtk4rt.Connect(m.__n0, "clicked", m.__n0_clicked_handler)
	gtk4rt.BoxAppend(m.__root, m.__n0)
}

// BuildUI constructs the widget tree and returns the top-level window.
func (m *Model) BuildUI(app gtk4rt.Handle) gtk4rt.Handle {
	m.buildWidgetTree()
	win := gtk4rt.ApplicationWindowNew(app)
	gtk4rt.WindowSetDefaultSize(win, 480, 640)
	gtk4rt.WindowSetChild(win, m.__root)
	return win
}
