// Code generated by sngl (bubbletea) from todo.sngl; DO NOT EDIT.

package ui

import (
	"fmt"
	"strings"

	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
)

var _ = fmt.Sprint
var _ = strings.Join
var _ = lipgloss.NewStyle

func ternary[T any](cond bool, a, b T) T {
	if cond {
		return a
	}
	return b
}

type Todo struct {
	Text string
	Done bool
}

// Model is the Bubble Tea model for this SNGL UI.
type Model struct {
	focus         int
	width, height int
}

// New creates a Model with default bind values.
func New() Model {
	m := Model{}
	return m
}

// SetTerminalSize sets the terminal dimensions.
func (m *Model) SetTerminalSize(w, h int) {
	m.width = w
	m.height = h
}

func (m Model) Init() tea.Cmd {
	return nil
}

func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmd tea.Cmd
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
	case tea.KeyPressMsg:
		switch {
		case msg.Code == 'c' && msg.Mod == tea.ModCtrl:
			return m, tea.Quit
		}
	}
	return m, cmd
}

func (m Model) View() tea.View {
	var content string
	content = lipgloss.NewStyle().Render(fmt.Sprint(""))
	v := tea.NewView(content)
	v.AltScreen = true
	return v
}

func (m Model) renderMain() string {
	var result string
	result = lipgloss.NewStyle().
		Padding(2).Render(fmt.Sprint(""))
	return result
}
