// Code generated by sngl (bubbletea) from todo.sngl; DO NOT EDIT.

package ui

import (
	"charm.land/bubbles/v2/textinput"
	"charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"fmt"
	"git.duckfam.us/jonathan/sngl/pkg/go/tui"
	"strings"
)

type Todo struct {
	Text string
	Done bool
}

// Model is the Bubble Tea model for this SNGL UI.
type Model struct {
	newTodo             string
	todos               []Todo
	checked__inst0      map[string]bool
	__focusID           int
	__focusLoop2_cursor int

	widget0 textinput.Model

	width, height int
}

// New creates a Model with default bind values.
func New() Model {
	m := Model{}
	m.newTodo = ""
	m.todos = []Todo{Todo{Text: "Buy groceries", Done: false}, Todo{Text: "Walk the dog", Done: true}, Todo{Text: "Write SNGL docs", Done: false}}
	m.checked__inst0 = map[string]bool{}
	m.__focusID = 0
	m.__focusLoop2_cursor = 0
	m.widget0 = textinput.New()
	m.widget0.Placeholder = "Buy eggs"
	m.widget0.SetValue(m.newTodo)
	m.widget0.Focus()
	m.resizeWidgets()
	return m
}

// SetTerminalSize sets the terminal dimensions and resizes widgets.
func (m *Model) SetTerminalSize(w, h int) {
	m.width = w
	m.height = h
	m.resizeWidgets()
}

// resizeWidgets sizes each bubbles widget to the current terminal extent.
func (m *Model) resizeWidgets() {
	m.widget0.SetWidth(tui.WidgetWidth(m.width))
}

func (m Model) status() string {
	return (("Todo List (" + fmt.Sprint(len(m.todos))) + " items)")
}

func (m *Model) __focusLoop2_len() int {
	var __focusCount int = 0
	for range m.todos {
		__focusCount = (__focusCount + 1)
	}
	return __focusCount
}

func (m *Model) __focusNext() {
	if m.__focusID == 0 {
		m.__focusID = 1
	} else {
		if m.__focusID == 1 {
			m.__focusID = 2
			m.__focusLoop2_cursor = 0
		} else {
			if m.__focusID == 2 {
				var __focusLen int = m.__focusLoop2_len()
				if (m.__focusLoop2_cursor + 1) < __focusLen {
					m.__focusLoop2_cursor = (m.__focusLoop2_cursor + 1)
				} else {
					m.__focusID = 3
				}
			} else {
				if m.__focusID == 3 {
					m.__focusID = 0
				}
			}
		}
	}
}

func (m *Model) __focusPrev() {
	if m.__focusID == 0 {
		m.__focusID = 3
	} else {
		if m.__focusID == 1 {
			m.__focusID = 0
		} else {
			if m.__focusID == 2 {
				if m.__focusLoop2_cursor > 0 {
					m.__focusLoop2_cursor = (m.__focusLoop2_cursor - 1)
				} else {
					m.__focusID = 1
				}
			} else {
				if m.__focusID == 3 {
					var __focusLen int = m.__focusLoop2_len()
					m.__focusID = 2
					m.__focusLoop2_cursor = (__focusLen - 1)
				}
			}
		}
	}
}

func (m Model) NewTodo() string {
	return m.newTodo
}

func (m Model) SetNewTodo(v string) Model {
	m.newTodo = v
	m.widget0.SetValue(m.newTodo)
	return m
}

type setNewTodoMsg struct{ value string }

func SetNewTodoCmd(v string) tea.Cmd {
	return func() tea.Msg { return setNewTodoMsg{value: v} }
}

func (m Model) Todos() []Todo {
	return m.todos
}

func (m Model) SetTodos(v []Todo) Model {
	m.todos = v
	return m
}

type setTodosMsg struct{ value []Todo }

func SetTodosCmd(v []Todo) tea.Cmd {
	return func() tea.Msg { return setTodosMsg{value: v} }
}

func (m Model) Checked__inst0() map[string]bool {
	return m.checked__inst0
}

func (m Model) SetChecked__inst0(v map[string]bool) Model {
	m.checked__inst0 = v
	return m
}

type setChecked__inst0Msg struct{ value map[string]bool }

func SetChecked__inst0Cmd(v map[string]bool) tea.Cmd {
	return func() tea.Msg { return setChecked__inst0Msg{value: v} }
}

func (m Model) Init() tea.Cmd {
	return textinput.Blink
}

func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmds []tea.Cmd
	var cmd tea.Cmd
	_ = cmd
	switch msg := msg.(type) {
	case setNewTodoMsg:
		m = m.SetNewTodo(msg.value)
	case setTodosMsg:
		m = m.SetTodos(msg.value)
	case setChecked__inst0Msg:
		m = m.SetChecked__inst0(msg.value)
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
		m.resizeWidgets()
	case tea.KeyPressMsg:
		switch {
		case msg.Code == 'c' && msg.Mod == tea.ModCtrl:
			return m, tea.Quit
		case msg.Code == tea.KeyTab && msg.Mod == 0:
			m.__focusNext()
			if m.__focusID == 0 {
				m.widget0.Focus()
			} else {
				m.widget0.Blur()
			}
		case msg.Code == tea.KeyTab && msg.Mod == tea.ModShift:
			m.__focusPrev()
			if m.__focusID == 0 {
				m.widget0.Focus()
			} else {
				m.widget0.Blur()
			}
		case msg.Code == tea.KeyEnter && m.__focusID == 1:
			m.todos = append(m.todos, Todo{Text: m.newTodo, Done: false})
			m.newTodo = ""
		case msg.Code == tea.KeySpace && m.__focusID == 2:
			func() {
				__focusPos2 := 0
				for index, item := range m.todos {
					_ = index
					_ = item
					if m.__focusLoop2_cursor == __focusPos2 {
						__bound_checked := !func() bool {
							if __v, __ok := m.checked__inst0[fmt.Sprint(index)]; __ok {
								return __v
							}
							return item.Done
						}()
						__cell1_checked__inst0 := func() bool {
							if __v, __ok := m.checked__inst0[fmt.Sprint(index)]; __ok {
								return __v
							}
							return item.Done
						}()
						__cell1_checked__inst0 = __bound_checked
						m.checked__inst0[fmt.Sprint(index)] = __cell1_checked__inst0
						m.todos[index].Done = !m.todos[index].Done
						return
					}
					__focusPos2++
				}
			}()
		case msg.Code == tea.KeyEnter && m.__focusID == 3:
			if __i := (len(m.todos) - 1); __i >= 0 && __i < len(m.todos) {
				m.todos = append(m.todos[:__i], m.todos[__i+1:]...)
			}
		}
	}
	if m.__focusID == 0 {
		m.widget0, cmd = m.widget0.Update(msg)
		cmds = append(cmds, cmd)
		m.newTodo = m.widget0.Value()
	}
	return m, tea.Batch(cmds...)
}

func (m Model) View() tea.View {
	var content string
	var contentChildren []string
	var content_0 string
	content_0 = lipgloss.NewStyle().
		Bold(true).Render(fmt.Sprint(m.status()))
	contentChildren = append(contentChildren, content_0)
	var content_1 string
	var content_1Children []string
	var content_1_0 string
	content_1_0 = m.widget0.View()
	content_1Children = append(content_1Children, content_1_0)
	var content_1_1 string
	content_1_1Focused := (m.__focusID == 1)
	content_1_1Prefix := " "
	if content_1_1Focused {
		content_1_1Prefix = ">"
	}
	content_1_1 = lipgloss.NewStyle().Render(content_1_1Prefix + " " + fmt.Sprint("Add"))
	content_1Children = append(content_1Children, content_1_1)
	content_1 = lipgloss.JoinHorizontal(lipgloss.Top, content_1Children...)
	content_1 = lipgloss.NewStyle().
		AlignHorizontal(lipgloss.Center).Render(content_1)
	contentChildren = append(contentChildren, content_1)
	var content_2 string
	var content_2Children []string
	var content_2_0 string
	__focusPos2 := 0
	_ = __focusPos2
	var content_2_0Items []string
	for index, item := range m.todos {
		_ = index
		_ = item
		var content_2_0Item string
		content_2_0ItemFocused := ((m.__focusID == 2) && (m.__focusLoop2_cursor == __focusPos2))
		content_2_0ItemPrefix := " "
		if content_2_0ItemFocused {
			content_2_0ItemPrefix = ">"
		}
		content_2_0Item = lipgloss.NewStyle().Render(content_2_0ItemPrefix + " " + fmt.Sprint(item.Text))
		__focusPos2++
		content_2_0Items = append(content_2_0Items, content_2_0Item)
	}
	content_2_0 = strings.Join(content_2_0Items, "\n")
	if content_2_0 != "" {
		content_2Children = append(content_2Children, content_2_0)
	}
	content_2 = lipgloss.JoinVertical(lipgloss.Left, content_2Children...)
	contentChildren = append(contentChildren, content_2)
	var content_3 string
	content_3Focused := (m.__focusID == 3)
	content_3Prefix := " "
	if content_3Focused {
		content_3Prefix = ">"
	}
	content_3 = lipgloss.NewStyle().Render(content_3Prefix + " " + fmt.Sprint("Remove"))
	contentChildren = append(contentChildren, content_3)
	content = lipgloss.JoinVertical(lipgloss.Left, contentChildren...)
	content = lipgloss.NewStyle().
		Padding(2).Render(content)
	v := tea.NewView(content)
	v.AltScreen = true
	return v
}
