// Code generated by sngl (bubbletea) from todo.sngl; DO NOT EDIT.

package ui

import (
	"charm.land/bubbles/v2/textinput"
	"charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"fmt"
	"strings"
)

type Todo struct {
	Text string
	Done bool
}

// Model is the Bubble Tea model for this SNGL UI.
type Model struct {
	newTodo             string
	todos               []Todo
	__focusID           int
	__focusLoop2_cursor int

	input0 textinput.Model

	width, height int
}

// New creates a Model with default bind values.
func New() Model {
	m := Model{}
	m.newTodo = ""
	m.todos = []Todo{Todo{Text: "Buy groceries", Done: false}, Todo{Text: "Walk the dog", Done: true}, Todo{Text: "Write SNGL docs", Done: false}}
	m.__focusID = 0
	m.__focusLoop2_cursor = 0
	m.input0 = textinput.New()
	m.input0.Placeholder = "Buy eggs"
	m.input0.SetValue(m.newTodo)
	m.input0.Focus()
	return m
}

// SetTerminalSize sets the terminal dimensions.
func (m *Model) SetTerminalSize(w, h int) {
	m.width = w
	m.height = h
}

func (m Model) status() string {
	return (("Todo List (" + fmt.Sprint(len(m.todos))) + " items)")
}

func (m *Model) __focusNext() {
	if m.__focusID == 0 {
		m.__focusID = 1
	} else {
		if m.__focusID == 1 {
			m.__focusID = 2
			m.__focusLoop2_cursor = 0
		} else {
			if m.__focusID == 2 {
				__focusLen := len(m.todos)
				if (m.__focusLoop2_cursor + 1) < __focusLen {
					m.__focusLoop2_cursor = (m.__focusLoop2_cursor + 1)
				} else {
					m.__focusID = 3
				}
			} else {
				if m.__focusID == 3 {
					m.__focusID = 0
				}
			}
		}
	}
}

func (m *Model) __focusPrev() {
	if m.__focusID == 0 {
		m.__focusID = 3
	} else {
		if m.__focusID == 1 {
			m.__focusID = 0
		} else {
			if m.__focusID == 2 {
				if m.__focusLoop2_cursor > 0 {
					m.__focusLoop2_cursor = (m.__focusLoop2_cursor - 1)
				} else {
					m.__focusID = 1
				}
			} else {
				if m.__focusID == 3 {
					m.__focusID = 2
					m.__focusLoop2_cursor = 0
				}
			}
		}
	}
}

func (m Model) NewTodo() string {
	return m.newTodo
}

func (m Model) SetNewTodo(v string) Model {
	m.newTodo = v
	m.input0.SetValue(m.newTodo)
	return m
}

type setNewTodoMsg struct{ value string }

func SetNewTodoCmd(v string) tea.Cmd {
	return func() tea.Msg { return setNewTodoMsg{value: v} }
}

func (m Model) Todos() []Todo {
	return m.todos
}

func (m Model) SetTodos(v []Todo) Model {
	m.todos = v
	return m
}

type setTodosMsg struct{ value []Todo }

func SetTodosCmd(v []Todo) tea.Cmd {
	return func() tea.Msg { return setTodosMsg{value: v} }
}

func (m Model) Init() tea.Cmd {
	return textinput.Blink
}

func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	var cmd tea.Cmd
	switch msg := msg.(type) {
	case setNewTodoMsg:
		m = m.SetNewTodo(msg.value)
	case setTodosMsg:
		m = m.SetTodos(msg.value)
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
	case tea.KeyPressMsg:
		switch {
		case msg.Code == 'c' && msg.Mod == tea.ModCtrl:
			return m, tea.Quit
		case msg.Code == tea.KeyTab && msg.Mod == 0:
			m.__focusNext()
			if m.__focusID == 0 {
				m.input0.Focus()
			} else {
				m.input0.Blur()
			}
		case msg.Code == tea.KeyTab && msg.Mod == tea.ModShift:
			m.__focusPrev()
			if m.__focusID == 0 {
				m.input0.Focus()
			} else {
				m.input0.Blur()
			}
		case msg.Code == tea.KeyEnter && m.__focusID == 1:
			m.todos = append(m.todos, Todo{Text: m.newTodo})
			m.newTodo = ""
		case msg.Code == tea.KeyEnter && m.__focusID == 2:
			for index, _ := range m.todos {
				if m.__focusLoop2_cursor == index {
					m.todos[index].Done = !m.todos[index].Done
					break
				}
			}
		case msg.Code == tea.KeyEnter && m.__focusID == 3:
			m.todos = append(m.todos[:(len(m.todos)-1)], m.todos[(len(m.todos)-1)+1:]...)
		}
	}
	if m.__focusID == 0 {
		m.input0, cmd = m.input0.Update(msg)
		m.newTodo = m.input0.Value()
	}
	return m, cmd
}

func (m Model) View() tea.View {
	var content string
	var contentChildren []string
	var content_0 string
	content_0 = lipgloss.NewStyle().
		Bold(true).Render(fmt.Sprint(m.status()))
	contentChildren = append(contentChildren, content_0)
	var content_1 string
	var content_1Children []string
	var content_1_0 string
	content_1_0 = m.input0.View()
	content_1Children = append(content_1Children, content_1_0)
	var content_1_1 string
	content_1_1Focused := (m.__focusID == 1)
	content_1_1Prefix := " "
	if content_1_1Focused {
		content_1_1Prefix = ">"
	}
	content_1_1 = lipgloss.NewStyle().Render(content_1_1Prefix + " " + fmt.Sprint("Add"))
	content_1Children = append(content_1Children, content_1_1)
	content_1 = lipgloss.JoinHorizontal(lipgloss.Top, content_1Children...)
	content_1 = lipgloss.NewStyle().
		AlignHorizontal(lipgloss.Center).Render(content_1)
	contentChildren = append(contentChildren, content_1)
	var content_2 string
	var content_2Children []string
	var content_2_0 string
	var content_2_0Items []string
	for index, item := range m.todos {
		_ = index
		_ = item
		var content_2_0Item string
		content_2_0ItemFocused := ((m.__focusID == 2) && (m.__focusLoop2_cursor == index))
		content_2_0ItemPrefix := " "
		if content_2_0ItemFocused {
			content_2_0ItemPrefix = ">"
		}
		content_2_0Item = lipgloss.NewStyle().Render(content_2_0ItemPrefix + " " + fmt.Sprint(item.Text))
		content_2_0Items = append(content_2_0Items, content_2_0Item)
	}
	content_2_0 = strings.Join(content_2_0Items, "\n")
	content_2Children = append(content_2Children, content_2_0)
	content_2 = lipgloss.JoinVertical(lipgloss.Left, content_2Children...)
	contentChildren = append(contentChildren, content_2)
	var content_3 string
	content_3Focused := (m.__focusID == 3)
	content_3Prefix := " "
	if content_3Focused {
		content_3Prefix = ">"
	}
	content_3 = lipgloss.NewStyle().Render(content_3Prefix + " " + fmt.Sprint("Remove"))
	contentChildren = append(contentChildren, content_3)
	content = lipgloss.JoinVertical(lipgloss.Left, contentChildren...)
	content = lipgloss.NewStyle().
		Padding(2).Render(content)
	v := tea.NewView(content)
	v.AltScreen = true
	return v
}
