//go:build !js

package html

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"git.duckfam.us/jonathan/sngl/codegen"
	"git.duckfam.us/jonathan/sngl/codegen/lang/javascript"
	"git.duckfam.us/jonathan/sngl/codegen/testharness"
	"git.duckfam.us/jonathan/sngl/ir"
)

// emitTestagentFiles writes the JS test files into sink when html
// Generate runs under --opt test=true testMode=agent. Produces:
//
//   - testagent_main.js — output of javascript.LowerTestFile(agent),
//     contains test funcs + Registry.register calls.
//   - snapshot.js — registers the DOM-string capture under
//     Snapshots.register(”, ...).
//   - current_model.js — setCurrentTestModel/currentTestModel/
//     newTestComponent accessors.
//   - testagent/*.js — verbatim copies of pkg/js/testagent/*.js so the
//     browser can resolve the `./testagent/testagent.js` ES module
//     specifier emitted in the testagent_main.js + snapshot.js
//     imports.
//
// The <script type="module"> tag that imports these and calls
// TestAgent.main() on DOMContentLoaded is injected by html.go's
// Generate at the end of <body>.
func emitTestagentFiles(sink codegen.Sink, pkg *ir.Package) error {
	testFns, suffixes, methodFields := codegen.CollectTestFuncs(pkg)
	if len(testFns) == 0 {
		return nil
	}

	testagentMain := javascript.LowerTestFile("ui", pkg, testFns, suffixes, methodFields, javascript.TestEmitAgent)
	if err := writeRawHTMLFile(sink, "testagent_main.js", []byte(testagentMain)); err != nil {
		return err
	}

	snapshotJS := `// Generated by SNGL — do not edit.
import { Snapshots } from './testagent/testagent.js';

// Browser-side snapshot capture for html. Serialises the document
// element as text/html bytes. Per-testRunner name prefix is empty —
// html is a single-backend platform.
//
// What a control holds is a property, which outerHTML does not carry: typed
// text and a ticked box are written onto a copy as the attributes they would
// be, so the snapshot shows what the user sees.
Snapshots.register('', () => {
    const copy = document.documentElement.cloneNode(true);
    const live = document.querySelectorAll('input, textarea');
    const copies = copy.querySelectorAll('input, textarea');
    live.forEach((el, i) => {
        const c = copies[i];
        if (!c) return;
        if (el.type === 'checkbox' || el.type === 'radio') {
            if (el.checked) c.setAttribute('checked', '');
        } else if (el.tagName === 'TEXTAREA') {
            c.textContent = el.value;
        } else if (el.value !== '') {
            c.setAttribute('value', el.value);
        }
    });
    const text = copy.outerHTML;
    return ['text/html', new TextEncoder().encode(text)];
});
`
	if err := writeRawHTMLFile(sink, "snapshot.js", []byte(snapshotJS)); err != nil {
		return err
	}

	accessor := `// Generated by SNGL — do not edit.
// Per-test fresh-model accessor.
//
// The first test gets the page as it loaded; every later one remounts it
// through window.__sngl_reset (see html.go), so no test sees another's writes.

let __snglCurrentModel = null;
let __snglMounted = false;
export function setCurrentTestModel(m) { __snglCurrentModel = m; }
export function currentTestModel() { return __snglCurrentModel; }
export function newTestComponent() {
    if (typeof window === 'undefined' || !window.__sngl_state) {
        throw new Error('SNGL state not exposed — was the page generated with --opt test=true?');
    }
    if (__snglMounted) {
        window.__sngl_reset();
    }
    __snglMounted = true;
    return window.__sngl_state;
}
`
	if err := writeRawHTMLFile(sink, "current_model.js", []byte(accessor)); err != nil {
		return err
	}

	if err := copyTestagentRuntime(sink); err != nil {
		return err
	}
	return nil
}

// copyTestagentRuntime copies every *.js file from pkg/js/testagent/
// (excluding tests) into the output's `testagent/` subdirectory so the
// browser can resolve `./testagent/testagent.js` imports emitted in
// the generated testagent_main.js + snapshot.js.
func copyTestagentRuntime(sink codegen.Sink) error {
	src, err := testharness.LangTestagentPath("js")
	if err != nil {
		return fmt.Errorf("html testagent: %w", err)
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return fmt.Errorf("html testagent: read %s: %w", src, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".js") {
			continue
		}
		if strings.HasSuffix(name, ".test.js") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(src, name))
		if err != nil {
			return fmt.Errorf("html testagent: read %s: %w", name, err)
		}
		if err := writeRawHTMLFile(sink, "testagent/"+name, data); err != nil {
			return err
		}
	}
	return nil
}

// writeRawHTMLFile copies bytes through sink. Matches the helper pattern
// in bubbletea/fyne/gtk4. Named to avoid colliding with the existing
// writeSinkFile helper in html.go.
func writeRawHTMLFile(sink codegen.Sink, name string, content []byte) error {
	wc, err := sink.Create(name)
	if err != nil {
		return err
	}
	if _, err := wc.Write(content); err != nil {
		wc.Close()
		return err
	}
	return wc.Close()
}
