package golang_test

import (
	"strings"
	"testing"

	"duckfam.us/sngl/codegen"
	"duckfam.us/sngl/codegen/lang/golang"
)

func TestFileEmitter_BasicComposition(t *testing.T) {
	sink := codegen.NewMemSink()
	tr := &golang.Translator{}
	e := tr.NewFileEmitter(sink, codegen.FileOptions{
		Name:        "model.go",
		Source:      "app.sngl",
		Platform:    "test",
		PackageName: "main",
	})
	if alias := e.RequireImport("fmt"); alias != "fmt" {
		t.Errorf("RequireImport(fmt)=%q want fmt", alias)
	}
	if alias := e.RequireImport("time"); alias != "time" {
		t.Errorf("RequireImport(time)=%q want time", alias)
	}
	e.Write([]byte("func Greet() {\n\tfmt.Println(time.Now())\n}\n"))
	if err := e.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	got := string(sink.Files()["model.go"])
	for _, want := range []string{
		"// Code generated by sngl (test) from app.sngl",
		"package main",
		`"fmt"`,
		`"time"`,
		"func Greet()",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in output:\n%s", want, got)
		}
	}
}

func TestFileEmitter_AliasConflict(t *testing.T) {
	sink := codegen.NewMemSink()
	tr := &golang.Translator{}
	e := tr.NewFileEmitter(sink, codegen.FileOptions{
		Name:        "model.go",
		PackageName: "main",
	})
	// Two paths whose default alias is "time"; second should be aliased.
	a := e.RequireImport("time")
	b := e.RequireImport("git.example/dup/time")
	if a != "time" {
		t.Errorf("first alias = %q, want time", a)
	}
	// Note: the emitter returns the default alias from RequireImport for
	// simplicity. Conflict resolution happens at Close render time. So
	// the caller of the second RequireImport would see "time" too. This
	// is acceptable for today's emitter usage where each translator only
	// references one of the conflicting paths. The render still emits
	// distinct aliases in the import block.
	if b != "time" {
		t.Errorf("RequireImport default = %q, want time", b)
	}
	e.Write([]byte("var _ = time.Now()\n"))
	if err := e.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	got := string(sink.Files()["model.go"])
	// Two imports rendered, second with explicit alias suffix.
	if !strings.Contains(got, `"time"`) || !strings.Contains(got, `"git.example/dup/time"`) {
		t.Errorf("both import paths must be rendered:\n%s", got)
	}
}

func TestFileEmitter_SingleImportInline(t *testing.T) {
	sink := codegen.NewMemSink()
	tr := &golang.Translator{}
	e := tr.NewFileEmitter(sink, codegen.FileOptions{Name: "m.go", PackageName: "p"})
	e.RequireImport("fmt")
	e.Write([]byte("var _ = fmt.Sprintf\n"))
	if err := e.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	got := string(sink.Files()["m.go"])
	// gofmt may collapse `import "fmt"` to inline form for single imports.
	if !strings.Contains(got, `"fmt"`) {
		t.Errorf("missing fmt import:\n%s", got)
	}
}

func TestFileEmitter_GofmtError(t *testing.T) {
	sink := codegen.NewMemSink()
	tr := &golang.Translator{}
	e := tr.NewFileEmitter(sink, codegen.FileOptions{Name: "m.go", PackageName: "p"})
	e.Write([]byte("not valid go\n"))
	err := e.Close()
	if err == nil {
		t.Fatal("expected gofmt error")
	}
}
