package golang

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"git.duckfam.us/jonathan/sngl/codegen"
	"git.duckfam.us/jonathan/sngl/ir"
)

// fileEmitter implements codegen.FileEmitter for Go output. The platform
// writes function signatures, declarations, and IR-translated bodies
// through it; the emitter buffers all writes and accumulates imports.
// Close assembles a complete Go file (generated-by comment + package +
// import block + body), runs it through go/format, and writes it to
// the sink under opts.Name.
//
// Imports are tracked via the embedded *GoIRContext.RequireImport. The
// emitter resolves alias conflicts at Close time so the import block
// renders with `alias "path"` where needed.
type fileEmitter struct {
	sink   codegen.Sink
	opts   codegen.FileOptions
	buf    bytes.Buffer
	gc     *GoIRContext
	closed bool
}

func newFileEmitter(sink codegen.Sink, opts codegen.FileOptions) *fileEmitter {
	// Translator-side imports flow into a fresh *GoIRContext. We don't
	// have an ExprCtx yet — callers that need EvalExpr/EvalStmt can set
	// gc.Ctx themselves via SetContext (below) or use the emitter's
	// io.Writer directly for raw bytes.
	gc := &GoIRContext{
		imports:            newImportSet(),
		EmitLineDirectives: opts.Maps,
		// The directive is resolved against the emitted file's own
		// directory, which is the output root plus whatever subdirectory
		// this file sits in.
		LineDirBase: lineDirBase(opts),
	}
	return &fileEmitter{sink: sink, opts: opts, gc: gc}
}

// Context returns the embedded GoIRContext so platforms can bind it to
// their ExprCtx (e.g. via `fe.Context().Ctx = ctx.ExprCtx.ForComponent(c)`)
// before calling EvalExpr/EvalStmt. Used during platform migration to
// reuse existing IRContext setup logic.
func (fe *fileEmitter) Context() *GoIRContext { return fe.gc }

// Write appends raw bytes to the file body. Imports referenced through
// EvalExpr/EvalStmt on the same emitter are still tracked separately;
// raw text that names a package directly (e.g. platform-injected
// helper code) must register imports explicitly via RequireImport.
func (fe *fileEmitter) Write(p []byte) (int, error) {
	if fe.closed {
		return 0, io.ErrClosedPipe
	}
	return fe.buf.Write(p)
}

// EvalExpr translates an IR expression to Go and auto-registers any
// native imports the expression references.
func (fe *fileEmitter) EvalExpr(e ir.Expr) string {
	if fe.gc == nil || fe.gc.Ctx == nil {
		return ""
	}
	return fe.gc.EvalExpr(e)
}

// EvalStmt translates an IR statement to one or more Go lines and
// auto-registers any native imports.
func (fe *fileEmitter) EvalStmt(s ir.Stmt) []string {
	if fe.gc == nil || fe.gc.Ctx == nil {
		return nil
	}
	return fe.gc.EvalStmt(s)
}

// RequireImport registers an import path and returns the local alias
// to use at call sites. Default alias is the last path component;
// conflicts get a numeric suffix.
func (fe *fileEmitter) RequireImport(path string) string {
	fe.gc.RequireImport(path)
	if a := fe.gc.ForcedAlias(path); a != "" {
		return a
	}
	return goAliasFor(path)
}

// RequireImportAs registers an import path under an explicit alias, returning
// that alias. Used when the path-derived default would collide with another
// import and call sites reference a fixed selector.
func (fe *fileEmitter) RequireImportAs(path, alias string) string {
	fe.gc.RequireImportAs(path, alias)
	return alias
}

// Close assembles the file (generated-by + package + imports + body),
// formats, and writes to the sink.
func (fe *fileEmitter) Close() error {
	if fe.closed {
		return nil
	}
	fe.closed = true

	var assembled bytes.Buffer
	if fe.opts.Source != "" && fe.opts.Platform != "" {
		fmt.Fprintf(&assembled, "// Code generated by sngl (%s) from %s; DO NOT EDIT.\n\n",
			fe.opts.Platform, fe.opts.Source)
	}
	if fe.opts.PackageName != "" {
		fmt.Fprintf(&assembled, "package %s\n\n", fe.opts.PackageName)
	}
	if fe.opts.CgoPreamble != "" {
		assembled.WriteString(fe.opts.CgoPreamble)
		assembled.WriteString("\n")
	}
	if imps := fe.renderImports(); len(imps) > 0 {
		assembled.Write(imps)
		assembled.WriteByte('\n')
	}
	assembled.Write(fe.buf.Bytes())

	src := assembled.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		// Return the unformatted source in the error message so the
		// caller can diagnose codegen issues against the actual output.
		return fmt.Errorf("go format %s: %w\n%s", fe.opts.Name, err, src)
	}

	w, err := fe.sink.Create(fe.opts.Name)
	if err != nil {
		return err
	}
	if _, err := w.Write(formatted); err != nil {
		w.Close()
		return err
	}
	return w.Close()
}

// renderImports composes the file's import block from the accumulated
// import set. Single-import files use the bare `import "path"` form;
// multi-import files use grouped `import ( ... )`. Aliases are emitted
// only when the default alias would collide with another import.
func (fe *fileEmitter) renderImports() []byte {
	paths := fe.gc.Imports()
	if len(paths) == 0 {
		return nil
	}
	// Resolve aliases: default per path; on collision the later
	// registrant gets a numeric suffix.
	type entry struct {
		path  string
		alias string
		blank bool
	}
	entries := make([]entry, 0, len(paths))
	used := map[string]bool{}
	// Reserve forced aliases first so path-derived defaults that would clash
	// with them get a numeric suffix instead of stealing the name.
	for _, p := range paths {
		if a := fe.gc.ForcedAlias(p); a != "" {
			used[a] = true
		}
	}
	for _, p := range paths {
		alias := fe.gc.ForcedAlias(p)
		if alias == "" {
			alias = goAliasFor(p)
			base := alias
			i := 1
			for used[alias] {
				i++
				alias = fmt.Sprintf("%s%d", base, i)
			}
		}
		used[alias] = true
		entries = append(entries, entry{path: p, alias: alias, blank: fe.gc.IsBlankImport(p)})
	}
	// Stable order: sort by path for output stability across runs.
	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })

	var b bytes.Buffer
	if len(entries) == 1 {
		e := entries[0]
		switch {
		case e.blank:
			fmt.Fprintf(&b, "import _ %q\n", e.path)
		case e.alias != "" && e.alias != goAliasFor(e.path):
			fmt.Fprintf(&b, "import %s %q\n", e.alias, e.path)
		default:
			fmt.Fprintf(&b, "import %q\n", e.path)
		}
		return b.Bytes()
	}
	b.WriteString("import (\n")
	for _, e := range entries {
		switch {
		case e.blank:
			fmt.Fprintf(&b, "\t_ %q\n", e.path)
		case e.alias != "" && e.alias != goAliasFor(e.path):
			fmt.Fprintf(&b, "\t%s %q\n", e.alias, e.path)
		default:
			fmt.Fprintf(&b, "\t%q\n", e.path)
		}
	}
	b.WriteString(")\n")
	return b.Bytes()
}

// goAliasFor returns the conventional package name for an import path:
// the last path component, with non-identifier characters stripped.
// E.g. "fmt" → "fmt", "encoding/json" → "json", "git.duckfam.us/.../i18n"
// → "i18n". Mirrors the implicit aliasing Go uses by default; the
// emitter only emits an explicit alias when the conventional one
// collides with another import.
func goAliasFor(p string) string {
	base := path.Base(p)
	// Semantic-import-versioned modules end in /vN (e.g.
	// "charm.land/bubbletea/v2"); the Go package name is the parent
	// component, not "vN". Use it so two different /vN modules don't both
	// derive "v2" and collide (which would force a bogus numeric alias).
	if isSemverComponent(base) {
		base = path.Base(path.Dir(p))
	}
	// Strip anything past a non-identifier char.
	out := make([]byte, 0, len(base))
	for i := 0; i < len(base); i++ {
		c := base[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			out = append(out, c)
			continue
		}
		break
	}
	if len(out) == 0 || (out[0] >= '0' && out[0] <= '9') {
		// Fall back to a normalized form to keep the alias a valid
		// identifier (very unusual paths only).
		return "pkg" + strings.Map(func(r rune) rune {
			if r == '/' || r == '.' || r == '-' {
				return '_'
			}
			return r
		}, base)
	}
	return string(out)
}

// isSemverComponent reports whether s is a semantic-import-version path
// component: "v" followed by one or more digits (v2, v3, …). v0/v1 never
// appear as path components, but treating them uniformly is harmless.
func isSemverComponent(s string) bool {
	if len(s) < 2 || s[0] != 'v' {
		return false
	}
	for i := 1; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

// lineDirBase is the directory opts.Name will land in once the sink's files
// are written under opts.OutDir.
func lineDirBase(opts codegen.FileOptions) string {
	if opts.OutDir == "" {
		return ""
	}
	return filepath.Join(opts.OutDir, filepath.Dir(opts.Name))
}
