// Command specgen generates docs/reference/specification.md from the v2 EBNF grammar.
//
// Usage: go run ./internal/cmd/specgen
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

func main() {
	_, thisFile, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	ebnfPath := filepath.Join(root, "internal", "parser", "sngl.ebnf")
	outPath := filepath.Join(root, "docs", "reference", "specification.md")

	prods := parseEBNF(ebnfPath)

	var b strings.Builder
	b.WriteString(`---
title: "Language Specification"
order: 50
description: "Formal grammar and semantics of the SNGL language"
---

<!-- Code generated by internal/cmd/specgen from internal/parser/sngl.ebnf; DO NOT EDIT. -->

`)

	writeGrammar(&b, prods)
	writePrecedence(&b)
	writeKeywords(&b)
	writeSemantics(&b)

	os.WriteFile(outPath, []byte(b.String()), 0o644)
}

// production is a named EBNF rule with its body and preceding comment block.
type production struct {
	name    string
	body    string
	comment string // preceding # comment lines
}

var prodRE = regexp.MustCompile(`^(\w+)\s*=\s*(.*)`)

// parseEBNF reads the EBNF file and extracts productions with their comments.
func parseEBNF(path string) []production {
	f, err := os.Open(path)
	if err != nil {
		fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	var prods []production
	var commentBuf []string
	var nameBuf string
	var bodyBuf []string

	flush := func() {
		if nameBuf != "" {
			prods = append(prods, production{
				name:    nameBuf,
				body:    strings.Join(bodyBuf, "\n"),
				comment: strings.Join(commentBuf, "\n"),
			})
		}
		nameBuf = ""
		bodyBuf = nil
	}

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()

		// Comment line
		if strings.HasPrefix(line, "#") {
			if nameBuf != "" {
				flush()
				commentBuf = nil
			}
			commentBuf = append(commentBuf, line)
			continue
		}

		// Blank line
		if strings.TrimSpace(line) == "" {
			if nameBuf != "" {
				flush()
			}
			continue
		}

		// Check if this line starts a new production (Name = ...)
		if m := prodRE.FindStringSubmatch(line); m != nil {
			// If we were already in a production, flush it
			if nameBuf != "" {
				flush()
				commentBuf = nil
			}
			nameBuf = m[1]
			bodyBuf = []string{m[2]}
			continue
		}

		// Continuation of current production body
		if nameBuf != "" {
			bodyBuf = append(bodyBuf, line)
		} else {
			// Not in a production, not a comment — skip
			commentBuf = nil
		}
	}

	flush()
	return prods
}

// Sections group productions for display.
var sections = []struct {
	title string
	rules []string
}{
	{"Document Structure", []string{"Document", "StmtBlock"}},
	{"Statements", []string{"Stmt", "VisualOrStmt", "IfNode", "ForNode", "AssignOp"}},
	{"Imports", []string{"ImportDecl"}},
	{"Type Declarations", []string{"StructDecl", "StructField", "EnumDecl", "UnitDecl"}},
	{"Constants & Variables", []string{
		"ConstDecl", "ConstSpec", "IdentList",
		"VarDecl", "VarSpec", "VarHandler",
	}},
	{"Functions", []string{"FuncDecl", "FuncTail", "FuncBodyTail", "FuncName", "TypeParamList", "ParamList", "Param"}},
	{"Components", []string{"ComponentDecl", "CompParamList", "CompParam", "CompParamTail"}},
	{"Expressions", []string{
		"Expr", "TernaryExpr", "OrExpr", "AndExpr",
		"EqExpr", "CmpExpr", "AddExpr", "MulExpr",
		"EqOp", "CmpOp", "AddOp", "MulOp",
		"UnaryExpr",
	}},
	{"Argument Lists", []string{"ArgList", "Arg"}},
	{"Literals & Primaries", []string{
		"ListBody", "ListElem", "StructLitBody", "AnonStructLit", "AnonField", "FuncLit",
	}},
	{"String Interpolation", []string{"InterpStr", "TripleInterp"}},
	{"Types", []string{"Type", "TypeList"}},
}

// tokenReplacements maps terminal names to readable symbols.
var tokenReplacements = map[string]string{
	"ident": "IDENT", "int_lit": "INT", "float_lit": "FLOAT",
	"str_full": `STRING`, "triple_full": `TRIPLE_STRING`, "raw_str": "RAW_STRING",
	"color": "COLOR", "unit_lit": "UNIT", "elem_ref": "ELEM_REF",
	"lparen": `"("`, "rparen": `")"`, "lbrace": `"{"`, "rbrace": `"}"`,
	"lbracket": `"["`, "rbracket": `"]"`,
	"comma": `","`, "dot": `"."`, "colon": `":"`, "assign": `"="`,
	"at": `"@"`, "arrow": `"->"`, "fat_arrow": `"=>"`, "ellipsis": `"..."`,
	"plus": `"+"`, "minus": `"-"`, "star": `"*"`, "slash": `"/"`, "percent": `"%"`,
	"bang": `"!"`, "bangbang": `"!!"`, "question": `"?"`,
	"eq": `"=="`, "neq": `"!="`, "lt": `"<"`, "gt": `">"`,
	"lte": `"<="`, "gte": `">="`,
	"land": `"&&"`, "lor": `"||"`,
	"plus_assign": `"+="`, "minus_assign": `"-="`, "star_assign": `"*="`,
	"slash_assign": `"/="`, "pct_assign": `"%="`,
	"kw_import": `"import"`, "kw_struct": `"struct"`, "kw_enum": `"enum"`,
	"kw_const": `"const"`, "kw_var": `"var"`, "kw_component": `"component"`,
	"kw_if": `"if"`, "kw_for": `"for"`, "kw_else": `"else"`,
	"kw_func": `"func"`, "kw_unit": `"unit"`, "kw_return": `"return"`,
	"slashdash": `"/-"`, "semi": `";"`,
	"str_start": "STR_START", "str_end": "STR_END", "str_resume": "STR_RESUME",
	"triple_start": "TRIPLE_START", "triple_end": "TRIPLE_END",
}

var tokenRE = regexp.MustCompile(`\b[a-z][a-z_]*\b`)

func writeGrammar(b *strings.Builder, prods []production) {
	b.WriteString("## Grammar\n\n")
	b.WriteString("SNGL uses an LL(1) recursive-descent parser with automatic semicolon insertion.\n")
	b.WriteString("The following grammar is extracted from the v2 EBNF definition.\n\n")
	b.WriteString("**Notation:** `{ X }` = zero or more, `[ X ]` = optional, `|` = alternative, `( X )` = grouping.\n\n")

	// Build map from name to production
	prodMap := map[string]production{}
	for _, p := range prods {
		prodMap[p.name] = p
	}

	for _, sec := range sections {
		b.WriteString("### " + sec.title + "\n\n```ebnf\n")
		for _, name := range sec.rules {
			p, ok := prodMap[name]
			if !ok {
				continue
			}
			body := formatBody(p.body)
			fmt.Fprintf(b, "%s = %s\n\n", name, body)
		}
		b.WriteString("```\n\n")
	}
}

// formatBody replaces terminal names with readable tokens and cleans up the body.
func formatBody(body string) string {
	// Strip trailing " ."
	body = strings.TrimSuffix(strings.TrimSpace(body), ".")
	body = strings.TrimSpace(body)

	// Replace terminal names with readable symbols
	body = tokenRE.ReplaceAllStringFunc(body, func(s string) string {
		if r, ok := tokenReplacements[s]; ok {
			return r
		}
		return s
	})

	// Clean up multi-line bodies: normalize indentation
	lines := strings.Split(body, "\n")
	if len(lines) == 1 {
		return strings.TrimSpace(lines[0])
	}

	var out []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		// Preserve leading pipe for alternatives
		if strings.HasPrefix(trimmed, "|") {
			out = append(out, "    "+trimmed)
		} else {
			out = append(out, "    "+trimmed)
		}
	}
	return "\n" + strings.Join(out, "\n")
}

func writePrecedence(b *strings.Builder) {
	b.WriteString("## Operator Precedence\n\n")
	b.WriteString("| Precedence | Operators | Associativity | Description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	b.WriteString("| 1 | `? :` | right | Ternary |\n")
	b.WriteString("| 2 | `\\|\\|` | left | Logical OR |\n")
	b.WriteString("| 3 | `&&` | left | Logical AND |\n")
	b.WriteString("| 4 | `==`, `!=` | left | Equality |\n")
	b.WriteString("| 5 | `<`, `>`, `<=`, `>=` | left | Comparison |\n")
	b.WriteString("| 6 | `+`, `-` | left | Addition |\n")
	b.WriteString("| 7 | `*`, `/`, `%` | left | Multiplication |\n")
	b.WriteString("| 8 | `!`, `-` (unary) | right | Unary |\n")
	b.WriteString("| 9 | `.`, `[]`, `()` | left | Postfix |\n\n")
}

func writeKeywords(b *strings.Builder) {
	b.WriteString("## Keywords\n\n")
	b.WriteString("`component` `const` `else` `enum` `for` `func` `if` `import` `return` `struct` `unit` `var`\n\n")
	b.WriteString("Additionally, `true`, `false`, and `null` are pre-declared identifiers (not keywords).\n\n")
}

func writeSemantics(b *strings.Builder) {
	b.WriteString(`## Semantics

### Reactivity Model

SNGL uses compile-time dependency tracking. The compiler:

1. Tracks every binding's data dependencies
2. Emits update closures for each dependency
3. Generates platform-specific reactive code (e.g., JS Signal API, Go state fields)

No virtual DOM or runtime diffing is involved. Assignments to state trigger only the affected update handlers.

### Component Model

- Components are declared with ` + "`component Name(params...) [ChildrenType] { ... }`" + `
- Parameters in ` + "`()`" + ` define the component's public API
- Props are passed at instantiation: ` + "`Name(prop=value)`" + `
- Events use ` + "`@`" + ` prefix: ` + "`@click ClickEvent`" + `
- Bidirectional bindings use ` + "`:`" + ` prefix: ` + "`:value string`" + `
- Children type (after params): ` + "`list<component>`" + `, ` + "`component`" + `, ` + "`option<component>`" + `, or omitted (no children)
- ` + "`slot`" + ` projects caller's children into the component body

### Scoping

- State (` + "`var`" + `, ` + "`const`" + `) and functions are scoped to their component
- Component parameters become local variables in the component body
- ` + "`for`" + ` loop variables are scoped to the loop body
- Imported components are namespaced: ` + "`import \"widgets\"`" + ` → ` + "`widgets.Button`" + `

### Type System

Built-in types: ` + "`int`" + `, ` + "`float`" + `, ` + "`bool`" + `, ` + "`string`" + `, ` + "`color`" + `, ` + "`date`" + `, ` + "`measurement`" + `, ` + "`dyn`" + `

Generic types: ` + "`list<T>`" + `, ` + "`option<T>`" + `

User-defined types: ` + "`struct`" + `, ` + "`enum`" + `, ` + "`unit`" + `
`)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "specgen: "+format+"\n", args...)
	os.Exit(1)
}
